import type { CategoryDbSchema } from "~/app/category/schema/CategoryDbSchema";
import type { CategorySpotlightDbSchema } from "~/app/category/schema/CategorySpotlightDbSchema";
import type { CategoryMissDbSchema } from "~/app/category-miss/schema/CategoryMissDbSchema";
import type { DraftDbSchema } from "~/app/draft/schema/DraftDbSchema";
import type { FavouriteDbSchema } from "~/app/favourite/schema/FavouriteDbSchema";
import type { FeedDbSchema } from "~/app/feed/schema/FeedDbSchema";
import type { FeedbackDbSchema } from "~/app/feedback/schema/FeedbackDbSchema";
import type { FlagDbSchema } from "~/app/flag/schema/FlagDbSchema";
import type { GalleryDbSchema } from "~/app/gallery/schema/GalleryDbSchema";
import type { GalleryItemDbSchema } from "~/app/gallery-item/schema/GalleryItemDbSchema";
import type { GitHubDbSchema } from "~/app/github/schema/GitHubDbSchema";
import type { IgnoreDbSchema } from "~/app/ignore/schema/IgnoreDbSchema";
import type { ListingDbSchema } from "~/app/listing/schema/ListingDbSchema";
import type { ListingEventDbSchema } from "~/app/listing-event/schema/ListingEventDbSchema";
import type { LocationDbSchema } from "~/app/location/schema/LocationDbSchema";
import type { MessageGalleryDbSchema } from "~/app/message-gallery/schema/MessageGalleryDbSchema";
import type { MessageLocationDbSchema } from "~/app/message-location/schema/MessageLocationDbSchema";
import type { MessageSystemDbSchema } from "~/app/message-system/schema/MessageSystemDbSchema";
import type { MessageTextDbSchema } from "~/app/message-text/schema/MessageTextDbSchema";
import type { MessageThreadDbSchema } from "~/app/message-thread/schema/MessageThreadDbSchema";
import type { MessageThreadUserDbSchema } from "~/app/message-thread-user/schema/MessageThreadUserDbSchema";
import type { TransactionDbSchema } from "~/app/transaction/schema/ListingTransactionDbSchema";
import type { TransactionStatusDbSchema } from "~/app/transaction-status/schema/ListingTransactionStatusDbSchema";
import type { UploadDbSchema } from "~/app/upload/schema/UploadDbSchema";
import type { UserExDbSchema } from "~/app/user-ex/schema/UserExDbSchema";
import type { auth } from "~/auth/auth";

export interface Database {
	category_miss: CategoryMissDbSchema.Type;
	category_spotlight: CategorySpotlightDbSchema.Type;
	category: CategoryDbSchema.Type;
	draft: DraftDbSchema.Type;
	favourite: FavouriteDbSchema.Type;
	feed: FeedDbSchema.Type;
	feedback: FeedbackDbSchema.Type;
	flag: FlagDbSchema.Type;
	gallery_item: GalleryItemDbSchema.Type;
	gallery: GalleryDbSchema.Type;
	github: GitHubDbSchema.Type;
	ignore: IgnoreDbSchema.Type;
	listing_event: ListingEventDbSchema.Type;
	listing: ListingDbSchema.Type;
	location: LocationDbSchema.Type;
	message_gallery: MessageGalleryDbSchema.Type;
	message_location: MessageLocationDbSchema.Type;
	message_system: MessageSystemDbSchema.Type;
	message_text: MessageTextDbSchema.Type;
	message_thread_user: MessageThreadUserDbSchema.Type;
	message_thread: MessageThreadDbSchema.Type;
	transaction_status: TransactionStatusDbSchema.Type;
	transaction: TransactionDbSchema.Type;
	upload: UploadDbSchema.Type;
	user_ex: UserExDbSchema.Type;
	user: typeof auth.$Infer.Session.user;
}
