import type { CategoryDbSchema } from "~/app/category/schema/CategoryDbSchema";
import type { CategorySpotlightDbSchema } from "~/app/category/schema/CategorySpotlightDbSchema";
import type { CategoryMissDbSchema } from "~/app/category-miss/schema/CategoryMissDbSchema";
import type { FavouriteDbSchema } from "~/app/favourite/schema/FavouriteDbSchema";
import type { FeedDbSchema } from "~/app/feed/schema/FeedDbSchema";
import type { GalleryDbSchema } from "~/app/gallery/schema/GalleryDbSchema";
import type { GalleryItemDbSchema } from "~/app/gallery-item/schema/GalleryItemDbSchema";
import type { IgnoreDbSchema } from "~/app/ignore/schema/IgnoreDbSchema";
import type { ListingDbSchema } from "~/app/listing/schema/ListingDbSchema";
import type { ListingFlagDbSchema } from "~/app/listing-flag/schema/ListingFlagDbSchema";
import type { ListingGalleryDbSchema } from "~/app/listing-gallery/schema/ListingGalleryDbSchema";
import type { ListingScoreDbSchema } from "~/app/listing-score/schema/ListingScoreDbSchema";
import type { ListingTransactionDbSchema } from "~/app/listing-transaction/schema/ListingTransactionDbSchema";
import type { ListingTransactionGalleryDbSchema } from "~/app/listing-transaction-gallery/schema/ListingTransactionGalleryDbSchema";
import type { ListingTransactionLocationDbSchema } from "~/app/listing-transaction-location/schema/ListingTransactionLocationDbSchema";
import type { ListingTransactionMessageDbSchema } from "~/app/listing-transaction-message/schema/ListingTransactionMessageDbSchema";
import type { ListingTransactionStatusDbSchema } from "~/app/listing-transaction-status/schema/ListingTransactionStatusDbSchema";
import type { LocationDbSchema } from "~/app/location/schema/LocationDbSchema";
import type { UploadDbSchema } from "~/app/upload/schema/UploadDbSchema";
import type { UserExDbSchema } from "~/app/user-ex/schema/UserExDbSchema";
import type { auth } from "~/auth/auth";

export interface Database {
	category_miss: CategoryMissDbSchema.Type;
	category_spotlight: CategorySpotlightDbSchema.Type;
	category: CategoryDbSchema.Type;
	feed: FeedDbSchema.Type;
	gallery_item: GalleryItemDbSchema.Type;
	gallery: GalleryDbSchema.Type;
	favourite: FavouriteDbSchema.Type;
	listing_flag: ListingFlagDbSchema.Type;
	listing_gallery: ListingGalleryDbSchema.Type;
	ignore: IgnoreDbSchema.Type;
	listing_score: ListingScoreDbSchema.Type;
	listing_transaction_gallery: ListingTransactionGalleryDbSchema.Type;
	listing_transaction_location: ListingTransactionLocationDbSchema.Type;
	listing_transaction_message: ListingTransactionMessageDbSchema.Type;
	listing_transaction_status: ListingTransactionStatusDbSchema.Type;
	listing_transaction: ListingTransactionDbSchema.Type;
	listing: ListingDbSchema.Type;
	location: LocationDbSchema.Type;
	upload: UploadDbSchema.Type;
	user_ex: UserExDbSchema.Type;
	user: typeof auth.$Infer.Session.user;
}
