import type { auth } from "~/auth/auth";
import type { BoardItemTableSchema } from "~/database/@table/BoardItemTableSchema";
import type { BoardTableSchema } from "~/database/@table/BoardTableSchema";
import type { CategoryMissTableSchema } from "~/database/@table/CategoryMissTableSchema";
import type { CategorySpotlightTableSchema } from "~/database/@table/CategorySpotlightTableSchema";
import type { CategoryTableSchema } from "~/database/@table/CategoryTableSchema";
import type { DraftTableSchema } from "~/database/@table/DraftTableSchema";
import type { FavouriteTableSchema } from "~/database/@table/FavouriteTableSchema";
import type { FeedTableSchema } from "~/database/@table/FeedTableSchema";
import type { FlagTableSchema } from "~/database/@table/FlagTableSchema";
import type { GalleryItemTableSchema } from "~/database/@table/GalleryItemTableSchema";
import type { GalleryTableSchema } from "~/database/@table/GalleryTableSchema";
import type { GitHubTableSchema } from "~/database/@table/GitHubTableSchema";
import type { IgnoreTableSchema } from "~/database/@table/IgnoreTableSchema";
import type { ListingEventTableSchema } from "~/database/@table/ListingEventTableSchema";
import type { ListingTableSchema } from "~/database/@table/ListingTableSchema";
import type { LocationTableSchema } from "~/database/@table/LocationTableSchema";
import type { MessageGalleryTableSchema } from "~/database/@table/MessageGalleryTableSchema";
import type { MessageLocationTableSchema } from "~/database/@table/MessageLocationTableSchema";
import type { MessagePackageTableSchema } from "~/database/@table/MessagePackageTableSchema";
import type { MessagePersonalTableSchema } from "~/database/@table/MessagePersonalTableSchema";
import type { MessageSystemTableSchema } from "~/database/@table/MessageSystemTableSchema";
import type { MessageTextTableSchema } from "~/database/@table/MessageTextTableSchema";
import type { MessageThreadTableSchema } from "~/database/@table/MessageThreadTableSchema";
import type { MessageThreadUserTableSchema } from "~/database/@table/MessageThreadUserTableSchema";
import type { ThumbTableSchema } from "~/database/@table/ThumbTableSchema";
import type { TransactionStatusTableSchema } from "~/database/@table/TransactionStatusTableSchema";
import type { TransactionTableSchema } from "~/database/@table/TransactionTableSchema";
import type { UploadTableSchema } from "~/database/@table/UploadTableSchema";
import type { UserEventTableSchema } from "~/database/@table/UserEventTableSchema";
import type { UserExTableSchema } from "~/database/@table/UserExTableSchema";

export interface Database {
	board: BoardTableSchema.Type;
	board_item: BoardItemTableSchema.Type;
	category_miss: CategoryMissTableSchema.Type;
	category_spotlight: CategorySpotlightTableSchema.Type;
	category: CategoryTableSchema.Type;
	draft: DraftTableSchema.Type;
	favourite: FavouriteTableSchema.Type;
	feed: FeedTableSchema.Type;
	thumb: ThumbTableSchema.Type;
	flag: FlagTableSchema.Type;
	gallery_item: GalleryItemTableSchema.Type;
	gallery: GalleryTableSchema.Type;
	github: GitHubTableSchema.Type;
	ignore: IgnoreTableSchema.Type;
	listing_event: ListingEventTableSchema.Type;
	listing: ListingTableSchema.Type;
	location: LocationTableSchema.Type;
	message_gallery: MessageGalleryTableSchema.Type;
	message_location: MessageLocationTableSchema.Type;
	message_package: MessagePackageTableSchema.Type;
	message_personal: MessagePersonalTableSchema.Type;
	message_system: MessageSystemTableSchema.Type;
	message_text: MessageTextTableSchema.Type;
	message_thread_user: MessageThreadUserTableSchema.Type;
	message_thread: MessageThreadTableSchema.Type;
	transaction_status: TransactionStatusTableSchema.Type;
	transaction: TransactionTableSchema.Type;
	upload: UploadTableSchema.Type;
	user_event: UserEventTableSchema.Type;
	user_ex: UserExTableSchema.Type;
	user: auth.User;
}
