model = "qwen/qwen3-coder-30b"
model_provider = "lmstudio"
oss_provider = "lmstudio"

approval_policy = "on-request"
sandbox_mode = "workspace-write"

model_context_window = 262144
model_reasoning_summary = "none"
model_verbosity = "low"
model_supports_reasoning_summaries = true

[model_providers.lmstudio]
name = "LM Studio"
base_url = "http://localhost:1234/v1"
wire_api = "responses"
