// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { apiBoardItemsErrors, tApiBoardItemsRequest, tApiBoardItemsResponse } from './types.gen';
import { zApiBoardItemsData, zApiBoardItemsResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Return current items on the board.
 *
 * Return current items on the board.
 */
export const apiBoardItems = <ThrowOnError extends boolean = false>(options?: Options<tApiBoardItemsRequest, ThrowOnError>) => (options?.client ?? client).get<tApiBoardItemsResponse, apiBoardItemsErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiBoardItemsData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiBoardItemsResponse.parseAsync(data),
    url: '/api/arkini/board/items',
    ...options
});
