// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Item on the board
 */
export const zItem = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'ID of the item'
    }),
    x: z.number().register(z.globalRegistry, {
        description: 'X coordinate of the item'
    }),
    y: z.number().register(z.globalRegistry, {
        description: 'Y coordinate of the item'
    })
}).register(z.globalRegistry, {
    description: 'Item on the board'
});

export type zItem = z.infer<typeof zItem>;

/**
 * Items on the board
 */
export const zItemsResponse = z.array(zItem).register(z.globalRegistry, {
    description: 'Items on the board'
});

export type zItemsResponse = z.infer<typeof zItemsResponse>;

/**
 * Type of notice
 */
export const zNoticeTypeEnum = z.enum([
    'info',
    'warning',
    'error'
]).register(z.globalRegistry, {
    description: 'Type of notice'
});

export type zNoticeTypeEnum = z.infer<typeof zNoticeTypeEnum>;

/**
 * Just a note sent from various reasons, usually when something is fucked up.
 */
export const zNotice = z.object({
    message: z.string().register(z.globalRegistry, {
        description: 'Message'
    }),
    type: zNoticeTypeEnum
}).register(z.globalRegistry, {
    description: 'Just a note sent from various reasons, usually when something is fucked up.'
});

export type zNotice = z.infer<typeof zNotice>;

export const zApiBoardItemsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type zapiBoardItemsRequest = z.infer<typeof zApiBoardItemsData>;

/**
 * Items on the board
 */
export const zApiBoardItemsResponse = zItemsResponse;

export type zapiBoardItemsResponse = z.infer<typeof zApiBoardItemsResponse>;
