// This file is auto-generated by @hey-api/openapi-ts

export const sCategory = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        group: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        slug: {
            type: 'string'
        },
        sort: {
            type: 'number'
        },
        locale: {
            type: 'string'
        }
    },
    required: [
        'id',
        'group',
        'category',
        'slug',
        'sort',
        'locale'
    ]
} as const;

export const sNotice = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/NoticeTypeEnum'
        }
    },
    required: [
        'message',
        'type'
    ]
} as const;

export const sNoticeTypeEnum = {
    type: 'string',
    enum: [
        'info',
        'warning',
        'error'
    ]
} as const;

export const sCategoryQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/CategoryFilter'
        },
        where: {
            $ref: '#/components/schemas/CategoryWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CategorySort'
            }
        }
    }
} as const;

export const sCursor = {
    type: 'object',
    properties: {
        page: {
            type: 'number',
            minimum: 0
        },
        size: {
            type: 'number',
            minimum: 1,
            maximum: 1000
        }
    },
    required: [
        'page',
        'size'
    ]
} as const;

export const sCategoryFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        group: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        locale: {
            type: 'string'
        },
        localeIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        slug: {
            type: 'string'
        }
    }
} as const;

export const sCategoryWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        group: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        locale: {
            type: 'string'
        },
        localeIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        slug: {
            type: 'string'
        }
    }
} as const;

export const sCategorySort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/CategorySortField'
        },
        order: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'order'
    ]
} as const;

export const sCategorySortField = {
    type: 'string',
    enum: [
        'group',
        'category',
        'sort'
    ]
} as const;

export const sOrderEnum = {
    type: 'string',
    enum: [
        'asc',
        'desc'
    ]
} as const;

export const sCategoryItem = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        group: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        slug: {
            type: 'string'
        },
        sort: {
            type: 'number'
        },
        locale: {
            type: 'string'
        }
    },
    required: [
        'id',
        'group',
        'category',
        'slug',
        'sort',
        'locale'
    ]
} as const;

export const sCount = {
    type: 'object',
    properties: {
        where: {
            type: 'number'
        },
        filter: {
            type: 'number'
        },
        total: {
            type: 'number'
        },
        isEmpty: {
            type: 'boolean'
        },
        isFilterEmpty: {
            type: 'boolean'
        }
    },
    required: [
        'where',
        'filter',
        'total',
        'isEmpty',
        'isFilterEmpty'
    ]
} as const;

export const sCategoryCountQuery = {
    type: 'object',
    properties: {
        filter: {
            $ref: '#/components/schemas/CategoryFilter'
        },
        where: {
            $ref: '#/components/schemas/CategoryWhere'
        },
        count: {
            type: 'array',
            items: {
                type: 'string',
                enum: [
                    'total',
                    'filter',
                    'where'
                ]
            }
        }
    }
} as const;

export const sLocation = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        query: {
            type: 'string'
        },
        lang: {
            type: 'string'
        },
        country: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        county: {
            anyOf: [
                {
                    type: 'null'
                },
                {
                    type: 'string'
                }
            ]
        },
        municipality: {
            anyOf: [
                {
                    type: 'null'
                },
                {
                    type: 'string'
                }
            ]
        },
        state: {
            anyOf: [
                {
                    type: 'null'
                },
                {
                    type: 'string'
                }
            ]
        },
        address: {
            type: 'string'
        },
        city: {
            anyOf: [
                {
                    type: 'null'
                },
                {
                    type: 'string'
                }
            ]
        },
        street: {
            anyOf: [
                {
                    type: 'null'
                },
                {
                    type: 'string'
                }
            ]
        },
        zip: {
            anyOf: [
                {
                    type: 'null'
                },
                {
                    type: 'string'
                }
            ]
        },
        confidence: {
            type: 'number'
        },
        hash: {
            type: 'string'
        },
        lat: {
            type: 'number'
        },
        lon: {
            type: 'number'
        }
    },
    required: [
        'id',
        'query',
        'lang',
        'country',
        'code',
        'county',
        'municipality',
        'state',
        'address',
        'city',
        'street',
        'zip',
        'confidence',
        'hash',
        'lat',
        'lon'
    ]
} as const;

export const sLocationAutocomplete = {
    type: 'object',
    properties: {
        text: {
            type: 'string'
        },
        lang: {
            type: 'string',
            minLength: 2,
            maxLength: 8
        }
    },
    required: [
        'text',
        'lang'
    ]
} as const;

export const sLocationQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/LocationFilter'
        },
        where: {
            $ref: '#/components/schemas/LocationWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/LocationSort'
            }
        }
    }
} as const;

export const sLocationFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        query: {
            type: 'string'
        },
        lang: {
            type: 'string'
        },
        country: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        confidenceMin: {
            type: 'number'
        }
    }
} as const;

export const sLocationWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        query: {
            type: 'string'
        },
        lang: {
            type: 'string'
        },
        country: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        confidenceMin: {
            type: 'number'
        }
    }
} as const;

export const sLocationSort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/LocationSortField'
        },
        order: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'order'
    ]
} as const;

export const sLocationSortField = {
    type: 'string',
    enum: [
        'confidence',
        'query',
        'country',
        'address'
    ]
} as const;
