// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { apiCategoryCollectionErrors, apiCategoryCountErrors, apiCategoryFetchErrors, apiListingSellerInfoErrors, apiLocationAutocompleteErrors, apiLocationFetchErrors, apiUploadFetchErrors, apiUserEventBuyerErrors, apiUserEventSellerErrors, tApiCategoryCollectionRequest, tApiCategoryCollectionResponse, tApiCategoryCountRequest, tApiCategoryCountResponse, tApiCategoryFetchRequest, tApiCategoryFetchResponse, tApiListingSellerInfoRequest, tApiListingSellerInfoResponse, tApiLocationAutocompleteRequest, tApiLocationAutocompleteResponse, tApiLocationFetchRequest, tApiLocationFetchResponse, tApiUploadFetchRequest, tApiUploadFetchResponse, tApiUserEventBuyerRequest, tApiUserEventBuyerResponse, tApiUserEventSellerRequest, tApiUserEventSellerResponse } from './types.gen';
import { zApiCategoryCollectionData, zApiCategoryCollectionResponse, zApiCategoryCountData, zApiCategoryCountResponse, zApiCategoryFetchData, zApiCategoryFetchResponse, zApiListingSellerInfoData, zApiListingSellerInfoResponse, zApiLocationAutocompleteData, zApiLocationAutocompleteResponse, zApiLocationFetchData, zApiLocationFetchResponse, zApiUploadFetchData, zApiUploadFetchResponse, zApiUserEventBuyerData, zApiUserEventBuyerResponse, zApiUserEventSellerData, zApiUserEventSellerResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Return a category based on the provided query
 */
export const apiCategoryFetch = <ThrowOnError extends boolean = false>(options?: Options<tApiCategoryFetchRequest, ThrowOnError>) => (options?.client ?? client).post<tApiCategoryFetchResponse, apiCategoryFetchErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiCategoryFetchData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiCategoryFetchResponse.parseAsync(data),
    url: '/api/session/category/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Returns categories based on provided parameters
 */
export const apiCategoryCollection = <ThrowOnError extends boolean = false>(options?: Options<tApiCategoryCollectionRequest, ThrowOnError>) => (options?.client ?? client).post<tApiCategoryCollectionResponse, apiCategoryCollectionErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiCategoryCollectionData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiCategoryCollectionResponse.parseAsync(data),
    url: '/api/session/category/collection',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Returns count of categories based on provided query
 */
export const apiCategoryCount = <ThrowOnError extends boolean = false>(options?: Options<tApiCategoryCountRequest, ThrowOnError>) => (options?.client ?? client).post<tApiCategoryCountResponse, apiCategoryCountErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiCategoryCountData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiCategoryCountResponse.parseAsync(data),
    url: '/api/session/category/count',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Return seller info for a listing.
 */
export const apiListingSellerInfo = <ThrowOnError extends boolean = false>(options: Options<tApiListingSellerInfoRequest, ThrowOnError>) => (options.client ?? client).post<tApiListingSellerInfoResponse, apiListingSellerInfoErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiListingSellerInfoData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiListingSellerInfoResponse.parseAsync(data),
    url: '/api/session/listing/{listingId}/seller-info',
    ...options
});

/**
 * Return a location autocomplete
 */
export const apiLocationAutocomplete = <ThrowOnError extends boolean = false>(options?: Options<tApiLocationAutocompleteRequest, ThrowOnError>) => (options?.client ?? client).post<tApiLocationAutocompleteResponse, apiLocationAutocompleteErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiLocationAutocompleteData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiLocationAutocompleteResponse.parseAsync(data),
    url: '/api/session/location/autocomplete',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Return a location based on the provided query
 */
export const apiLocationFetch = <ThrowOnError extends boolean = false>(options?: Options<tApiLocationFetchRequest, ThrowOnError>) => (options?.client ?? client).post<tApiLocationFetchResponse, apiLocationFetchErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiLocationFetchData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiLocationFetchResponse.parseAsync(data),
    url: '/api/session/location/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Return an upload item based on the provided query
 */
export const apiUploadFetch = <ThrowOnError extends boolean = false>(options?: Options<tApiUploadFetchRequest, ThrowOnError>) => (options?.client ?? client).post<tApiUploadFetchResponse, apiUploadFetchErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiUploadFetchData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiUploadFetchResponse.parseAsync(data),
    url: '/api/session/upload/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Return buyer info for a user event.
 */
export const apiUserEventBuyer = <ThrowOnError extends boolean = false>(options: Options<tApiUserEventBuyerRequest, ThrowOnError>) => (options.client ?? client).post<tApiUserEventBuyerResponse, apiUserEventBuyerErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiUserEventBuyerData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiUserEventBuyerResponse.parseAsync(data),
    url: '/api/session/user-event/{userId}/buyer',
    ...options
});

/**
 * Return seller info for a user event.
 */
export const apiUserEventSeller = <ThrowOnError extends boolean = false>(options: Options<tApiUserEventSellerRequest, ThrowOnError>) => (options.client ?? client).post<tApiUserEventSellerResponse, apiUserEventSellerErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiUserEventSellerData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiUserEventSellerResponse.parseAsync(data),
    url: '/api/session/user-event/{userId}/seller',
    ...options
});
