/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './@routes/__root'
import { Route as LocaleRouteImport } from './@routes/$locale'
import { Route as IndexRouteImport } from './@routes/index'
import { Route as LocaleIndexRouteImport } from './@routes/$locale/index'
import { Route as LocaleUserRouteImport } from './@routes/$locale/user'
import { Route as LocaleShopRouteImport } from './@routes/$locale/shop'
import { Route as LocaleFeedRouteImport } from './@routes/$locale/feed'
import { Route as LocaleDashboardRouteImport } from './@routes/$locale/dashboard'
import { Route as LocaleBagRouteImport } from './@routes/$locale/bag'
import { Route as LocaleListingWizardRouteImport } from './@routes/$locale/listing/wizard'
import { Route as LocaleListingMyRouteImport } from './@routes/$locale/listing/my'
import { Route as LocaleDevSeedRouteImport } from './@routes/$locale/dev/seed'
import { Route as LocaleListingWizardStartRouteImport } from './@routes/$locale/listing/wizard/start'
import { Route as LocaleListingWizardPhotosRouteImport } from './@routes/$locale/listing/wizard/photos'
import { Route as LocaleListingWizardCategoryGroupRouteImport } from './@routes/$locale/listing/wizard/category-group'
import { Route as LocaleListingIdViewRouteImport } from './@routes/$locale/listing/$id/view'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleUserRoute = LocaleUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleShopRoute = LocaleShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFeedRoute = LocaleFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDashboardRoute = LocaleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBagRoute = LocaleBagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleListingWizardRoute = LocaleListingWizardRouteImport.update({
  id: '/listing/wizard',
  path: '/listing/wizard',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleListingMyRoute = LocaleListingMyRouteImport.update({
  id: '/listing/my',
  path: '/listing/my',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDevSeedRoute = LocaleDevSeedRouteImport.update({
  id: '/dev/seed',
  path: '/dev/seed',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleListingWizardStartRoute =
  LocaleListingWizardStartRouteImport.update({
    id: '/start',
    path: '/start',
    getParentRoute: () => LocaleListingWizardRoute,
  } as any)
const LocaleListingWizardPhotosRoute =
  LocaleListingWizardPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => LocaleListingWizardRoute,
  } as any)
const LocaleListingWizardCategoryGroupRoute =
  LocaleListingWizardCategoryGroupRouteImport.update({
    id: '/category-group',
    path: '/category-group',
    getParentRoute: () => LocaleListingWizardRoute,
  } as any)
const LocaleListingIdViewRoute = LocaleListingIdViewRouteImport.update({
  id: '/listing/$id/view',
  path: '/listing/$id/view',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/bag': typeof LocaleBagRoute
  '/$locale/dashboard': typeof LocaleDashboardRoute
  '/$locale/feed': typeof LocaleFeedRoute
  '/$locale/shop': typeof LocaleShopRoute
  '/$locale/user': typeof LocaleUserRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/dev/seed': typeof LocaleDevSeedRoute
  '/$locale/listing/my': typeof LocaleListingMyRoute
  '/$locale/listing/wizard': typeof LocaleListingWizardRouteWithChildren
  '/$locale/listing/$id/view': typeof LocaleListingIdViewRoute
  '/$locale/listing/wizard/category-group': typeof LocaleListingWizardCategoryGroupRoute
  '/$locale/listing/wizard/photos': typeof LocaleListingWizardPhotosRoute
  '/$locale/listing/wizard/start': typeof LocaleListingWizardStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/bag': typeof LocaleBagRoute
  '/$locale/dashboard': typeof LocaleDashboardRoute
  '/$locale/feed': typeof LocaleFeedRoute
  '/$locale/shop': typeof LocaleShopRoute
  '/$locale/user': typeof LocaleUserRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/dev/seed': typeof LocaleDevSeedRoute
  '/$locale/listing/my': typeof LocaleListingMyRoute
  '/$locale/listing/wizard': typeof LocaleListingWizardRouteWithChildren
  '/$locale/listing/$id/view': typeof LocaleListingIdViewRoute
  '/$locale/listing/wizard/category-group': typeof LocaleListingWizardCategoryGroupRoute
  '/$locale/listing/wizard/photos': typeof LocaleListingWizardPhotosRoute
  '/$locale/listing/wizard/start': typeof LocaleListingWizardStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/bag': typeof LocaleBagRoute
  '/$locale/dashboard': typeof LocaleDashboardRoute
  '/$locale/feed': typeof LocaleFeedRoute
  '/$locale/shop': typeof LocaleShopRoute
  '/$locale/user': typeof LocaleUserRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/dev/seed': typeof LocaleDevSeedRoute
  '/$locale/listing/my': typeof LocaleListingMyRoute
  '/$locale/listing/wizard': typeof LocaleListingWizardRouteWithChildren
  '/$locale/listing/$id/view': typeof LocaleListingIdViewRoute
  '/$locale/listing/wizard/category-group': typeof LocaleListingWizardCategoryGroupRoute
  '/$locale/listing/wizard/photos': typeof LocaleListingWizardPhotosRoute
  '/$locale/listing/wizard/start': typeof LocaleListingWizardStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/bag'
    | '/$locale/dashboard'
    | '/$locale/feed'
    | '/$locale/shop'
    | '/$locale/user'
    | '/$locale/'
    | '/$locale/dev/seed'
    | '/$locale/listing/my'
    | '/$locale/listing/wizard'
    | '/$locale/listing/$id/view'
    | '/$locale/listing/wizard/category-group'
    | '/$locale/listing/wizard/photos'
    | '/$locale/listing/wizard/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/bag'
    | '/$locale/dashboard'
    | '/$locale/feed'
    | '/$locale/shop'
    | '/$locale/user'
    | '/$locale'
    | '/$locale/dev/seed'
    | '/$locale/listing/my'
    | '/$locale/listing/wizard'
    | '/$locale/listing/$id/view'
    | '/$locale/listing/wizard/category-group'
    | '/$locale/listing/wizard/photos'
    | '/$locale/listing/wizard/start'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/bag'
    | '/$locale/dashboard'
    | '/$locale/feed'
    | '/$locale/shop'
    | '/$locale/user'
    | '/$locale/'
    | '/$locale/dev/seed'
    | '/$locale/listing/my'
    | '/$locale/listing/wizard'
    | '/$locale/listing/$id/view'
    | '/$locale/listing/wizard/category-group'
    | '/$locale/listing/wizard/photos'
    | '/$locale/listing/wizard/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/user': {
      id: '/$locale/user'
      path: '/user'
      fullPath: '/$locale/user'
      preLoaderRoute: typeof LocaleUserRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/shop': {
      id: '/$locale/shop'
      path: '/shop'
      fullPath: '/$locale/shop'
      preLoaderRoute: typeof LocaleShopRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/feed': {
      id: '/$locale/feed'
      path: '/feed'
      fullPath: '/$locale/feed'
      preLoaderRoute: typeof LocaleFeedRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/dashboard': {
      id: '/$locale/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/dashboard'
      preLoaderRoute: typeof LocaleDashboardRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/bag': {
      id: '/$locale/bag'
      path: '/bag'
      fullPath: '/$locale/bag'
      preLoaderRoute: typeof LocaleBagRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/listing/wizard': {
      id: '/$locale/listing/wizard'
      path: '/listing/wizard'
      fullPath: '/$locale/listing/wizard'
      preLoaderRoute: typeof LocaleListingWizardRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/listing/my': {
      id: '/$locale/listing/my'
      path: '/listing/my'
      fullPath: '/$locale/listing/my'
      preLoaderRoute: typeof LocaleListingMyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/dev/seed': {
      id: '/$locale/dev/seed'
      path: '/dev/seed'
      fullPath: '/$locale/dev/seed'
      preLoaderRoute: typeof LocaleDevSeedRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/listing/wizard/start': {
      id: '/$locale/listing/wizard/start'
      path: '/start'
      fullPath: '/$locale/listing/wizard/start'
      preLoaderRoute: typeof LocaleListingWizardStartRouteImport
      parentRoute: typeof LocaleListingWizardRoute
    }
    '/$locale/listing/wizard/photos': {
      id: '/$locale/listing/wizard/photos'
      path: '/photos'
      fullPath: '/$locale/listing/wizard/photos'
      preLoaderRoute: typeof LocaleListingWizardPhotosRouteImport
      parentRoute: typeof LocaleListingWizardRoute
    }
    '/$locale/listing/wizard/category-group': {
      id: '/$locale/listing/wizard/category-group'
      path: '/category-group'
      fullPath: '/$locale/listing/wizard/category-group'
      preLoaderRoute: typeof LocaleListingWizardCategoryGroupRouteImport
      parentRoute: typeof LocaleListingWizardRoute
    }
    '/$locale/listing/$id/view': {
      id: '/$locale/listing/$id/view'
      path: '/listing/$id/view'
      fullPath: '/$locale/listing/$id/view'
      preLoaderRoute: typeof LocaleListingIdViewRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleListingWizardRouteChildren {
  LocaleListingWizardCategoryGroupRoute: typeof LocaleListingWizardCategoryGroupRoute
  LocaleListingWizardPhotosRoute: typeof LocaleListingWizardPhotosRoute
  LocaleListingWizardStartRoute: typeof LocaleListingWizardStartRoute
}

const LocaleListingWizardRouteChildren: LocaleListingWizardRouteChildren = {
  LocaleListingWizardCategoryGroupRoute: LocaleListingWizardCategoryGroupRoute,
  LocaleListingWizardPhotosRoute: LocaleListingWizardPhotosRoute,
  LocaleListingWizardStartRoute: LocaleListingWizardStartRoute,
}

const LocaleListingWizardRouteWithChildren =
  LocaleListingWizardRoute._addFileChildren(LocaleListingWizardRouteChildren)

interface LocaleRouteChildren {
  LocaleBagRoute: typeof LocaleBagRoute
  LocaleDashboardRoute: typeof LocaleDashboardRoute
  LocaleFeedRoute: typeof LocaleFeedRoute
  LocaleShopRoute: typeof LocaleShopRoute
  LocaleUserRoute: typeof LocaleUserRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleDevSeedRoute: typeof LocaleDevSeedRoute
  LocaleListingMyRoute: typeof LocaleListingMyRoute
  LocaleListingWizardRoute: typeof LocaleListingWizardRouteWithChildren
  LocaleListingIdViewRoute: typeof LocaleListingIdViewRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleBagRoute: LocaleBagRoute,
  LocaleDashboardRoute: LocaleDashboardRoute,
  LocaleFeedRoute: LocaleFeedRoute,
  LocaleShopRoute: LocaleShopRoute,
  LocaleUserRoute: LocaleUserRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleDevSeedRoute: LocaleDevSeedRoute,
  LocaleListingMyRoute: LocaleListingMyRoute,
  LocaleListingWizardRoute: LocaleListingWizardRouteWithChildren,
  LocaleListingIdViewRoute: LocaleListingIdViewRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
