import type { auth } from "~/server/auth/auth";
import type { ActivityTableSchema } from "~/server/database/@table/ActivityTableSchema";
import type { AgentStreamTableSchema } from "~/server/database/@table/AgentStreamTableSchema";
import type { AgentThreadTableSchema } from "~/server/database/@table/AgentThreadTableSchema";
import type { AgentUsageTableSchema } from "~/server/database/@table/AgentUsageTableSchema";
import type { CategoryMissTableSchema } from "~/server/database/@table/CategoryMissTableSchema";
import type { CategorySpotlightTableSchema } from "~/server/database/@table/CategorySpotlightTableSchema";
import type { CategoryTableSchema } from "~/server/database/@table/CategoryTableSchema";
import type { DraftAttrDecimalTableSchema } from "~/server/database/@table/DraftAttrDecimalTableSchema";
import type { DraftAttrEnumMultiTableSchema } from "~/server/database/@table/DraftAttrEnumMultiTableSchema";
import type { DraftAttrEnumSingleTableSchema } from "~/server/database/@table/DraftAttrEnumSingleTableSchema";
import type { DraftAttrNumberTableSchema } from "~/server/database/@table/DraftAttrNumberTableSchema";
import type { DraftAttrTextTableSchema } from "~/server/database/@table/DraftAttrTextTableSchema";
import type { DraftTableSchema } from "~/server/database/@table/DraftTableSchema";
import type { FavouriteTableSchema } from "~/server/database/@table/FavouriteTableSchema";
import type { FeedTableSchema } from "~/server/database/@table/FeedTableSchema";
import type { FieldOptionTableSchema } from "~/server/database/@table/FieldOptionTableSchema";
import type { FieldTableSchema } from "~/server/database/@table/FieldTableSchema";
import type { FlagTableSchema } from "~/server/database/@table/FlagTableSchema";
import type { GalleryItemTableSchema } from "~/server/database/@table/GalleryItemTableSchema";
import type { GalleryTableSchema } from "~/server/database/@table/GalleryTableSchema";
import type { GitHubTableSchema } from "~/server/database/@table/GitHubTableSchema";
import type { IgnoreTableSchema } from "~/server/database/@table/IgnoreTableSchema";
import type { ListingEventTableSchema } from "~/server/database/@table/ListingEventTableSchema";
import type { ListingSpotlightTableSchema } from "~/server/database/@table/ListingSpotlightTableSchema";
import type { ListingTableSchema } from "~/server/database/@table/ListingTableSchema";
import type { LocationTableSchema } from "~/server/database/@table/LocationTableSchema";
import type { RateLimitEventTableSchema } from "~/server/database/@table/RateLimitEventTableSchema";
import type { RateLimitRuleTableSchema } from "~/server/database/@table/RateLimitRuleTableSchema";
import type { ResourceDefinitionTableSchema } from "~/server/database/@table/ResourceDefinitionTableSchema";
import type { ThumbTableSchema } from "~/server/database/@table/ThumbTableSchema";
import type { TransactionEntryTableSchema } from "~/server/database/@table/TransactionEntryTableSchema";
import type { TransactionTableSchema } from "~/server/database/@table/TransactionTableSchema";
import type { TransactionUserTableSchema } from "~/server/database/@table/TransactionUserTableSchema";
import type { TranslationTableSchema } from "~/server/database/@table/TranslationTableSchema";
import type { UploadTableSchema } from "~/server/database/@table/UploadTableSchema";
import type { UserEventTableSchema } from "~/server/database/@table/UserEventTableSchema";
import type { UserExTableSchema } from "~/server/database/@table/UserExTableSchema";
import type { UserResourceLimitTableSchema } from "~/server/database/@table/UserResourceLimitTableSchema";
import type { UserRestrictionTableSchema } from "~/server/database/@table/UserRestrictionTableSchema";
import type { CategoryFieldTableSchema } from "./@table/CategoryFieldTableSchema";
import type { ListingAttrDecimalTableSchema } from "./@table/ListingAttrDecimalTableSchema";
import type { ListingAttrEnumMultiTableSchema } from "./@table/ListingAttrEnumMultiTableSchema";
import type { ListingAttrEnumSingleTableSchema } from "./@table/ListingAttrEnumSingleTableSchema";
import type { ListingAttrNumberTableSchema } from "./@table/ListingAttrNumberTableSchema";
import type { ListingAttrTextTableSchema } from "./@table/ListingAttrTextTableSchema";

export interface Database {
	activity: ActivityTableSchema.Type;
	agent_stream: AgentStreamTableSchema.Type;
	agent_thread: AgentThreadTableSchema.Type;
	agent_usage: AgentUsageTableSchema.Type;
	category_field: CategoryFieldTableSchema.Type;
	category_miss: CategoryMissTableSchema.Type;
	category_spotlight: CategorySpotlightTableSchema.Type;
	category: CategoryTableSchema.Type;
	draft: DraftTableSchema.Type;
	draft_attr_decimal: DraftAttrDecimalTableSchema.Type;
	draft_attr_number: DraftAttrNumberTableSchema.Type;
	draft_attr_enum_multi: DraftAttrEnumMultiTableSchema.Type;
	draft_attr_enum_single: DraftAttrEnumSingleTableSchema.Type;
	draft_attr_text: DraftAttrTextTableSchema.Type;
	favourite: FavouriteTableSchema.Type;
	feed: FeedTableSchema.Type;
	field: FieldTableSchema.Type;
	field_option: FieldOptionTableSchema.Type;
	flag: FlagTableSchema.Type;
	gallery_item: GalleryItemTableSchema.Type;
	gallery: GalleryTableSchema.Type;
	github: GitHubTableSchema.Type;
	ignore: IgnoreTableSchema.Type;
	listing_attr_decimal: ListingAttrDecimalTableSchema.Type;
	listing_attr_number: ListingAttrNumberTableSchema.Type;
	listing_attr_enum_multi: ListingAttrEnumMultiTableSchema.Type;
	listing_attr_enum_single: ListingAttrEnumSingleTableSchema.Type;
	listing_attr_text: ListingAttrTextTableSchema.Type;
	listing_event: ListingEventTableSchema.Type;
	listing_spotlight: ListingSpotlightTableSchema.Type;
	listing: ListingTableSchema.Type;
	location: LocationTableSchema.Type;
	rate_limit_event: RateLimitEventTableSchema.Type;
	rate_limit_rule: RateLimitRuleTableSchema.Type;
	resource_definition: ResourceDefinitionTableSchema.Type;
	thumb: ThumbTableSchema.Type;
	transaction_entry: TransactionEntryTableSchema.Type;
	transaction_user: TransactionUserTableSchema.Type;
	transaction: TransactionTableSchema.Type;
	translation: TranslationTableSchema.Type;
	upload: UploadTableSchema.Type;
	user_event: UserEventTableSchema.Type;
	user_ex: UserExTableSchema.Type;
	user_resource_limit: UserResourceLimitTableSchema.Type;
	user_restriction: UserRestrictionTableSchema.Type;
	user: auth.User;
}
