// This file is auto-generated by @hey-api/openapi-ts

export const sUpload = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        url: {
            type: 'string',
            format: 'uri'
        }
    },
    required: [
        'id',
        'url'
    ]
} as const;

export const sGalleryItem = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        galleryId: {
            type: 'string'
        },
        uploadId: {
            type: 'string'
        },
        sort: {
            type: 'number'
        },
        upload: {
            $ref: '#/components/schemas/Upload'
        }
    },
    required: [
        'id',
        'galleryId',
        'uploadId',
        'sort',
        'upload'
    ]
} as const;

export const sGallery = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/GalleryItem'
            }
        }
    },
    required: [
        'id',
        'items'
    ]
} as const;

export const sNoticeTypeEnum = {
    type: 'string',
    enum: [
        'info',
        'warning',
        'error'
    ]
} as const;

export const sNotice = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/NoticeTypeEnum'
        }
    },
    required: [
        'message',
        'type'
    ]
} as const;

export const sCursor = {
    type: 'object',
    properties: {
        page: {
            type: 'number',
            minimum: 0
        },
        size: {
            type: 'number',
            minimum: 1,
            maximum: 1000
        }
    },
    required: [
        'page',
        'size'
    ]
} as const;

export const sGalleryFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        }
    }
} as const;

export const sGalleryWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        }
    }
} as const;

export const sGallerySortField = {
    type: 'string',
    enum: [
        'createdAt'
    ]
} as const;

export const sOrderEnum = {
    type: 'string',
    enum: [
        'asc',
        'desc'
    ]
} as const;

export const sGallerySort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/GallerySortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sGalleryQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/GalleryFilter'
        },
        where: {
            $ref: '#/components/schemas/GalleryWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/GallerySort'
            }
        }
    }
} as const;

export const sGalleryItemSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                allOf: [
                    {
                        $ref: '#/components/schemas/GalleryItem'
                    },
                    {
                        properties: {
                            id: {
                                type: 'string'
                            }
                        },
                        required: [
                            'id'
                        ]
                    }
                ]
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sCount = {
    type: 'object',
    properties: {
        where: {
            type: 'number'
        },
        filter: {
            type: 'number'
        },
        total: {
            type: 'number'
        }
    },
    required: [
        'where',
        'filter',
        'total'
    ]
} as const;

export const sGalleryCountQuery = {
    type: 'object',
    properties: {
        filter: {
            $ref: '#/components/schemas/GalleryFilter'
        },
        where: {
            $ref: '#/components/schemas/GalleryWhere'
        },
        count: {
            type: 'array',
            items: {
                type: 'string',
                enum: [
                    'total',
                    'filter',
                    'where'
                ]
            }
        }
    }
} as const;

export const sMessageTypeEnum = {
    type: 'string',
    enum: [
        'text',
        'gallery',
        'location',
        'personal',
        'package',
        'date',
        'system'
    ]
} as const;

export const sMessageDirectionEnum = {
    type: 'string',
    enum: [
        'in',
        'out',
        'system'
    ]
} as const;

export const sMessageText = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        text: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/MessageTypeEnum'
        },
        direction: {
            $ref: '#/components/schemas/MessageDirectionEnum'
        }
    },
    required: [
        'id',
        'text',
        'createdAt',
        'type',
        'direction'
    ]
} as const;

export const sMessageGallery = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        galleryId: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/MessageTypeEnum'
        },
        direction: {
            $ref: '#/components/schemas/MessageDirectionEnum'
        },
        gallery: {
            $ref: '#/components/schemas/Gallery'
        }
    },
    required: [
        'id',
        'galleryId',
        'createdAt',
        'type',
        'direction',
        'gallery'
    ]
} as const;

export const sLocation = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        query: {
            type: 'string'
        },
        lang: {
            type: 'string'
        },
        country: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        county: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        municipality: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        state: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        address: {
            type: 'string'
        },
        city: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        street: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        zip: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        confidence: {
            type: 'number'
        },
        hash: {
            type: 'string'
        },
        lat: {
            type: 'number'
        },
        lon: {
            type: 'number'
        }
    },
    required: [
        'id',
        'query',
        'lang',
        'country',
        'code',
        'county',
        'municipality',
        'state',
        'address',
        'city',
        'street',
        'zip',
        'confidence',
        'hash',
        'lat',
        'lon'
    ]
} as const;

export const sMessageLocation = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        locationId: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/MessageTypeEnum'
        },
        direction: {
            $ref: '#/components/schemas/MessageDirectionEnum'
        },
        location: {
            $ref: '#/components/schemas/Location'
        }
    },
    required: [
        'id',
        'locationId',
        'createdAt',
        'type',
        'direction',
        'location'
    ]
} as const;

export const sMessagePersonal = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        locationId: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/MessageTypeEnum'
        },
        direction: {
            $ref: '#/components/schemas/MessageDirectionEnum'
        },
        location: {
            $ref: '#/components/schemas/Location'
        }
    },
    required: [
        'id',
        'name',
        'phone',
        'email',
        'locationId',
        'createdAt',
        'type',
        'direction',
        'location'
    ]
} as const;

export const sMessagePackage = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        link: {
            type: 'string',
            format: 'uri'
        },
        number: {
            type: [
                'string',
                'null'
            ]
        },
        createdAt: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/MessageTypeEnum'
        },
        direction: {
            $ref: '#/components/schemas/MessageDirectionEnum'
        }
    },
    required: [
        'id',
        'link',
        'number',
        'createdAt',
        'type',
        'direction'
    ]
} as const;

export const sMessageSystem = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        text: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/MessageTypeEnum'
        },
        direction: {
            $ref: '#/components/schemas/MessageDirectionEnum'
        }
    },
    required: [
        'id',
        'text',
        'createdAt',
        'type',
        'direction'
    ]
} as const;

export const sMessagePayload = {
    anyOf: [
        {
            $ref: '#/components/schemas/MessageText'
        },
        {
            $ref: '#/components/schemas/MessageGallery'
        },
        {
            $ref: '#/components/schemas/MessageLocation'
        },
        {
            $ref: '#/components/schemas/MessagePersonal'
        },
        {
            $ref: '#/components/schemas/MessagePackage'
        },
        {
            $ref: '#/components/schemas/MessageSystem'
        }
    ]
} as const;

export const sMessageItem = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/MessageTypeEnum'
        },
        payload: {
            $ref: '#/components/schemas/MessagePayload'
        }
    },
    required: [
        'id',
        'type',
        'payload'
    ]
} as const;

export const sMessageItemSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/MessageItem'
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sMessageFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        messageThreadId: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        transactionId: {
            type: 'string'
        }
    }
} as const;

export const sMessageWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        messageThreadId: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        transactionId: {
            type: 'string'
        }
    }
} as const;

export const sMessageSortField = {
    type: 'string',
    enum: [
        'id',
        'createdAt'
    ]
} as const;

export const sMessageSort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/MessageSortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sMessageQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/MessageFilter'
        },
        where: {
            $ref: '#/components/schemas/MessageWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/MessageSort'
            }
        }
    }
} as const;

export const sAllowedExtensionsEnum = {
    type: 'string',
    enum: [
        'webp',
        'png',
        'jpg',
        'jpeg',
        'avif',
        'heic',
        'heif'
    ]
} as const;

export const sAllowedContentTypesEnum = {
    type: 'string',
    enum: [
        'image/jpeg',
        'image/png',
        'image/webp',
        'image/avif',
        'image/heic',
        'image/heif'
    ]
} as const;

export const sTransactionMessageGalleryCreate = {
    type: 'object',
    properties: {
        transactionId: {
            type: 'string'
        },
        uploadIds: {
            type: 'array',
            items: {
                type: 'string'
            },
            minItems: 1
        }
    },
    required: [
        'transactionId',
        'uploadIds'
    ]
} as const;

export const sTransactionMessageLocationCreate = {
    type: 'object',
    properties: {
        transactionId: {
            type: 'string'
        },
        locationId: {
            type: 'string'
        }
    },
    required: [
        'transactionId',
        'locationId'
    ]
} as const;

export const sTransactionMessagePackageCreate = {
    type: 'object',
    properties: {
        transactionId: {
            type: 'string'
        },
        link: {
            type: 'string',
            format: 'uri'
        },
        number: {
            type: [
                'string',
                'null'
            ]
        }
    },
    required: [
        'transactionId',
        'link',
        'number'
    ]
} as const;

export const sTransactionMessagePersonalCreate = {
    type: 'object',
    properties: {
        transactionId: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        locationId: {
            type: 'string'
        }
    },
    required: [
        'transactionId',
        'name',
        'phone',
        'email',
        'locationId'
    ]
} as const;

export const sTransactionMessageTextCreate = {
    type: 'object',
    properties: {
        transactionId: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: [
        'transactionId',
        'message'
    ]
} as const;

export const sTransactionSideEnum = {
    type: 'string',
    enum: [
        'seller',
        'buyer',
        'transaction',
        'system',
        'unknown'
    ]
} as const;

export const sTransactionStatusEnum = {
    type: 'string',
    enum: [
        'pending',
        'open',
        'resolved',
        'dispute',
        'rejected',
        'expired',
        'success',
        'closed'
    ]
} as const;

export const sTransactionStatus = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        transactionId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        },
        side: {
            $ref: '#/components/schemas/TransactionSideEnum'
        },
        status: {
            $ref: '#/components/schemas/TransactionStatusEnum'
        },
        createdAt: {
            type: 'string'
        }
    },
    required: [
        'id',
        'transactionId',
        'listingId',
        'side',
        'status',
        'createdAt'
    ]
} as const;

export const sTransactionStatusReject = {
    type: 'object',
    properties: {
        transactionId: {
            type: 'string'
        }
    },
    required: [
        'transactionId'
    ]
} as const;

export const sTransactionStatusDispute = {
    type: 'object',
    properties: {
        transactionId: {
            type: 'string'
        }
    },
    required: [
        'transactionId'
    ]
} as const;

export const sUploadCreate = {
    type: 'object',
    properties: {
        url: {
            type: 'string',
            format: 'uri'
        }
    },
    required: [
        'url'
    ]
} as const;

export const sUserSideEnum = {
    type: 'string',
    enum: [
        'seller',
        'buyer'
    ]
} as const;

export const sUserEx = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        locationId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        side: {
            anyOf: [
                {
                    $ref: '#/components/schemas/UserSideEnum'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    required: [
        'id',
        'locationId'
    ]
} as const;

export const sUserExPatch = {
    type: 'object',
    properties: {
        patch: {
            type: 'object',
            properties: {
                locationId: {
                    anyOf: [
                        {
                            type: 'string'
                        },
                        {
                            type: 'null'
                        },
                        {
                            type: 'null'
                        }
                    ]
                },
                side: {
                    anyOf: [
                        {
                            $ref: '#/components/schemas/UserSideEnum'
                        },
                        {
                            type: 'null'
                        },
                        {
                            type: 'null'
                        }
                    ]
                }
            }
        }
    },
    required: [
        'patch'
    ]
} as const;
