// This file is auto-generated by @hey-api/openapi-ts

export const sUserExPatch = {
    type: 'object',
    properties: {
        patch: {
            type: 'object',
            properties: {
                locationId: {
                    anyOf: [
                        {
                            type: 'string'
                        },
                        {
                            type: 'null'
                        },
                        {
                            type: 'null'
                        }
                    ]
                },
                side: {
                    anyOf: [
                        {
                            $ref: '#/components/schemas/UserSideEnum'
                        },
                        {
                            type: 'null'
                        },
                        {
                            type: 'null'
                        }
                    ]
                }
            }
        }
    },
    required: [
        'patch'
    ]
} as const;

export const sUserSideEnum = {
    type: 'string',
    enum: [
        'seller',
        'buyer'
    ]
} as const;

export const sUserEx = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        locationId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        side: {
            anyOf: [
                {
                    $ref: '#/components/schemas/UserSideEnum'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    required: [
        'id',
        'locationId'
    ]
} as const;

export const sUploadCountQuery = {
    type: 'object',
    properties: {
        filter: {
            $ref: '#/components/schemas/UploadFilter'
        },
        where: {
            $ref: '#/components/schemas/UploadWhere'
        }
    }
} as const;

export const sUploadWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        }
    }
} as const;

export const sUploadFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        }
    }
} as const;

export const sUploadCollection = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Upload'
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sUpload = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        url: {
            type: 'string',
            format: 'uri'
        }
    },
    required: [
        'id',
        'url'
    ]
} as const;

export const sUploadQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/UploadFilter'
        },
        where: {
            $ref: '#/components/schemas/UploadWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/UploadSort'
            }
        }
    }
} as const;

export const sOrderEnum = {
    type: 'string',
    enum: [
        'asc',
        'desc'
    ]
} as const;

export const sUploadSortField = {
    type: 'string',
    enum: [
        'createdAt'
    ]
} as const;

export const sUploadSort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/UploadSortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sCursor = {
    type: 'object',
    properties: {
        page: {
            type: 'number',
            minimum: 0
        },
        size: {
            type: 'number',
            minimum: 1,
            maximum: 1000
        }
    },
    required: [
        'page',
        'size'
    ]
} as const;

export const sUploadCreate = {
    type: 'object',
    properties: {
        url: {
            type: 'string',
            format: 'uri'
        }
    },
    required: [
        'url'
    ]
} as const;

export const sTransactionStatusReject = {
    type: 'object',
    properties: {
        transactionId: {
            type: 'string'
        }
    },
    required: [
        'transactionId'
    ]
} as const;

export const sTransactionStatusAccept = {
    type: 'object',
    properties: {
        transactionId: {
            type: 'string'
        }
    },
    required: [
        'transactionId'
    ]
} as const;

export const sTransactionStatus = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        transactionId: {
            type: 'string'
        },
        side: {
            $ref: '#/components/schemas/TransactionSideEnum'
        },
        status: {
            allOf: [
                {
                    $ref: '#/components/schemas/TransactionStatusEnum'
                },
                {}
            ]
        }
    },
    required: [
        'id',
        'transactionId',
        'side',
        'status'
    ]
} as const;

export const sTransactionStatusEnum = {
    type: 'string',
    enum: [
        'request',
        'accepted',
        'rejected',
        'success',
        'closed',
        'expired'
    ]
} as const;

export const sTransactionSideEnum = {
    type: 'string',
    enum: [
        'seller',
        'buyer',
        'transaction',
        'system',
        'unknown'
    ]
} as const;

export const sTransactionBuyerInfo = {
    type: 'object',
    properties: {
        registered: {
            type: 'string'
        },
        score: {
            type: 'number',
            example: 0
        }
    },
    required: [
        'registered',
        'score'
    ]
} as const;

export const sTransactionSellerInfo = {
    type: 'object',
    properties: {
        registered: {
            type: 'string'
        },
        score: {
            type: 'number',
            example: 0
        }
    },
    required: [
        'registered',
        'score'
    ]
} as const;

export const sTransactionCreate = {
    type: 'object',
    properties: {
        listingId: {
            type: 'string'
        }
    },
    required: [
        'listingId'
    ]
} as const;

export const sTransaction = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        },
        messageThreadId: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        },
        expiresAt: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        status: {
            allOf: [
                {
                    $ref: '#/components/schemas/TransactionStatusEnum'
                },
                {}
            ]
        },
        gallery: {
            allOf: [
                {
                    $ref: '#/components/schemas/Gallery'
                },
                {}
            ]
        },
        price: {
            type: 'number'
        },
        priceType: {
            $ref: '#/components/schemas/ListingPriceEnum'
        },
        currency: {
            $ref: '#/components/schemas/CurrencyListEnum'
        },
        location: {
            $ref: '#/components/schemas/Location'
        }
    },
    required: [
        'id',
        'listingId',
        'messageThreadId',
        'createdAt',
        'updatedAt',
        'expiresAt',
        'title',
        'status',
        'gallery',
        'price',
        'priceType',
        'currency',
        'location'
    ]
} as const;

export const sLocation = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        query: {
            type: 'string'
        },
        lang: {
            type: 'string'
        },
        country: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        county: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        municipality: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        state: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        address: {
            type: 'string'
        },
        city: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        street: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        zip: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        confidence: {
            type: 'number'
        },
        hash: {
            type: 'string'
        },
        lat: {
            type: 'number'
        },
        lon: {
            type: 'number'
        }
    },
    required: [
        'id',
        'query',
        'lang',
        'country',
        'code',
        'county',
        'municipality',
        'state',
        'address',
        'city',
        'street',
        'zip',
        'confidence',
        'hash',
        'lat',
        'lon'
    ]
} as const;

export const sCurrencyListEnum = {
    type: 'string',
    enum: [
        'CZK',
        'EUR',
        'USD',
        'GBP',
        'PLN',
        'HUF',
        'CHF'
    ]
} as const;

export const sListingPriceEnum = {
    type: 'string',
    enum: [
        'closed',
        'open'
    ]
} as const;

export const sGalleryItem = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        galleryId: {
            type: 'string'
        },
        uploadId: {
            type: 'string'
        },
        sort: {
            type: 'number'
        },
        upload: {
            $ref: '#/components/schemas/Upload'
        }
    },
    required: [
        'id',
        'galleryId',
        'uploadId',
        'sort',
        'upload'
    ]
} as const;

export const sGallery = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/GalleryItem'
            }
        }
    },
    required: [
        'id',
        'items'
    ]
} as const;

export const sTransactionQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/TransactionFilter'
        },
        where: {
            $ref: '#/components/schemas/TransactionWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TransactionSort'
            }
        },
        meta: {
            $ref: '#/components/schemas/TransactionMeta'
        }
    }
} as const;

export const sTransactionMeta = {
    type: 'object',
    properties: {
        side: {
            $ref: '#/components/schemas/UserSideEnum'
        }
    }
} as const;

export const sTransactionSortField = {
    type: 'string',
    enum: [
        'createdAt',
        'updatedAt',
        'expiresAt',
        'status'
    ]
} as const;

export const sTransactionSort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/TransactionSortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sTransactionWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        },
        status: {
            $ref: '#/components/schemas/TransactionStatusEnum'
        },
        statusIn: {
            type: 'array',
            items: {
                allOf: [
                    {
                        $ref: '#/components/schemas/TransactionStatusEnum'
                    },
                    {}
                ]
            }
        }
    }
} as const;

export const sTransactionFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        },
        status: {
            $ref: '#/components/schemas/TransactionStatusEnum'
        },
        statusIn: {
            type: 'array',
            items: {
                allOf: [
                    {
                        $ref: '#/components/schemas/TransactionStatusEnum'
                    },
                    {}
                ]
            }
        }
    }
} as const;

export const sTransactionCollection = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        type: 'string',
                        minLength: 1
                    }
                },
                required: [
                    'id'
                ]
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sAllowedContentTypesEnum = {
    type: 'string',
    enum: [
        'image/jpeg',
        'image/png',
        'image/webp',
        'image/avif',
        'image/heic',
        'image/heif'
    ]
} as const;

export const sAllowedExtensionsEnum = {
    type: 'string',
    enum: [
        'webp',
        'png',
        'jpg',
        'jpeg',
        'avif',
        'heic',
        'heif'
    ]
} as const;

export const sMessageQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/MessageFilter'
        },
        where: {
            $ref: '#/components/schemas/MessageWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/MessageSort'
            }
        }
    }
} as const;

export const sMessageSortField = {
    type: 'string',
    enum: [
        'createdAt'
    ]
} as const;

export const sMessageSort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/MessageSortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sMessageWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        messageThreadId: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        transactionId: {
            type: 'string'
        }
    }
} as const;

export const sMessageFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        messageThreadId: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        transactionId: {
            type: 'string'
        }
    }
} as const;

export const sMessageCollection = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Message'
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sMessageSystem = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        text: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/MessageTypeEnum'
        },
        direction: {
            $ref: '#/components/schemas/MessageDirectionEnum'
        }
    },
    required: [
        'id',
        'text',
        'createdAt',
        'type',
        'direction'
    ]
} as const;

export const sMessageDirectionEnum = {
    type: 'string',
    enum: [
        'in',
        'out',
        'system'
    ]
} as const;

export const sMessageTypeEnum = {
    type: 'string',
    enum: [
        'text',
        'gallery',
        'location',
        'system'
    ]
} as const;

export const sMessageLocation = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        locationId: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/MessageTypeEnum'
        },
        direction: {
            $ref: '#/components/schemas/MessageDirectionEnum'
        }
    },
    required: [
        'id',
        'locationId',
        'type',
        'direction'
    ]
} as const;

export const sMessageGallery = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        galleryId: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/MessageTypeEnum'
        },
        direction: {
            $ref: '#/components/schemas/MessageDirectionEnum'
        }
    },
    required: [
        'id',
        'galleryId',
        'type',
        'direction'
    ]
} as const;

export const sMessageText = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        text: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/MessageTypeEnum'
        },
        direction: {
            $ref: '#/components/schemas/MessageDirectionEnum'
        }
    },
    required: [
        'id',
        'text',
        'createdAt',
        'type',
        'direction'
    ]
} as const;

export const sMessage = {
    anyOf: [
        {
            $ref: '#/components/schemas/MessageText'
        },
        {
            $ref: '#/components/schemas/MessageGallery'
        },
        {
            $ref: '#/components/schemas/MessageLocation'
        },
        {
            $ref: '#/components/schemas/MessageSystem'
        }
    ]
} as const;

export const sMessageTextCreate = {
    type: 'object',
    properties: {
        messageThreadId: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: [
        'messageThreadId',
        'message'
    ]
} as const;

export const sListingScoreCreate = {
    type: 'object',
    properties: {
        listingId: {
            type: 'string'
        },
        score: {
            $ref: '#/components/schemas/ListingScoreTypeEnum'
        }
    },
    required: [
        'listingId',
        'score'
    ]
} as const;

export const sListingScoreTypeEnum = {
    type: 'string',
    enum: [
        'listing',
        'ignore',
        'flag',
        'view',
        'favourite'
    ]
} as const;

export const sListingScoreCountQuery = {
    type: 'object',
    properties: {
        filter: {
            $ref: '#/components/schemas/ListingScoreFilter'
        },
        where: {
            $ref: '#/components/schemas/ListingScoreWhere'
        }
    }
} as const;

export const sListingScoreWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        }
    }
} as const;

export const sListingScoreFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        }
    }
} as const;

export const sListingScoreQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/ListingScoreFilter'
        },
        where: {
            $ref: '#/components/schemas/ListingScoreWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ListingScoreSort'
            }
        }
    }
} as const;

export const sListingScoreSortField = {
    type: 'string',
    enum: [
        'score',
        'createdAt'
    ]
} as const;

export const sListingScoreSort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/ListingScoreSortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sListingScoreCollection = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ListingScore'
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sListingScore = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/ListingScoreTypeEnum'
        },
        score: {
            type: 'integer'
        },
        createdAt: {
            type: 'string'
        }
    },
    required: [
        'id',
        'listingId',
        'type',
        'score',
        'createdAt'
    ]
} as const;

export const sListingMetrics = {
    type: 'object',
    properties: {
        listing: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        listingScore: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        views: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        viewsScore: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        favourite: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        favouriteScore: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        ignore: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        ignoreScore: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        flag: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        flagScore: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        score: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    required: [
        'listing',
        'listingScore',
        'views',
        'viewsScore',
        'favourite',
        'favouriteScore',
        'ignore',
        'ignoreScore',
        'flag',
        'flagScore',
        'score'
    ]
} as const;

export const sListingCountQuery = {
    type: 'object',
    properties: {
        filter: {
            $ref: '#/components/schemas/ListingFilter'
        },
        where: {
            $ref: '#/components/schemas/ListingWhere'
        },
        meta: {
            $ref: '#/components/schemas/ListingMeta'
        }
    }
} as const;

export const sLatLon = {
    type: 'object',
    properties: {
        lat: {
            type: 'number',
            minimum: -90,
            maximum: 90
        },
        lon: {
            type: 'number',
            minimum: -180,
            maximum: 180
        }
    },
    required: [
        'lat',
        'lon'
    ]
} as const;

export const sListingMeta = {
    type: 'object',
    properties: {
        latLon: {
            $ref: '#/components/schemas/LatLon'
        },
        feedId: {
            allOf: [
                {
                    $ref: '#/components/schemas/FeedId'
                },
                {}
            ]
        }
    }
} as const;

export const sFeedId = {
    type: 'string',
    minLength: 1
} as const;

export const sListingWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        priceMin: {
            $ref: '#/components/schemas/PriceMin'
        },
        priceMax: {
            $ref: '#/components/schemas/PriceMax'
        },
        conditionMin: {
            type: 'number',
            minimum: 0,
            maximum: 6
        },
        conditionMax: {
            type: 'number',
            minimum: 0,
            maximum: 6
        },
        conditionIn: {
            type: 'array',
            items: {
                type: 'number',
                minimum: 0,
                maximum: 6
            }
        },
        ageMin: {
            type: 'number',
            minimum: 0,
            maximum: 6
        },
        ageMax: {
            type: 'number',
            minimum: 0,
            maximum: 6
        },
        ageIn: {
            type: 'array',
            items: {
                type: 'number',
                minimum: 0,
                maximum: 6
            }
        },
        categoryId: {
            $ref: '#/components/schemas/CategoryId'
        },
        categoryIdIn: {
            $ref: '#/components/schemas/CategoryIdIn'
        },
        currency: {
            $ref: '#/components/schemas/CurrencyListEnum'
        },
        currencyIn: {
            $ref: '#/components/schemas/CurrencyIn'
        },
        expiresAtBefore: {
            type: 'string'
        },
        expiresAtAfter: {
            type: 'string'
        },
        range: {
            type: 'number',
            minimum: 0
        },
        title: {
            type: 'string'
        },
        withOwn: {
            type: 'boolean'
        },
        my: {
            type: 'boolean'
        },
        withIgnored: {
            type: 'boolean'
        },
        isFavourite: {
            type: 'boolean'
        },
        feedId: {
            $ref: '#/components/schemas/FeedId'
        },
        feedIdIn: {
            $ref: '#/components/schemas/FeedIdIn'
        },
        transaction: {
            type: 'boolean'
        }
    }
} as const;

export const sFeedIdIn = {
    type: 'array',
    items: {
        type: 'string',
        minLength: 1
    }
} as const;

export const sCurrencyIn = {
    type: 'array',
    items: {
        $ref: '#/components/schemas/CurrencyListEnum'
    }
} as const;

export const sCategoryIdIn = {
    type: 'array',
    items: {
        type: 'string',
        minLength: 1
    }
} as const;

export const sCategoryId = {
    type: 'string',
    minLength: 1
} as const;

export const sPriceMax = {
    type: 'number',
    minimum: 0
} as const;

export const sPriceMin = {
    type: 'number',
    minimum: 0
} as const;

export const sListingFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        priceMin: {
            $ref: '#/components/schemas/PriceMin'
        },
        priceMax: {
            $ref: '#/components/schemas/PriceMax'
        },
        conditionMin: {
            type: 'number',
            minimum: 0,
            maximum: 6
        },
        conditionMax: {
            type: 'number',
            minimum: 0,
            maximum: 6
        },
        conditionIn: {
            type: 'array',
            items: {
                type: 'number',
                minimum: 0,
                maximum: 6
            }
        },
        ageMin: {
            type: 'number',
            minimum: 0,
            maximum: 6
        },
        ageMax: {
            type: 'number',
            minimum: 0,
            maximum: 6
        },
        ageIn: {
            type: 'array',
            items: {
                type: 'number',
                minimum: 0,
                maximum: 6
            }
        },
        categoryId: {
            $ref: '#/components/schemas/CategoryId'
        },
        categoryIdIn: {
            $ref: '#/components/schemas/CategoryIdIn'
        },
        currency: {
            $ref: '#/components/schemas/CurrencyListEnum'
        },
        currencyIn: {
            $ref: '#/components/schemas/CurrencyIn'
        },
        expiresAtBefore: {
            type: 'string'
        },
        expiresAtAfter: {
            type: 'string'
        },
        range: {
            type: 'number',
            minimum: 0
        },
        title: {
            type: 'string'
        },
        withOwn: {
            type: 'boolean'
        },
        my: {
            type: 'boolean'
        },
        withIgnored: {
            type: 'boolean'
        },
        isFavourite: {
            type: 'boolean'
        },
        feedId: {
            $ref: '#/components/schemas/FeedId'
        },
        feedIdIn: {
            $ref: '#/components/schemas/FeedIdIn'
        },
        transaction: {
            type: 'boolean'
        }
    }
} as const;

export const sListingCollection = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        type: 'string',
                        minLength: 1
                    }
                },
                required: [
                    'id'
                ]
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sListingCreate = {
    type: 'object',
    properties: {
        price: {
            type: 'number'
        },
        priceType: {
            $ref: '#/components/schemas/ListingPriceEnum'
        },
        condition: {
            type: 'number'
        },
        age: {
            type: 'number'
        },
        draftId: {
            type: 'string'
        },
        locationId: {
            type: 'string'
        },
        categoryId: {
            type: 'string'
        },
        expiresAt: {
            $ref: '#/components/schemas/ListingExpireEnum'
        },
        title: {
            type: 'string',
            minLength: 5,
            maxLength: 72
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        uploadIds: {
            type: 'array',
            items: {
                type: 'string'
            },
            minItems: 1
        }
    },
    required: [
        'price',
        'priceType',
        'condition',
        'age',
        'locationId',
        'categoryId',
        'expiresAt',
        'title',
        'uploadIds'
    ]
} as const;

export const sListingExpireEnum = {
    type: 'string',
    enum: [
        '7-days',
        '14-days',
        '1-month'
    ]
} as const;

export const sIgnoreToggle = {
    type: 'object',
    properties: {
        toggle: {
            type: 'boolean'
        },
        listingId: {
            type: 'string'
        }
    },
    required: [
        'toggle',
        'listingId'
    ]
} as const;

export const sIgnoreCountQuery = {
    type: 'object',
    properties: {
        filter: {
            $ref: '#/components/schemas/IgnoreFilter'
        },
        where: {
            $ref: '#/components/schemas/IgnoreWhere'
        }
    }
} as const;

export const sIgnoreWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        }
    }
} as const;

export const sIgnoreFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        }
    }
} as const;

export const sIgnoreQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/IgnoreFilter'
        },
        where: {
            $ref: '#/components/schemas/IgnoreWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/IgnoreSort'
            }
        }
    }
} as const;

export const sIgnoreSortField = {
    type: 'string',
    enum: [
        'createdAt'
    ]
} as const;

export const sIgnoreSort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/IgnoreSortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sIgnoreCollection = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Ignore'
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sIgnore = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        }
    },
    required: [
        'id',
        'listingId'
    ]
} as const;

export const sGalleryCountQuery = {
    type: 'object',
    properties: {
        filter: {
            $ref: '#/components/schemas/GalleryFilter'
        },
        where: {
            $ref: '#/components/schemas/GalleryWhere'
        }
    }
} as const;

export const sGalleryWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        }
    }
} as const;

export const sGalleryFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        }
    }
} as const;

export const sGalleryCollection = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                allOf: [
                    {
                        $ref: '#/components/schemas/Gallery'
                    },
                    {}
                ]
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sGalleryQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/GalleryFilter'
        },
        where: {
            $ref: '#/components/schemas/GalleryWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/GallerySort'
            }
        }
    }
} as const;

export const sGallerySortField = {
    type: 'string',
    enum: [
        'createdAt'
    ]
} as const;

export const sGallerySort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/GallerySortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sFlagToggle = {
    type: 'object',
    properties: {
        toggle: {
            type: 'boolean'
        },
        listingId: {
            type: 'string'
        }
    },
    required: [
        'toggle',
        'listingId'
    ]
} as const;

export const sFlagCountQuery = {
    type: 'object',
    properties: {
        filter: {
            $ref: '#/components/schemas/FlagFilter'
        },
        where: {
            $ref: '#/components/schemas/FlagCountWhere'
        }
    }
} as const;

export const sFlagCountWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        }
    }
} as const;

export const sFlagFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        }
    }
} as const;

export const sFlagQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/FlagFilter'
        },
        where: {
            $ref: '#/components/schemas/FlagWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/FlagSort'
            }
        }
    }
} as const;

export const sFlagSortField = {
    type: 'string',
    enum: [
        'createdAt'
    ]
} as const;

export const sFlagSort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/FlagSortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sFlagWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        }
    }
} as const;

export const sFlagCollection = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Flag'
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sFlag = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        }
    },
    required: [
        'id',
        'listingId'
    ]
} as const;

export const sFeedFavouriteCollection = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/FeedFavourite'
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sListingSortField = {
    type: 'string',
    enum: [
        'price',
        'condition',
        'age',
        'createdAt',
        'updatedAt',
        'expiresAt',
        'geo'
    ]
} as const;

export const sListingSort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/ListingSortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sListingQuery = {
    type: 'object',
    properties: {
        cursor: {
            allOf: [
                {
                    $ref: '#/components/schemas/Cursor'
                },
                {
                    default: {
                        page: 0,
                        size: 256
                    }
                }
            ]
        },
        filter: {
            $ref: '#/components/schemas/ListingFilter'
        },
        where: {
            $ref: '#/components/schemas/ListingWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ListingSort'
            }
        },
        meta: {
            $ref: '#/components/schemas/ListingMeta'
        }
    }
} as const;

export const sFeedFavourite = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        locationId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        uploadId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        name: {
            type: 'string'
        },
        query: {
            $ref: '#/components/schemas/ListingQuery'
        },
        upload: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Upload'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        count: {
            type: 'number'
        }
    },
    required: [
        'id',
        'locationId',
        'uploadId',
        'name',
        'query',
        'upload',
        'count'
    ]
} as const;

export const sFeedGalleryCreate = {
    type: 'object',
    properties: {
        feedId: {
            type: 'string'
        },
        uploadIds: {
            type: 'array',
            items: {
                type: 'string'
            },
            minItems: 1
        }
    },
    required: [
        'feedId',
        'uploadIds'
    ]
} as const;

export const sFeedCountQuery = {
    type: 'object',
    properties: {
        filter: {
            $ref: '#/components/schemas/FeedFilter'
        },
        where: {
            $ref: '#/components/schemas/FeedWhere'
        }
    }
} as const;

export const sFeedWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        }
    }
} as const;

export const sFeedFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        }
    }
} as const;

export const sFeedCollection = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        type: 'string',
                        minLength: 1
                    }
                },
                required: [
                    'id'
                ]
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sFeedPatch = {
    type: 'object',
    properties: {
        patch: {
            type: 'object',
            properties: {
                id: {
                    type: 'string'
                },
                locationId: {
                    anyOf: [
                        {
                            type: 'string'
                        },
                        {
                            type: 'null'
                        },
                        {
                            type: 'null'
                        }
                    ]
                },
                uploadId: {
                    anyOf: [
                        {
                            type: 'string'
                        },
                        {
                            type: 'null'
                        },
                        {
                            type: 'null'
                        }
                    ]
                },
                name: {
                    type: 'string'
                },
                query: {
                    $ref: '#/components/schemas/ListingQuery'
                }
            }
        },
        query: {
            $ref: '#/components/schemas/FeedQuery'
        }
    },
    required: [
        'patch',
        'query'
    ]
} as const;

export const sFeedSortField = {
    type: 'string',
    enum: [
        'createdAt',
        'updatedAt'
    ]
} as const;

export const sFeedSort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/FeedSortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sFeedQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/FeedFilter'
        },
        where: {
            $ref: '#/components/schemas/FeedWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/FeedSort'
            }
        }
    }
} as const;

export const sFeedCreate = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1
        },
        locationId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        query: {
            $ref: '#/components/schemas/ListingQuery'
        }
    },
    required: [
        'name',
        'query'
    ]
} as const;

export const sFeed = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        locationId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        uploadId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        name: {
            type: 'string'
        },
        query: {
            $ref: '#/components/schemas/ListingQuery'
        },
        upload: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Upload'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    required: [
        'id',
        'locationId',
        'uploadId',
        'name',
        'query',
        'upload'
    ]
} as const;

export const sFavouriteToggle = {
    type: 'object',
    properties: {
        toggle: {
            type: 'boolean'
        },
        feedId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        }
    },
    required: [
        'toggle',
        'feedId',
        'listingId'
    ]
} as const;

export const sListing = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        price: {
            type: 'number'
        },
        priceType: {
            $ref: '#/components/schemas/ListingPriceEnum'
        },
        currency: {
            $ref: '#/components/schemas/CurrencyListEnum'
        },
        condition: {
            type: 'number'
        },
        age: {
            type: 'number'
        },
        locationId: {
            type: 'string'
        },
        categoryId: {
            type: 'string'
        },
        galleryId: {
            type: 'string'
        },
        draftId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        expiresAt: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        createdAt: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        },
        location: {
            $ref: '#/components/schemas/Location'
        },
        category: {
            $ref: '#/components/schemas/Category'
        },
        distance: {
            type: [
                'number',
                'null'
            ]
        },
        gallery: {
            allOf: [
                {
                    $ref: '#/components/schemas/Gallery'
                },
                {}
            ]
        },
        isFavourite: {
            type: 'boolean'
        },
        isIgnored: {
            type: 'boolean'
        },
        hasFlag: {
            type: 'boolean'
        },
        transactionId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    required: [
        'id',
        'price',
        'priceType',
        'currency',
        'condition',
        'age',
        'locationId',
        'categoryId',
        'galleryId',
        'draftId',
        'expiresAt',
        'title',
        'description',
        'createdAt',
        'updatedAt',
        'location',
        'category',
        'distance',
        'gallery',
        'isFavourite',
        'isIgnored',
        'hasFlag',
        'transactionId'
    ]
} as const;

export const sCategory = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        group: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        slug: {
            type: 'string'
        },
        sort: {
            type: 'number'
        },
        locale: {
            type: 'string'
        }
    },
    required: [
        'id',
        'group',
        'category',
        'slug',
        'sort',
        'locale'
    ]
} as const;

export const sFavouriteCountQuery = {
    type: 'object',
    properties: {
        filter: {
            $ref: '#/components/schemas/FavouriteFilter'
        },
        where: {
            $ref: '#/components/schemas/FavouriteWhere'
        }
    }
} as const;

export const sFavouriteWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        }
    }
} as const;

export const sFavouriteFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        }
    }
} as const;

export const sFavouriteQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/FavouriteFilter'
        },
        where: {
            $ref: '#/components/schemas/FavouriteWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/FavouriteSort'
            }
        }
    }
} as const;

export const sFavouriteSortField = {
    type: 'string',
    enum: [
        'createdAt'
    ]
} as const;

export const sFavouriteSort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/FavouriteSortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sFavouriteCollection = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Favourite'
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sFavourite = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        feedId: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        }
    },
    required: [
        'id',
        'feedId',
        'listingId',
        'createdAt'
    ]
} as const;

export const sDraftPatch = {
    type: 'object',
    properties: {
        patch: {
            $ref: '#/components/schemas/DraftPatchData'
        },
        query: {
            $ref: '#/components/schemas/DraftQuery'
        }
    },
    required: [
        'patch',
        'query'
    ]
} as const;

export const sDraftSortField = {
    type: 'string',
    enum: [
        'createdAt',
        'updatedAt'
    ]
} as const;

export const sDraftSort = {
    type: 'object',
    properties: {
        field: {
            $ref: '#/components/schemas/DraftSortField'
        },
        direction: {
            $ref: '#/components/schemas/OrderEnum'
        }
    },
    required: [
        'field',
        'direction'
    ]
} as const;

export const sDraftWhere = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        updatedAtGte: {
            type: 'string'
        },
        updatedAtLte: {
            type: 'string'
        },
        usedAtIsNull: {
            type: 'boolean'
        }
    }
} as const;

export const sDraftFilter = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        idIn: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        fulltext: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        updatedAtGte: {
            type: 'string'
        },
        updatedAtLte: {
            type: 'string'
        },
        usedAtIsNull: {
            type: 'boolean'
        }
    }
} as const;

export const sDraftQuery = {
    type: 'object',
    properties: {
        cursor: {
            $ref: '#/components/schemas/Cursor'
        },
        filter: {
            $ref: '#/components/schemas/DraftFilter'
        },
        where: {
            $ref: '#/components/schemas/DraftWhere'
        },
        sort: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/DraftSort'
            }
        }
    }
} as const;

export const sDraftPatchData = {
    type: 'object',
    properties: {
        price: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        priceType: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ListingPriceEnum'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        condition: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        age: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        locationId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        categoryId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        galleryId: {
            type: 'string'
        },
        expiresAt: {
            anyOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/ListingExpireEnum'
                },
                {
                    type: 'null'
                }
            ]
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        usedAt: {
            anyOf: [
                {
                    type: 'null'
                },
                {
                    type: [
                        'string',
                        'null'
                    ],
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const sDraftGalleryCreate = {
    type: 'object',
    properties: {
        draftId: {
            type: 'string'
        },
        uploadIds: {
            type: 'array',
            items: {
                type: 'string'
            },
            minItems: 1
        }
    },
    required: [
        'draftId',
        'uploadIds'
    ]
} as const;

export const sDraftCreate = {
    type: 'object',
    properties: {
        price: {
            type: 'number'
        },
        priceType: {
            allOf: [
                {
                    $ref: '#/components/schemas/ListingPriceEnum'
                },
                {}
            ]
        },
        condition: {
            type: 'number'
        },
        age: {
            type: 'number'
        },
        locationId: {
            type: 'string'
        },
        categoryId: {
            type: 'string'
        },
        expiresAt: {
            $ref: '#/components/schemas/ListingExpireEnum'
        },
        title: {
            type: 'string',
            minLength: 5,
            maxLength: 72
        },
        description: {
            type: 'string',
            maxLength: 2048
        },
        uploadIds: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const sDraft = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        price: {
            anyOf: [
                {
                    type: [
                        'number',
                        'null'
                    ]
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        priceType: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ListingPriceEnum'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        currency: {
            anyOf: [
                {
                    $ref: '#/components/schemas/CurrencyListEnum'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        condition: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        age: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        locationId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        categoryId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        galleryId: {
            type: 'string'
        },
        expiresAt: {
            anyOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/ListingExpireEnum'
                },
                {
                    type: 'null'
                }
            ]
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        createdAt: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        },
        usedAt: {
            anyOf: [
                {
                    type: 'null'
                },
                {
                    type: [
                        'string',
                        'null'
                    ],
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ]
        },
        location: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Location'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        category: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Category'
                },
                {
                    type: 'null'
                },
                {
                    type: 'null'
                }
            ]
        },
        gallery: {
            $ref: '#/components/schemas/Gallery'
        }
    },
    required: [
        'id',
        'price',
        'priceType',
        'currency',
        'condition',
        'age',
        'locationId',
        'categoryId',
        'galleryId',
        'expiresAt',
        'title',
        'description',
        'createdAt',
        'updatedAt',
        'usedAt',
        'location',
        'category',
        'gallery'
    ]
} as const;

export const sDraftCountQuery = {
    type: 'object',
    properties: {
        filter: {
            $ref: '#/components/schemas/DraftFilter'
        },
        where: {
            $ref: '#/components/schemas/DraftWhere'
        }
    }
} as const;

export const sDraftCollection = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        type: 'string',
                        minLength: 1
                    }
                },
                required: [
                    'id'
                ]
            }
        },
        more: {
            type: 'boolean'
        }
    },
    required: [
        'data',
        'more'
    ]
} as const;

export const sCount = {
    type: 'object',
    properties: {
        where: {
            type: 'number'
        },
        filter: {
            type: 'number'
        },
        total: {
            type: 'number'
        }
    },
    required: [
        'where',
        'filter',
        'total'
    ]
} as const;

export const sNotice = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/NoticeTypeEnum'
        }
    },
    required: [
        'message',
        'type'
    ]
} as const;

export const sNoticeTypeEnum = {
    type: 'string',
    enum: [
        'info',
        'warning',
        'error'
    ]
} as const;
