// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { apiGalleryCollectionErrors, apiGalleryCountErrors, apiGalleryFetchErrors, apiS3PresignErrors, apiTransactionEntryCollectionErrors, apiTransactionEntryCountErrors, apiTransactionEntryCreateErrors, apiTransactionEntryFetchErrors, apiTransactionEntryGalleryFetchErrors, apiUploadCreateErrors, apiUploadFetchErrors, tApiGalleryCollectionRequest, tApiGalleryCollectionResponse, tApiGalleryCountRequest, tApiGalleryCountResponse, tApiGalleryFetchRequest, tApiGalleryFetchResponse, tApiS3PresignRequest, tApiS3PresignResponse, tApiTransactionEntryCollectionRequest, tApiTransactionEntryCollectionResponse, tApiTransactionEntryCountRequest, tApiTransactionEntryCountResponse, tApiTransactionEntryCreateRequest, tApiTransactionEntryCreateResponse, tApiTransactionEntryFetchRequest, tApiTransactionEntryFetchResponse, tApiTransactionEntryGalleryFetchRequest, tApiTransactionEntryGalleryFetchResponse, tApiUploadCreateRequest, tApiUploadCreateResponse, tApiUploadFetchRequest, tApiUploadFetchResponse } from './types.gen';
import { zApiGalleryCollectionData, zApiGalleryCollectionResponse, zApiGalleryCountData, zApiGalleryCountResponse, zApiGalleryFetchData, zApiGalleryFetchResponse, zApiS3PresignData, zApiS3PresignResponse, zApiTransactionEntryCollectionData, zApiTransactionEntryCollectionResponse, zApiTransactionEntryCountData, zApiTransactionEntryCountResponse, zApiTransactionEntryCreateData, zApiTransactionEntryCreateResponse, zApiTransactionEntryFetchData, zApiTransactionEntryFetchResponse, zApiTransactionEntryGalleryFetchData, zApiTransactionEntryGalleryFetchResponse, zApiUploadCreateData, zApiUploadCreateResponse, zApiUploadFetchData, zApiUploadFetchResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Fetch a gallery based on the provided query
 *
 * Return a gallery based on the provided query
 */
export const apiGalleryFetch = <ThrowOnError extends boolean = false>(options?: Options<tApiGalleryFetchRequest, ThrowOnError>) => (options?.client ?? client).post<tApiGalleryFetchResponse, apiGalleryFetchErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiGalleryFetchData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiGalleryFetchResponse.parseAsync(data),
    url: '/api/user/gallery/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Fetch a collection of galleries based on the provided query
 *
 * Returns galleries based on provided parameters
 */
export const apiGalleryCollection = <ThrowOnError extends boolean = false>(options?: Options<tApiGalleryCollectionRequest, ThrowOnError>) => (options?.client ?? client).post<tApiGalleryCollectionResponse, apiGalleryCollectionErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiGalleryCollectionData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiGalleryCollectionResponse.parseAsync(data),
    url: '/api/user/gallery/collection',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Count galleries based on the provided query
 *
 * Returns count of galleries based on provided query
 */
export const apiGalleryCount = <ThrowOnError extends boolean = false>(options?: Options<tApiGalleryCountRequest, ThrowOnError>) => (options?.client ?? client).post<tApiGalleryCountResponse, apiGalleryCountErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiGalleryCountData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiGalleryCountResponse.parseAsync(data),
    url: '/api/user/gallery/count',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Generate a pre-signed URL for direct S3-compatible PUT upload
 *
 * Generate a pre-signed URL for direct S3-compatible PUT upload (private bucket). Expiration is server-controlled. A random suffix is always added.
 */
export const apiS3Presign = <ThrowOnError extends boolean = false>(options: Options<tApiS3PresignRequest, ThrowOnError>) => (options.client ?? client).post<tApiS3PresignResponse, apiS3PresignErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiS3PresignData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiS3PresignResponse.parseAsync(data),
    url: '/api/user/s3/pre-sign',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fetch a transaction entry collection
 *
 * Returns transaction entries based on the provided query
 */
export const apiTransactionEntryCollection = <ThrowOnError extends boolean = false>(options?: Options<tApiTransactionEntryCollectionRequest, ThrowOnError>) => (options?.client ?? client).post<tApiTransactionEntryCollectionResponse, apiTransactionEntryCollectionErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiTransactionEntryCollectionData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiTransactionEntryCollectionResponse.parseAsync(data),
    url: '/api/user/transaction-entry/collection',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Count transaction entries
 *
 * Returns count of transaction entries for the provided query
 */
export const apiTransactionEntryCount = <ThrowOnError extends boolean = false>(options?: Options<tApiTransactionEntryCountRequest, ThrowOnError>) => (options?.client ?? client).post<tApiTransactionEntryCountResponse, apiTransactionEntryCountErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiTransactionEntryCountData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiTransactionEntryCountResponse.parseAsync(data),
    url: '/api/user/transaction-entry/count',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Create one transaction entry
 *
 * Appends one user-authored transaction entry
 */
export const apiTransactionEntryCreate = <ThrowOnError extends boolean = false>(options?: Options<tApiTransactionEntryCreateRequest, ThrowOnError>) => (options?.client ?? client).post<tApiTransactionEntryCreateResponse, apiTransactionEntryCreateErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiTransactionEntryCreateData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiTransactionEntryCreateResponse.parseAsync(data),
    url: '/api/user/transaction-entry/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Fetch one transaction entry
 *
 * Returns one transaction entry based on the provided query
 */
export const apiTransactionEntryFetch = <ThrowOnError extends boolean = false>(options?: Options<tApiTransactionEntryFetchRequest, ThrowOnError>) => (options?.client ?? client).post<tApiTransactionEntryFetchResponse, apiTransactionEntryFetchErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiTransactionEntryFetchData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiTransactionEntryFetchResponse.parseAsync(data),
    url: '/api/user/transaction-entry/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Fetch gallery for one transaction entry
 *
 * Returns a gallery linked to a transaction entry when the current user is a participant of the transaction
 */
export const apiTransactionEntryGalleryFetch = <ThrowOnError extends boolean = false>(options?: Options<tApiTransactionEntryGalleryFetchRequest, ThrowOnError>) => (options?.client ?? client).post<tApiTransactionEntryGalleryFetchResponse, apiTransactionEntryGalleryFetchErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiTransactionEntryGalleryFetchData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiTransactionEntryGalleryFetchResponse.parseAsync(data),
    url: '/api/user/transaction-entry/gallery/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Create a new upload
 *
 * Create a new upload
 */
export const apiUploadCreate = <ThrowOnError extends boolean = false>(options?: Options<tApiUploadCreateRequest, ThrowOnError>) => (options?.client ?? client).post<tApiUploadCreateResponse, apiUploadCreateErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiUploadCreateData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiUploadCreateResponse.parseAsync(data),
    url: '/api/user/upload/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Fetch an upload item based on the provided query
 *
 * Return an upload item based on the provided query
 */
export const apiUploadFetch = <ThrowOnError extends boolean = false>(options?: Options<tApiUploadFetchRequest, ThrowOnError>) => (options?.client ?? client).post<tApiUploadFetchResponse, apiUploadFetchErrors, ThrowOnError>({
    requestValidator: async (data) => await zApiUploadFetchData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zApiUploadFetchResponse.parseAsync(data),
    url: '/api/user/upload/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
