/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './@routes/__root'
import { Route as LocaleRouteImport } from './@routes/$locale'
import { Route as IndexRouteImport } from './@routes/index'
import { Route as LocaleIndexRouteImport } from './@routes/$locale/index'
import { Route as CsTosRouteImport } from './@routes/cs/tos'
import { Route as LocaleTosRouteImport } from './@routes/$locale/tos'
import { Route as LocaleRegisterRouteImport } from './@routes/$locale/register'
import { Route as LocalePrivacyRouteImport } from './@routes/$locale/privacy'
import { Route as LocaleLoginRouteImport } from './@routes/$locale/login'
import { Route as LocaleLandingRouteImport } from './@routes/$locale/landing'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const CsTosRoute = CsTosRouteImport.update({
  id: '/cs/tos',
  path: '/cs/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTosRoute = LocaleTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRegisterRoute = LocaleRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLandingRoute = LocaleLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/landing': typeof LocaleLandingRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/tos': typeof LocaleTosRoute
  '/cs/tos': typeof CsTosRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/landing': typeof LocaleLandingRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/tos': typeof LocaleTosRoute
  '/cs/tos': typeof CsTosRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/landing': typeof LocaleLandingRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/tos': typeof LocaleTosRoute
  '/cs/tos': typeof CsTosRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/landing'
    | '/$locale/login'
    | '/$locale/privacy'
    | '/$locale/register'
    | '/$locale/tos'
    | '/cs/tos'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/landing'
    | '/$locale/login'
    | '/$locale/privacy'
    | '/$locale/register'
    | '/$locale/tos'
    | '/cs/tos'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/landing'
    | '/$locale/login'
    | '/$locale/privacy'
    | '/$locale/register'
    | '/$locale/tos'
    | '/cs/tos'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  CsTosRoute: typeof CsTosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/cs/tos': {
      id: '/cs/tos'
      path: '/cs/tos'
      fullPath: '/cs/tos'
      preLoaderRoute: typeof CsTosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/tos': {
      id: '/$locale/tos'
      path: '/tos'
      fullPath: '/$locale/tos'
      preLoaderRoute: typeof LocaleTosRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/register': {
      id: '/$locale/register'
      path: '/register'
      fullPath: '/$locale/register'
      preLoaderRoute: typeof LocaleRegisterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/landing': {
      id: '/$locale/landing'
      path: '/landing'
      fullPath: '/$locale/landing'
      preLoaderRoute: typeof LocaleLandingRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleLandingRoute: typeof LocaleLandingRoute
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleRegisterRoute: typeof LocaleRegisterRoute
  LocaleTosRoute: typeof LocaleTosRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleLandingRoute: LocaleLandingRoute,
  LocaleLoginRoute: LocaleLoginRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleRegisterRoute: LocaleRegisterRoute,
  LocaleTosRoute: LocaleTosRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  CsTosRoute: CsTosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
