// This file is auto-generated by @hey-api/openapi-ts

export type clientOptions = {
	baseUrl: "http://obsidian-ii.local:3032" | (string & {});
};

export type tHealth = {
	status: boolean;
};

export type tApiHealthRequest = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/public/health";
};

export type tApiHealthResponse = {
	/**
	 * Just health check
	 */
	200: tHealth;
};

export type apiHealthResponse = tApiHealthResponse[keyof tApiHealthResponse];
