// This file is auto-generated by @hey-api/openapi-ts

export const sListingEventEnum = {
    type: 'string',
    enum: [
        'impression',
        'view',
        'ignore',
        'unignore',
        'flag',
        'unflag',
        'transaction',
        'favourite',
        'unfavourite',
        'like',
        'dislike'
    ]
} as const;

export const sListingEvent = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        listingId: {
            type: 'string'
        },
        event: {
            $ref: '#/components/schemas/ListingEventEnum'
        },
        createdAt: {
            type: 'string'
        }
    },
    required: [
        'id',
        'listingId',
        'event',
        'createdAt'
    ]
} as const;

export const sNoticeTypeEnum = {
    type: 'string',
    enum: [
        'info',
        'warning',
        'error'
    ]
} as const;

export const sNotice = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/NoticeTypeEnum'
        }
    },
    required: [
        'message',
        'type'
    ]
} as const;

export const sListingEventCreate = {
    type: 'object',
    properties: {
        listingId: {
            type: 'string'
        },
        event: {
            $ref: '#/components/schemas/ListingEventEnum'
        }
    },
    required: [
        'listingId',
        'event'
    ]
} as const;
