/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './@routes/__root'
import { Route as McpRouteImport } from './@routes/mcp'
import { Route as ApiRouteImport } from './@routes/api'
import { Route as DotwellKnownRouteImport } from './@routes/[.]well-known'
import { Route as LocaleRouteImport } from './@routes/$locale'
import { Route as IndexRouteImport } from './@routes/index'
import { Route as LocaleIndexRouteImport } from './@routes/$locale/index'
import { Route as RedirectSignInRouteImport } from './@routes/redirect/sign-in'
import { Route as RedirectOathRouteImport } from './@routes/redirect/oath'
import { Route as ApiHealthRouteImport } from './@routes/api/health'
import { Route as ApiE2eRouteImport } from './@routes/api/e2e'
import { Route as ApiAssistantRouteImport } from './@routes/api/assistant'
import { Route as ApiCronRouteImport } from './@routes/api/$cron'
import { Route as LocaleTosRouteImport } from './@routes/$locale/tos'
import { Route as LocaleSignUpRouteImport } from './@routes/$locale/sign-up'
import { Route as LocaleSignInRouteImport } from './@routes/$locale/sign-in'
import { Route as LocalePrivacyRouteImport } from './@routes/$locale/privacy'
import { Route as LocaleOathRouteImport } from './@routes/$locale/oath'
import { Route as LocaleLandingRouteImport } from './@routes/$locale/landing'
import { Route as LocaleAppRouteImport } from './@routes/$locale/app'
import { Route as LocaleAppIndexRouteImport } from './@routes/$locale/app/index'
import { Route as ApiOauthAuthorizeRouteImport } from './@routes/api/oauth/authorize'
import { Route as ApiAuthSplatRouteImport } from './@routes/api/auth/$'
import { Route as LocaleAppWelcomeRouteImport } from './@routes/$locale/app/welcome'
import { Route as LocaleAppUserRouteImport } from './@routes/$locale/app/user'
import { Route as LocaleAppShopRouteImport } from './@routes/$locale/app/shop'
import { Route as LocaleAppHomeRouteImport } from './@routes/$locale/app/home'
import { Route as LocaleAppAssistantRouteImport } from './@routes/$locale/app/assistant'
import { Route as ApiPublicMigrationRunRouteImport } from './@routes/api/public/migration/run'
import { Route as LocaleAppInboxPriorityRouteImport } from './@routes/$locale/app/inbox/$priority'
import { Route as LocaleAppBuyerSearchRouteImport } from './@routes/$locale/app/buyer/search'
import { Route as LocaleAppSellerTransactionListRouteImport } from './@routes/$locale/app/seller/transaction/list'
import { Route as LocaleAppSellerListingMyRouteImport } from './@routes/$locale/app/seller/listing/my'
import { Route as LocaleAppSellerDraftResolveRouteImport } from './@routes/$locale/app/seller/draft/resolve'
import { Route as LocaleAppSellerDraftListRouteImport } from './@routes/$locale/app/seller/draft/list'
import { Route as LocaleAppBuyerTransactionListRouteImport } from './@routes/$locale/app/buyer/transaction/list'
import { Route as LocaleAppBuyerFeedListRouteImport } from './@routes/$locale/app/buyer/feed/list'
import { Route as LocaleAppBuyerFeedDefaultRouteImport } from './@routes/$locale/app/buyer/feed/default'
import { Route as LocaleAppBuyerFavouriteListRouteImport } from './@routes/$locale/app/buyer/favourite/list'
import { Route as LocaleAppSellerTransactionTransactionIdDetailRouteImport } from './@routes/$locale/app/seller/transaction/$transactionId/detail'
import { Route as LocaleAppSellerTransactionListingIdListRouteImport } from './@routes/$locale/app/seller/transaction/$listingId/list'
import { Route as LocaleAppSellerDraftIdEditRouteImport } from './@routes/$locale/app/seller/draft/$id/edit'
import { Route as LocaleAppBuyerTransactionTransactionIdDetailRouteImport } from './@routes/$locale/app/buyer/transaction/$transactionId/detail'
import { Route as LocaleAppBuyerFeedIdListRouteImport } from './@routes/$locale/app/buyer/feed/$id/list'
import { Route as LocaleAppBuyerFeedIdFavouriteListRouteImport } from './@routes/$locale/app/buyer/feed/$id/favourite/list'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownRoute = DotwellKnownRouteImport.update({
  id: '/.well-known',
  path: '/.well-known',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const RedirectSignInRoute = RedirectSignInRouteImport.update({
  id: '/redirect/sign-in',
  path: '/redirect/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectOathRoute = RedirectOathRouteImport.update({
  id: '/redirect/oath',
  path: '/redirect/oath',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ApiRoute,
} as any)
const ApiE2eRoute = ApiE2eRouteImport.update({
  id: '/e2e',
  path: '/e2e',
  getParentRoute: () => ApiRoute,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ApiRoute,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/$cron',
  path: '/$cron',
  getParentRoute: () => ApiRoute,
} as any)
const LocaleTosRoute = LocaleTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSignUpRoute = LocaleSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSignInRoute = LocaleSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOathRoute = LocaleOathRouteImport.update({
  id: '/oath',
  path: '/oath',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLandingRoute = LocaleLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppRoute = LocaleAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppIndexRoute = LocaleAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAppRoute,
} as any)
const ApiOauthAuthorizeRoute = ApiOauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => ApiRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/auth/$',
  path: '/auth/$',
  getParentRoute: () => ApiRoute,
} as any)
const LocaleAppWelcomeRoute = LocaleAppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppUserRoute = LocaleAppUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppShopRoute = LocaleAppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppHomeRoute = LocaleAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppAssistantRoute = LocaleAppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => LocaleAppRoute,
} as any)
const ApiPublicMigrationRunRoute = ApiPublicMigrationRunRouteImport.update({
  id: '/public/migration/run',
  path: '/public/migration/run',
  getParentRoute: () => ApiRoute,
} as any)
const LocaleAppInboxPriorityRoute = LocaleAppInboxPriorityRouteImport.update({
  id: '/inbox/$priority',
  path: '/inbox/$priority',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppBuyerSearchRoute = LocaleAppBuyerSearchRouteImport.update({
  id: '/buyer/search',
  path: '/buyer/search',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppSellerTransactionListRoute =
  LocaleAppSellerTransactionListRouteImport.update({
    id: '/seller/transaction/list',
    path: '/seller/transaction/list',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppSellerListingMyRoute =
  LocaleAppSellerListingMyRouteImport.update({
    id: '/seller/listing/my',
    path: '/seller/listing/my',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppSellerDraftResolveRoute =
  LocaleAppSellerDraftResolveRouteImport.update({
    id: '/seller/draft/resolve',
    path: '/seller/draft/resolve',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppSellerDraftListRoute =
  LocaleAppSellerDraftListRouteImport.update({
    id: '/seller/draft/list',
    path: '/seller/draft/list',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppBuyerTransactionListRoute =
  LocaleAppBuyerTransactionListRouteImport.update({
    id: '/buyer/transaction/list',
    path: '/buyer/transaction/list',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppBuyerFeedListRoute = LocaleAppBuyerFeedListRouteImport.update({
  id: '/buyer/feed/list',
  path: '/buyer/feed/list',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppBuyerFeedDefaultRoute =
  LocaleAppBuyerFeedDefaultRouteImport.update({
    id: '/buyer/feed/default',
    path: '/buyer/feed/default',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppBuyerFavouriteListRoute =
  LocaleAppBuyerFavouriteListRouteImport.update({
    id: '/buyer/favourite/list',
    path: '/buyer/favourite/list',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppSellerTransactionTransactionIdDetailRoute =
  LocaleAppSellerTransactionTransactionIdDetailRouteImport.update({
    id: '/seller/transaction/$transactionId/detail',
    path: '/seller/transaction/$transactionId/detail',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppSellerTransactionListingIdListRoute =
  LocaleAppSellerTransactionListingIdListRouteImport.update({
    id: '/seller/transaction/$listingId/list',
    path: '/seller/transaction/$listingId/list',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppSellerDraftIdEditRoute =
  LocaleAppSellerDraftIdEditRouteImport.update({
    id: '/seller/draft/$id/edit',
    path: '/seller/draft/$id/edit',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppBuyerTransactionTransactionIdDetailRoute =
  LocaleAppBuyerTransactionTransactionIdDetailRouteImport.update({
    id: '/buyer/transaction/$transactionId/detail',
    path: '/buyer/transaction/$transactionId/detail',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppBuyerFeedIdListRoute =
  LocaleAppBuyerFeedIdListRouteImport.update({
    id: '/buyer/feed/$id/list',
    path: '/buyer/feed/$id/list',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppBuyerFeedIdFavouriteListRoute =
  LocaleAppBuyerFeedIdFavouriteListRouteImport.update({
    id: '/buyer/feed/$id/favourite/list',
    path: '/buyer/feed/$id/favourite/list',
    getParentRoute: () => LocaleAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/.well-known': typeof DotwellKnownRoute
  '/api': typeof ApiRouteWithChildren
  '/mcp': typeof McpRoute
  '/$locale/app': typeof LocaleAppRouteWithChildren
  '/$locale/landing': typeof LocaleLandingRoute
  '/$locale/oath': typeof LocaleOathRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/$locale/tos': typeof LocaleTosRoute
  '/api/$cron': typeof ApiCronRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/e2e': typeof ApiE2eRoute
  '/api/health': typeof ApiHealthRoute
  '/redirect/oath': typeof RedirectOathRoute
  '/redirect/sign-in': typeof RedirectSignInRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/app/assistant': typeof LocaleAppAssistantRoute
  '/$locale/app/home': typeof LocaleAppHomeRoute
  '/$locale/app/shop': typeof LocaleAppShopRoute
  '/$locale/app/user': typeof LocaleAppUserRoute
  '/$locale/app/welcome': typeof LocaleAppWelcomeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/authorize': typeof ApiOauthAuthorizeRoute
  '/$locale/app/': typeof LocaleAppIndexRoute
  '/$locale/app/buyer/search': typeof LocaleAppBuyerSearchRoute
  '/$locale/app/inbox/$priority': typeof LocaleAppInboxPriorityRoute
  '/api/public/migration/run': typeof ApiPublicMigrationRunRoute
  '/$locale/app/buyer/favourite/list': typeof LocaleAppBuyerFavouriteListRoute
  '/$locale/app/buyer/feed/default': typeof LocaleAppBuyerFeedDefaultRoute
  '/$locale/app/buyer/feed/list': typeof LocaleAppBuyerFeedListRoute
  '/$locale/app/buyer/transaction/list': typeof LocaleAppBuyerTransactionListRoute
  '/$locale/app/seller/draft/list': typeof LocaleAppSellerDraftListRoute
  '/$locale/app/seller/draft/resolve': typeof LocaleAppSellerDraftResolveRoute
  '/$locale/app/seller/listing/my': typeof LocaleAppSellerListingMyRoute
  '/$locale/app/seller/transaction/list': typeof LocaleAppSellerTransactionListRoute
  '/$locale/app/buyer/feed/$id/list': typeof LocaleAppBuyerFeedIdListRoute
  '/$locale/app/buyer/transaction/$transactionId/detail': typeof LocaleAppBuyerTransactionTransactionIdDetailRoute
  '/$locale/app/seller/draft/$id/edit': typeof LocaleAppSellerDraftIdEditRoute
  '/$locale/app/seller/transaction/$listingId/list': typeof LocaleAppSellerTransactionListingIdListRoute
  '/$locale/app/seller/transaction/$transactionId/detail': typeof LocaleAppSellerTransactionTransactionIdDetailRoute
  '/$locale/app/buyer/feed/$id/favourite/list': typeof LocaleAppBuyerFeedIdFavouriteListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/.well-known': typeof DotwellKnownRoute
  '/api': typeof ApiRouteWithChildren
  '/mcp': typeof McpRoute
  '/$locale/landing': typeof LocaleLandingRoute
  '/$locale/oath': typeof LocaleOathRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/$locale/tos': typeof LocaleTosRoute
  '/api/$cron': typeof ApiCronRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/e2e': typeof ApiE2eRoute
  '/api/health': typeof ApiHealthRoute
  '/redirect/oath': typeof RedirectOathRoute
  '/redirect/sign-in': typeof RedirectSignInRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/app/assistant': typeof LocaleAppAssistantRoute
  '/$locale/app/home': typeof LocaleAppHomeRoute
  '/$locale/app/shop': typeof LocaleAppShopRoute
  '/$locale/app/user': typeof LocaleAppUserRoute
  '/$locale/app/welcome': typeof LocaleAppWelcomeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/authorize': typeof ApiOauthAuthorizeRoute
  '/$locale/app': typeof LocaleAppIndexRoute
  '/$locale/app/buyer/search': typeof LocaleAppBuyerSearchRoute
  '/$locale/app/inbox/$priority': typeof LocaleAppInboxPriorityRoute
  '/api/public/migration/run': typeof ApiPublicMigrationRunRoute
  '/$locale/app/buyer/favourite/list': typeof LocaleAppBuyerFavouriteListRoute
  '/$locale/app/buyer/feed/default': typeof LocaleAppBuyerFeedDefaultRoute
  '/$locale/app/buyer/feed/list': typeof LocaleAppBuyerFeedListRoute
  '/$locale/app/buyer/transaction/list': typeof LocaleAppBuyerTransactionListRoute
  '/$locale/app/seller/draft/list': typeof LocaleAppSellerDraftListRoute
  '/$locale/app/seller/draft/resolve': typeof LocaleAppSellerDraftResolveRoute
  '/$locale/app/seller/listing/my': typeof LocaleAppSellerListingMyRoute
  '/$locale/app/seller/transaction/list': typeof LocaleAppSellerTransactionListRoute
  '/$locale/app/buyer/feed/$id/list': typeof LocaleAppBuyerFeedIdListRoute
  '/$locale/app/buyer/transaction/$transactionId/detail': typeof LocaleAppBuyerTransactionTransactionIdDetailRoute
  '/$locale/app/seller/draft/$id/edit': typeof LocaleAppSellerDraftIdEditRoute
  '/$locale/app/seller/transaction/$listingId/list': typeof LocaleAppSellerTransactionListingIdListRoute
  '/$locale/app/seller/transaction/$transactionId/detail': typeof LocaleAppSellerTransactionTransactionIdDetailRoute
  '/$locale/app/buyer/feed/$id/favourite/list': typeof LocaleAppBuyerFeedIdFavouriteListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/.well-known': typeof DotwellKnownRoute
  '/api': typeof ApiRouteWithChildren
  '/mcp': typeof McpRoute
  '/$locale/app': typeof LocaleAppRouteWithChildren
  '/$locale/landing': typeof LocaleLandingRoute
  '/$locale/oath': typeof LocaleOathRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/$locale/tos': typeof LocaleTosRoute
  '/api/$cron': typeof ApiCronRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/e2e': typeof ApiE2eRoute
  '/api/health': typeof ApiHealthRoute
  '/redirect/oath': typeof RedirectOathRoute
  '/redirect/sign-in': typeof RedirectSignInRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/app/assistant': typeof LocaleAppAssistantRoute
  '/$locale/app/home': typeof LocaleAppHomeRoute
  '/$locale/app/shop': typeof LocaleAppShopRoute
  '/$locale/app/user': typeof LocaleAppUserRoute
  '/$locale/app/welcome': typeof LocaleAppWelcomeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/authorize': typeof ApiOauthAuthorizeRoute
  '/$locale/app/': typeof LocaleAppIndexRoute
  '/$locale/app/buyer/search': typeof LocaleAppBuyerSearchRoute
  '/$locale/app/inbox/$priority': typeof LocaleAppInboxPriorityRoute
  '/api/public/migration/run': typeof ApiPublicMigrationRunRoute
  '/$locale/app/buyer/favourite/list': typeof LocaleAppBuyerFavouriteListRoute
  '/$locale/app/buyer/feed/default': typeof LocaleAppBuyerFeedDefaultRoute
  '/$locale/app/buyer/feed/list': typeof LocaleAppBuyerFeedListRoute
  '/$locale/app/buyer/transaction/list': typeof LocaleAppBuyerTransactionListRoute
  '/$locale/app/seller/draft/list': typeof LocaleAppSellerDraftListRoute
  '/$locale/app/seller/draft/resolve': typeof LocaleAppSellerDraftResolveRoute
  '/$locale/app/seller/listing/my': typeof LocaleAppSellerListingMyRoute
  '/$locale/app/seller/transaction/list': typeof LocaleAppSellerTransactionListRoute
  '/$locale/app/buyer/feed/$id/list': typeof LocaleAppBuyerFeedIdListRoute
  '/$locale/app/buyer/transaction/$transactionId/detail': typeof LocaleAppBuyerTransactionTransactionIdDetailRoute
  '/$locale/app/seller/draft/$id/edit': typeof LocaleAppSellerDraftIdEditRoute
  '/$locale/app/seller/transaction/$listingId/list': typeof LocaleAppSellerTransactionListingIdListRoute
  '/$locale/app/seller/transaction/$transactionId/detail': typeof LocaleAppSellerTransactionTransactionIdDetailRoute
  '/$locale/app/buyer/feed/$id/favourite/list': typeof LocaleAppBuyerFeedIdFavouriteListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/.well-known'
    | '/api'
    | '/mcp'
    | '/$locale/app'
    | '/$locale/landing'
    | '/$locale/oath'
    | '/$locale/privacy'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/$locale/tos'
    | '/api/$cron'
    | '/api/assistant'
    | '/api/e2e'
    | '/api/health'
    | '/redirect/oath'
    | '/redirect/sign-in'
    | '/$locale/'
    | '/$locale/app/assistant'
    | '/$locale/app/home'
    | '/$locale/app/shop'
    | '/$locale/app/user'
    | '/$locale/app/welcome'
    | '/api/auth/$'
    | '/api/oauth/authorize'
    | '/$locale/app/'
    | '/$locale/app/buyer/search'
    | '/$locale/app/inbox/$priority'
    | '/api/public/migration/run'
    | '/$locale/app/buyer/favourite/list'
    | '/$locale/app/buyer/feed/default'
    | '/$locale/app/buyer/feed/list'
    | '/$locale/app/buyer/transaction/list'
    | '/$locale/app/seller/draft/list'
    | '/$locale/app/seller/draft/resolve'
    | '/$locale/app/seller/listing/my'
    | '/$locale/app/seller/transaction/list'
    | '/$locale/app/buyer/feed/$id/list'
    | '/$locale/app/buyer/transaction/$transactionId/detail'
    | '/$locale/app/seller/draft/$id/edit'
    | '/$locale/app/seller/transaction/$listingId/list'
    | '/$locale/app/seller/transaction/$transactionId/detail'
    | '/$locale/app/buyer/feed/$id/favourite/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/.well-known'
    | '/api'
    | '/mcp'
    | '/$locale/landing'
    | '/$locale/oath'
    | '/$locale/privacy'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/$locale/tos'
    | '/api/$cron'
    | '/api/assistant'
    | '/api/e2e'
    | '/api/health'
    | '/redirect/oath'
    | '/redirect/sign-in'
    | '/$locale'
    | '/$locale/app/assistant'
    | '/$locale/app/home'
    | '/$locale/app/shop'
    | '/$locale/app/user'
    | '/$locale/app/welcome'
    | '/api/auth/$'
    | '/api/oauth/authorize'
    | '/$locale/app'
    | '/$locale/app/buyer/search'
    | '/$locale/app/inbox/$priority'
    | '/api/public/migration/run'
    | '/$locale/app/buyer/favourite/list'
    | '/$locale/app/buyer/feed/default'
    | '/$locale/app/buyer/feed/list'
    | '/$locale/app/buyer/transaction/list'
    | '/$locale/app/seller/draft/list'
    | '/$locale/app/seller/draft/resolve'
    | '/$locale/app/seller/listing/my'
    | '/$locale/app/seller/transaction/list'
    | '/$locale/app/buyer/feed/$id/list'
    | '/$locale/app/buyer/transaction/$transactionId/detail'
    | '/$locale/app/seller/draft/$id/edit'
    | '/$locale/app/seller/transaction/$listingId/list'
    | '/$locale/app/seller/transaction/$transactionId/detail'
    | '/$locale/app/buyer/feed/$id/favourite/list'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/.well-known'
    | '/api'
    | '/mcp'
    | '/$locale/app'
    | '/$locale/landing'
    | '/$locale/oath'
    | '/$locale/privacy'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/$locale/tos'
    | '/api/$cron'
    | '/api/assistant'
    | '/api/e2e'
    | '/api/health'
    | '/redirect/oath'
    | '/redirect/sign-in'
    | '/$locale/'
    | '/$locale/app/assistant'
    | '/$locale/app/home'
    | '/$locale/app/shop'
    | '/$locale/app/user'
    | '/$locale/app/welcome'
    | '/api/auth/$'
    | '/api/oauth/authorize'
    | '/$locale/app/'
    | '/$locale/app/buyer/search'
    | '/$locale/app/inbox/$priority'
    | '/api/public/migration/run'
    | '/$locale/app/buyer/favourite/list'
    | '/$locale/app/buyer/feed/default'
    | '/$locale/app/buyer/feed/list'
    | '/$locale/app/buyer/transaction/list'
    | '/$locale/app/seller/draft/list'
    | '/$locale/app/seller/draft/resolve'
    | '/$locale/app/seller/listing/my'
    | '/$locale/app/seller/transaction/list'
    | '/$locale/app/buyer/feed/$id/list'
    | '/$locale/app/buyer/transaction/$transactionId/detail'
    | '/$locale/app/seller/draft/$id/edit'
    | '/$locale/app/seller/transaction/$listingId/list'
    | '/$locale/app/seller/transaction/$transactionId/detail'
    | '/$locale/app/buyer/feed/$id/favourite/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  DotwellKnownRoute: typeof DotwellKnownRoute
  ApiRoute: typeof ApiRouteWithChildren
  McpRoute: typeof McpRoute
  RedirectOathRoute: typeof RedirectOathRoute
  RedirectSignInRoute: typeof RedirectSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known': {
      id: '/.well-known'
      path: '/.well-known'
      fullPath: '/.well-known'
      preLoaderRoute: typeof DotwellKnownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/redirect/sign-in': {
      id: '/redirect/sign-in'
      path: '/redirect/sign-in'
      fullPath: '/redirect/sign-in'
      preLoaderRoute: typeof RedirectSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect/oath': {
      id: '/redirect/oath'
      path: '/redirect/oath'
      fullPath: '/redirect/oath'
      preLoaderRoute: typeof RedirectOathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/e2e': {
      id: '/api/e2e'
      path: '/e2e'
      fullPath: '/api/e2e'
      preLoaderRoute: typeof ApiE2eRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/$cron': {
      id: '/api/$cron'
      path: '/$cron'
      fullPath: '/api/$cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof ApiRoute
    }
    '/$locale/tos': {
      id: '/$locale/tos'
      path: '/tos'
      fullPath: '/$locale/tos'
      preLoaderRoute: typeof LocaleTosRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sign-up': {
      id: '/$locale/sign-up'
      path: '/sign-up'
      fullPath: '/$locale/sign-up'
      preLoaderRoute: typeof LocaleSignUpRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sign-in': {
      id: '/$locale/sign-in'
      path: '/sign-in'
      fullPath: '/$locale/sign-in'
      preLoaderRoute: typeof LocaleSignInRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/oath': {
      id: '/$locale/oath'
      path: '/oath'
      fullPath: '/$locale/oath'
      preLoaderRoute: typeof LocaleOathRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/landing': {
      id: '/$locale/landing'
      path: '/landing'
      fullPath: '/$locale/landing'
      preLoaderRoute: typeof LocaleLandingRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app': {
      id: '/$locale/app'
      path: '/app'
      fullPath: '/$locale/app'
      preLoaderRoute: typeof LocaleAppRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app/': {
      id: '/$locale/app/'
      path: '/'
      fullPath: '/$locale/app/'
      preLoaderRoute: typeof LocaleAppIndexRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/api/oauth/authorize': {
      id: '/api/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/api/oauth/authorize'
      preLoaderRoute: typeof ApiOauthAuthorizeRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof ApiRoute
    }
    '/$locale/app/welcome': {
      id: '/$locale/app/welcome'
      path: '/welcome'
      fullPath: '/$locale/app/welcome'
      preLoaderRoute: typeof LocaleAppWelcomeRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/user': {
      id: '/$locale/app/user'
      path: '/user'
      fullPath: '/$locale/app/user'
      preLoaderRoute: typeof LocaleAppUserRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/shop': {
      id: '/$locale/app/shop'
      path: '/shop'
      fullPath: '/$locale/app/shop'
      preLoaderRoute: typeof LocaleAppShopRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/home': {
      id: '/$locale/app/home'
      path: '/home'
      fullPath: '/$locale/app/home'
      preLoaderRoute: typeof LocaleAppHomeRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/assistant': {
      id: '/$locale/app/assistant'
      path: '/assistant'
      fullPath: '/$locale/app/assistant'
      preLoaderRoute: typeof LocaleAppAssistantRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/api/public/migration/run': {
      id: '/api/public/migration/run'
      path: '/public/migration/run'
      fullPath: '/api/public/migration/run'
      preLoaderRoute: typeof ApiPublicMigrationRunRouteImport
      parentRoute: typeof ApiRoute
    }
    '/$locale/app/inbox/$priority': {
      id: '/$locale/app/inbox/$priority'
      path: '/inbox/$priority'
      fullPath: '/$locale/app/inbox/$priority'
      preLoaderRoute: typeof LocaleAppInboxPriorityRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/buyer/search': {
      id: '/$locale/app/buyer/search'
      path: '/buyer/search'
      fullPath: '/$locale/app/buyer/search'
      preLoaderRoute: typeof LocaleAppBuyerSearchRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/seller/transaction/list': {
      id: '/$locale/app/seller/transaction/list'
      path: '/seller/transaction/list'
      fullPath: '/$locale/app/seller/transaction/list'
      preLoaderRoute: typeof LocaleAppSellerTransactionListRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/seller/listing/my': {
      id: '/$locale/app/seller/listing/my'
      path: '/seller/listing/my'
      fullPath: '/$locale/app/seller/listing/my'
      preLoaderRoute: typeof LocaleAppSellerListingMyRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/seller/draft/resolve': {
      id: '/$locale/app/seller/draft/resolve'
      path: '/seller/draft/resolve'
      fullPath: '/$locale/app/seller/draft/resolve'
      preLoaderRoute: typeof LocaleAppSellerDraftResolveRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/seller/draft/list': {
      id: '/$locale/app/seller/draft/list'
      path: '/seller/draft/list'
      fullPath: '/$locale/app/seller/draft/list'
      preLoaderRoute: typeof LocaleAppSellerDraftListRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/buyer/transaction/list': {
      id: '/$locale/app/buyer/transaction/list'
      path: '/buyer/transaction/list'
      fullPath: '/$locale/app/buyer/transaction/list'
      preLoaderRoute: typeof LocaleAppBuyerTransactionListRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/buyer/feed/list': {
      id: '/$locale/app/buyer/feed/list'
      path: '/buyer/feed/list'
      fullPath: '/$locale/app/buyer/feed/list'
      preLoaderRoute: typeof LocaleAppBuyerFeedListRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/buyer/feed/default': {
      id: '/$locale/app/buyer/feed/default'
      path: '/buyer/feed/default'
      fullPath: '/$locale/app/buyer/feed/default'
      preLoaderRoute: typeof LocaleAppBuyerFeedDefaultRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/buyer/favourite/list': {
      id: '/$locale/app/buyer/favourite/list'
      path: '/buyer/favourite/list'
      fullPath: '/$locale/app/buyer/favourite/list'
      preLoaderRoute: typeof LocaleAppBuyerFavouriteListRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/seller/transaction/$transactionId/detail': {
      id: '/$locale/app/seller/transaction/$transactionId/detail'
      path: '/seller/transaction/$transactionId/detail'
      fullPath: '/$locale/app/seller/transaction/$transactionId/detail'
      preLoaderRoute: typeof LocaleAppSellerTransactionTransactionIdDetailRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/seller/transaction/$listingId/list': {
      id: '/$locale/app/seller/transaction/$listingId/list'
      path: '/seller/transaction/$listingId/list'
      fullPath: '/$locale/app/seller/transaction/$listingId/list'
      preLoaderRoute: typeof LocaleAppSellerTransactionListingIdListRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/seller/draft/$id/edit': {
      id: '/$locale/app/seller/draft/$id/edit'
      path: '/seller/draft/$id/edit'
      fullPath: '/$locale/app/seller/draft/$id/edit'
      preLoaderRoute: typeof LocaleAppSellerDraftIdEditRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/buyer/transaction/$transactionId/detail': {
      id: '/$locale/app/buyer/transaction/$transactionId/detail'
      path: '/buyer/transaction/$transactionId/detail'
      fullPath: '/$locale/app/buyer/transaction/$transactionId/detail'
      preLoaderRoute: typeof LocaleAppBuyerTransactionTransactionIdDetailRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/buyer/feed/$id/list': {
      id: '/$locale/app/buyer/feed/$id/list'
      path: '/buyer/feed/$id/list'
      fullPath: '/$locale/app/buyer/feed/$id/list'
      preLoaderRoute: typeof LocaleAppBuyerFeedIdListRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/buyer/feed/$id/favourite/list': {
      id: '/$locale/app/buyer/feed/$id/favourite/list'
      path: '/buyer/feed/$id/favourite/list'
      fullPath: '/$locale/app/buyer/feed/$id/favourite/list'
      preLoaderRoute: typeof LocaleAppBuyerFeedIdFavouriteListRouteImport
      parentRoute: typeof LocaleAppRoute
    }
  }
}

interface LocaleAppRouteChildren {
  LocaleAppAssistantRoute: typeof LocaleAppAssistantRoute
  LocaleAppHomeRoute: typeof LocaleAppHomeRoute
  LocaleAppShopRoute: typeof LocaleAppShopRoute
  LocaleAppUserRoute: typeof LocaleAppUserRoute
  LocaleAppWelcomeRoute: typeof LocaleAppWelcomeRoute
  LocaleAppIndexRoute: typeof LocaleAppIndexRoute
  LocaleAppBuyerSearchRoute: typeof LocaleAppBuyerSearchRoute
  LocaleAppInboxPriorityRoute: typeof LocaleAppInboxPriorityRoute
  LocaleAppBuyerFavouriteListRoute: typeof LocaleAppBuyerFavouriteListRoute
  LocaleAppBuyerFeedDefaultRoute: typeof LocaleAppBuyerFeedDefaultRoute
  LocaleAppBuyerFeedListRoute: typeof LocaleAppBuyerFeedListRoute
  LocaleAppBuyerTransactionListRoute: typeof LocaleAppBuyerTransactionListRoute
  LocaleAppSellerDraftListRoute: typeof LocaleAppSellerDraftListRoute
  LocaleAppSellerDraftResolveRoute: typeof LocaleAppSellerDraftResolveRoute
  LocaleAppSellerListingMyRoute: typeof LocaleAppSellerListingMyRoute
  LocaleAppSellerTransactionListRoute: typeof LocaleAppSellerTransactionListRoute
  LocaleAppBuyerFeedIdListRoute: typeof LocaleAppBuyerFeedIdListRoute
  LocaleAppBuyerTransactionTransactionIdDetailRoute: typeof LocaleAppBuyerTransactionTransactionIdDetailRoute
  LocaleAppSellerDraftIdEditRoute: typeof LocaleAppSellerDraftIdEditRoute
  LocaleAppSellerTransactionListingIdListRoute: typeof LocaleAppSellerTransactionListingIdListRoute
  LocaleAppSellerTransactionTransactionIdDetailRoute: typeof LocaleAppSellerTransactionTransactionIdDetailRoute
  LocaleAppBuyerFeedIdFavouriteListRoute: typeof LocaleAppBuyerFeedIdFavouriteListRoute
}

const LocaleAppRouteChildren: LocaleAppRouteChildren = {
  LocaleAppAssistantRoute: LocaleAppAssistantRoute,
  LocaleAppHomeRoute: LocaleAppHomeRoute,
  LocaleAppShopRoute: LocaleAppShopRoute,
  LocaleAppUserRoute: LocaleAppUserRoute,
  LocaleAppWelcomeRoute: LocaleAppWelcomeRoute,
  LocaleAppIndexRoute: LocaleAppIndexRoute,
  LocaleAppBuyerSearchRoute: LocaleAppBuyerSearchRoute,
  LocaleAppInboxPriorityRoute: LocaleAppInboxPriorityRoute,
  LocaleAppBuyerFavouriteListRoute: LocaleAppBuyerFavouriteListRoute,
  LocaleAppBuyerFeedDefaultRoute: LocaleAppBuyerFeedDefaultRoute,
  LocaleAppBuyerFeedListRoute: LocaleAppBuyerFeedListRoute,
  LocaleAppBuyerTransactionListRoute: LocaleAppBuyerTransactionListRoute,
  LocaleAppSellerDraftListRoute: LocaleAppSellerDraftListRoute,
  LocaleAppSellerDraftResolveRoute: LocaleAppSellerDraftResolveRoute,
  LocaleAppSellerListingMyRoute: LocaleAppSellerListingMyRoute,
  LocaleAppSellerTransactionListRoute: LocaleAppSellerTransactionListRoute,
  LocaleAppBuyerFeedIdListRoute: LocaleAppBuyerFeedIdListRoute,
  LocaleAppBuyerTransactionTransactionIdDetailRoute:
    LocaleAppBuyerTransactionTransactionIdDetailRoute,
  LocaleAppSellerDraftIdEditRoute: LocaleAppSellerDraftIdEditRoute,
  LocaleAppSellerTransactionListingIdListRoute:
    LocaleAppSellerTransactionListingIdListRoute,
  LocaleAppSellerTransactionTransactionIdDetailRoute:
    LocaleAppSellerTransactionTransactionIdDetailRoute,
  LocaleAppBuyerFeedIdFavouriteListRoute:
    LocaleAppBuyerFeedIdFavouriteListRoute,
}

const LocaleAppRouteWithChildren = LocaleAppRoute._addFileChildren(
  LocaleAppRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAppRoute: typeof LocaleAppRouteWithChildren
  LocaleLandingRoute: typeof LocaleLandingRoute
  LocaleOathRoute: typeof LocaleOathRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleSignInRoute: typeof LocaleSignInRoute
  LocaleSignUpRoute: typeof LocaleSignUpRoute
  LocaleTosRoute: typeof LocaleTosRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAppRoute: LocaleAppRouteWithChildren,
  LocaleLandingRoute: LocaleLandingRoute,
  LocaleOathRoute: LocaleOathRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleSignInRoute: LocaleSignInRoute,
  LocaleSignUpRoute: LocaleSignUpRoute,
  LocaleTosRoute: LocaleTosRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface ApiRouteChildren {
  ApiCronRoute: typeof ApiCronRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  ApiE2eRoute: typeof ApiE2eRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOauthAuthorizeRoute: typeof ApiOauthAuthorizeRoute
  ApiPublicMigrationRunRoute: typeof ApiPublicMigrationRunRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiCronRoute: ApiCronRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  ApiE2eRoute: ApiE2eRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOauthAuthorizeRoute: ApiOauthAuthorizeRoute,
  ApiPublicMigrationRunRoute: ApiPublicMigrationRunRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  DotwellKnownRoute: DotwellKnownRoute,
  ApiRoute: ApiRouteWithChildren,
  McpRoute: McpRoute,
  RedirectOathRoute: RedirectOathRoute,
  RedirectSignInRoute: RedirectSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
