// This file is auto-generated by @hey-api/openapi-ts

export type clientOptions = {
	baseUrl: "http://obsidian-ii.local:3032" | (string & {});
};

/**
 * Collection of feed items
 */
export type tFeedCollection = {
	data: Array<tFeedDto>;
	/**
	 * Whether there are more items to fetch
	 */
	more: boolean;
};

/**
 * Latitude and longitude coordinates
 */
export type tLatLon = {
	/**
	 * Latitude coordinate
	 */
	lat: number;
	/**
	 * Longitude coordinate
	 */
	lon: number;
};

/**
 * Metadata for a listing (query)
 */
export type tListingMeta = {
	latLon?: tLatLon;
};

/**
 * Sort object for listing collection
 */
export type tListingSort = {
	value:
		| "price"
		| "condition"
		| "age"
		| "createdAt"
		| "updatedAt"
		| "expiresAt"
		| "geo";
	sort?: "asc" | "desc";
};

/**
 * This filter matches listings with currency codes in the provided array
 */
export type tCurrencyIn = Array<tCurrencyList>;

/**
 * Currency code (ISO 4217)
 */
export const tCurrencyList = {
	CZK: "CZK",
	EUR: "EUR",
	USD: "USD",
	GBP: "GBP",
	PLN: "PLN",
	HUF: "HUF",
	CHF: "CHF",
} as const;

/**
 * Currency code (ISO 4217)
 */
export type tCurrencyList = (typeof tCurrencyList)[keyof typeof tCurrencyList];

/**
 * Filter listings based on the provided category IDs
 */
export type tCategoryIdIn = Array<tCategoryId & unknown>;

/**
 * This filter matches listings with the exact category ID
 */
export type tCategoryId = string;

/**
 * Sets the maximum price for the listings
 */
export type tPriceMax = number;

/**
 * Sets the minimum price for the listings
 */
export type tPriceMin = number;

/**
 * User-land filters
 */
export type tListingFilter = {
	/**
	 * This filter matches the exact id
	 */
	id?: string | null;
	/**
	 * This filter matches the ids
	 */
	idIn?: Array<string> | null;
	/**
	 * Runs fulltext on the collection/query.
	 */
	fulltext?: string | null;
	priceMin?: tPriceMin;
	priceMax?: tPriceMax;
	/**
	 * This filter matches listings with condition greater than or equal to the provided value
	 */
	conditionMin?: number;
	/**
	 * This filter matches listings with condition less than or equal to the provided value
	 */
	conditionMax?: number;
	/**
	 * This filter matches listings with conditions in the provided array
	 */
	conditionIn?: Array<number> | null;
	/**
	 * This filter matches listings with age greater than or equal to the provided value
	 */
	ageMin?: number;
	/**
	 * This filter matches listings with age less than or equal to the provided value
	 */
	ageMax?: number;
	categoryId?: tCategoryId;
	categoryIdIn?: tCategoryIdIn;
	currency?: tCurrencyList;
	currencyIn?: tCurrencyIn;
	/**
	 * This filter matches listings that expire before the provided date
	 */
	expiresAtBefore?: string | null;
	/**
	 * This filter matches listings that expire after the provided date
	 */
	expiresAtAfter?: string | null;
	/**
	 * This filter matches listings with range greater than or equal to the provided value (meters)
	 */
	rangeMin?: number | null;
	/**
	 * This filter matches listings with range less than or equal to the provided value (meters)
	 */
	rangeMax?: number | null;
	/**
	 * This filter matches listings with vendor matching the provided value
	 */
	vendor?: string | null;
	/**
	 * This filter matches listings with model matching the provided value
	 */
	model?: string | null;
};

/**
 * Feed data transfer object
 */
export type tFeedDto = {
	/**
	 * ID of the feed
	 */
	id: string;
	/**
	 * ID of the location associated with the feed
	 */
	locationId?: string | null;
	/**
	 * Name of the feed
	 */
	name: string;
	filter?: tListingFilter & unknown;
	/**
	 * Filter used to fetch the listings
	 */
	sort?: Array<tListingSort>;
	meta?: tListingMeta & unknown;
};

/**
 * Query object for feed collection
 */
export type tFeedQuery = {
	cursor?: tCursor;
	filter?: tFeedFilter;
	where?: tFeedFilter & unknown;
	sort?: Array<tFeedSort>;
};

/**
 * Sort object for feed collection
 */
export type tFeedSort = {
	value: "createdAt" | "updatedAt";
	sort?: "asc" | "desc";
};

/**
 * User-land filters for feed items
 */
export type tFeedFilter = {
	/**
	 * This filter matches the exact id
	 */
	id?: string | null;
	/**
	 * This filter matches the ids
	 */
	idIn?: Array<string> | null;
	/**
	 * Runs fulltext on the collection/query.
	 */
	fulltext?: string | null;
	/**
	 * Exact user id
	 */
	userId?: string | null;
};

/**
 * Cursor for pagination
 */
export type tCursor = {
	/**
	 * Page number (0-indexed)
	 */
	page: number;
	/**
	 * Page size
	 */
	size: number;
};

export type tFeedPatch = {
	id: string;
	/**
	 * Name of the feed
	 */
	name?: string;
	/**
	 * ID of the location associated with the feed
	 */
	locationId?: string | null;
	filter?: tListingFilter & unknown;
	/**
	 * Sort used to fetch the listings
	 */
	sort?: Array<tListingSort>;
	meta?: tListingMeta & unknown;
};

export type tFeedCreate = {
	/**
	 * Name of the feed
	 */
	name: string;
	/**
	 * ID of the location associated with the feed
	 */
	locationId?: string;
	filter: tListingFilter;
	sort: Array<tListingSort>;
	meta: tListingMeta;
};

/**
 * Schema for patching user extended information
 */
export type tUserPatch = {
	/**
	 * Default location for the user - used for listings & listing sorting
	 */
	locationId?: string | null;
	side?: tUserSide | null;
};

/**
 * User side - whether they are a seller or buyer
 */
export const tUserSide = {
	seller: "seller",
	buyer: "buyer",
} as const;

/**
 * User side - whether they are a seller or buyer
 */
export type tUserSide = (typeof tUserSide)[keyof typeof tUserSide];

export type tS3PreSignRequest = {
	/**
	 * Object path. After stripping leading '/', must start with `<userId>/`
	 */
	path: string;
	extension: tAllowedExtensions;
	contentType: tAllowedContentTypes;
};

/**
 * Browser-provided Content-Type used for PUT upload.
 */
export const tAllowedContentTypes = {
	"image/jpeg": "image/jpeg",
	"image/png": "image/png",
	"image/webp": "image/webp",
	"image/avif": "image/avif",
	"image/heic": "image/heic",
	"image/heif": "image/heif",
} as const;

/**
 * Browser-provided Content-Type used for PUT upload.
 */
export type tAllowedContentTypes =
	(typeof tAllowedContentTypes)[keyof typeof tAllowedContentTypes];

/**
 * File extension. Must be one of the allowed extensions.
 */
export const tAllowedExtensions = {
	webp: "webp",
	png: "png",
	jpg: "jpg",
	jpeg: "jpeg",
	avif: "avif",
	heic: "heic",
	heif: "heif",
} as const;

/**
 * File extension. Must be one of the allowed extensions.
 */
export type tAllowedExtensions =
	(typeof tAllowedExtensions)[keyof typeof tAllowedExtensions];

export type tS3PreSignResponse = {
	url: string;
	/**
	 * CDN url where the file lives
	 */
	cdn: string;
};

/**
 * Query object for location collection
 */
export type tLocationQuery = {
	cursor?: tCursor;
	filter?: tLocationFilter;
	where?: tLocationWhere;
	sort?: Array<tLocationSort>;
};

/**
 * Sort object for location collection
 */
export type tLocationSort = {
	value: "confidence" | "query" | "country" | "address";
	sort?: "asc" | "desc";
};

/**
 * App-based filters
 */
export type tLocationWhere = {
	/**
	 * This filter matches the exact id
	 */
	id?: string | null;
	/**
	 * This filter matches the ids
	 */
	idIn?: Array<string> | null;
	/**
	 * Runs fulltext on the collection/query.
	 */
	fulltext?: string | null;
	/**
	 * This filter matches the exact query that was used to get the location
	 */
	query?: string | null;
	/**
	 * This filter matches the exact language that was used to get the location
	 */
	lang?: string | null;
	/**
	 * This filter matches the exact country of the location
	 */
	country?: string | null;
	/**
	 * This filter matches the exact country code of the location
	 */
	code?: string | null;
	/**
	 * This filter matches locations with confidence greater than or equal to the provided value
	 */
	confidenceMin?: number | null;
};

/**
 * User-land filters
 */
export type tLocationFilter = {
	/**
	 * This filter matches the exact id
	 */
	id?: string | null;
	/**
	 * This filter matches the ids
	 */
	idIn?: Array<string> | null;
	/**
	 * Runs fulltext on the collection/query.
	 */
	fulltext?: string | null;
	/**
	 * This filter matches the exact query that was used to get the location
	 */
	query?: string | null;
	/**
	 * This filter matches the exact language that was used to get the location
	 */
	lang?: string | null;
	/**
	 * This filter matches the exact country of the location
	 */
	country?: string | null;
	/**
	 * This filter matches the exact country code of the location
	 */
	code?: string | null;
	/**
	 * This filter matches locations with confidence greater than or equal to the provided value
	 */
	confidenceMin?: number | null;
};

/**
 * Request body for location autocomplete
 */
export type tLocationAutocomplete = {
	/**
	 * The search text for location autocomplete
	 */
	text: string;
	/**
	 * The language code for the location search
	 */
	lang: string;
};

/**
 * Collection of upload items
 */
export type tUploadCollection = {
	data: Array<tUploadDto>;
	/**
	 * Whether there are more items to fetch
	 */
	more: boolean;
};

/**
 * Upload data transfer object
 */
export type tUploadDto = {
	/**
	 * ID of the upload
	 */
	id: string;
	/**
	 * Public URL to the uploaded file
	 */
	url: string;
};

/**
 * Query object for upload collection
 */
export type tUploadQuery = {
	cursor?: tCursor;
	filter?: tUploadFilter;
	where?: tUploadWhere;
	sort?: Array<tUploadSort>;
};

/**
 * Sort object for upload collection
 */
export type tUploadSort = {
	value: "createdAt";
	sort?: "asc" | "desc";
};

/**
 * App-based filters
 */
export type tUploadWhere = {
	/**
	 * This filter matches the exact id
	 */
	id?: string | null;
	/**
	 * This filter matches the ids
	 */
	idIn?: Array<string> | null;
	/**
	 * Runs fulltext on the collection/query.
	 */
	fulltext?: string | null;
};

/**
 * User-land filters for upload items
 */
export type tUploadFilter = {
	/**
	 * This filter matches the exact id
	 */
	id?: string | null;
	/**
	 * This filter matches the ids
	 */
	idIn?: Array<string> | null;
	/**
	 * Runs fulltext on the collection/query.
	 */
	fulltext?: string | null;
};

/**
 * Data for creating a new upload
 */
export type tUploadCreate = {
	/**
	 * Public URL to the uploaded file
	 */
	url: string;
};

/**
 * Collection of gallery items
 */
export type tGalleryCollection = {
	data: Array<tGalleryDto>;
	/**
	 * Whether there are more items to fetch
	 */
	more: boolean;
};

/**
 * Gallery data transfer object
 */
export type tGalleryDto = {
	/**
	 * ID of the gallery item
	 */
	id: string;
	/**
	 * ID of the listing this image belongs to
	 */
	listingId: string;
	/**
	 * ID of the upload this image belongs to
	 */
	uploadId: string;
	/**
	 * Sort order of the image in the listing's gallery
	 */
	sort: number;
	upload: tUploadDto;
};

/**
 * Query object for gallery collection
 */
export type tGalleryQuery = {
	cursor?: tCursor;
	filter?: tGalleryFilter;
	where?: tGalleryWhere;
	sort?: Array<tGallerySort>;
};

/**
 * Sort object for gallery collection
 */
export type tGallerySort = {
	value: "sort" | "createdAt";
	sort?: "asc" | "desc";
};

/**
 * App-based filters
 */
export type tGalleryWhere = {
	/**
	 * This filter matches the exact id
	 */
	id?: string | null;
	/**
	 * This filter matches the ids
	 */
	idIn?: Array<string> | null;
	/**
	 * Runs fulltext on the collection/query.
	 */
	fulltext?: string | null;
	/**
	 * Exact user id
	 */
	userId?: string | null;
	/**
	 * Exact listing id
	 */
	listingId?: string | null;
};

/**
 * User-land filters for gallery items
 */
export type tGalleryFilter = {
	/**
	 * This filter matches the exact id
	 */
	id?: string | null;
	/**
	 * This filter matches the ids
	 */
	idIn?: Array<string> | null;
	/**
	 * Runs fulltext on the collection/query.
	 */
	fulltext?: string | null;
	/**
	 * Exact user id
	 */
	userId?: string | null;
	/**
	 * Exact listing id
	 */
	listingId?: string | null;
};

/**
 * Query object for listing count (omits cursor, sort, and meta)
 */
export type tListingCountQuery = {
	filter?: tListingFilter;
	where?: tListingWhere;
	meta?: tListingMeta;
};

/**
 * App-based filters
 */
export type tListingWhere = {
	/**
	 * This filter matches the exact id
	 */
	id?: string | null;
	/**
	 * This filter matches the ids
	 */
	idIn?: Array<string> | null;
	/**
	 * Runs fulltext on the collection/query.
	 */
	fulltext?: string | null;
	priceMin?: tPriceMin;
	priceMax?: tPriceMax;
	/**
	 * This filter matches listings with condition greater than or equal to the provided value
	 */
	conditionMin?: number;
	/**
	 * This filter matches listings with condition less than or equal to the provided value
	 */
	conditionMax?: number;
	/**
	 * This filter matches listings with conditions in the provided array
	 */
	conditionIn?: Array<number> | null;
	/**
	 * This filter matches listings with age greater than or equal to the provided value
	 */
	ageMin?: number;
	/**
	 * This filter matches listings with age less than or equal to the provided value
	 */
	ageMax?: number;
	categoryId?: tCategoryId;
	categoryIdIn?: tCategoryIdIn;
	currency?: tCurrencyList;
	currencyIn?: tCurrencyIn;
	/**
	 * This filter matches listings that expire before the provided date
	 */
	expiresAtBefore?: string | null;
	/**
	 * This filter matches listings that expire after the provided date
	 */
	expiresAtAfter?: string | null;
	/**
	 * This filter matches listings with range greater than or equal to the provided value (meters)
	 */
	rangeMin?: number | null;
	/**
	 * This filter matches listings with range less than or equal to the provided value (meters)
	 */
	rangeMax?: number | null;
	/**
	 * This filter matches listings with vendor matching the provided value
	 */
	vendor?: string | null;
	/**
	 * This filter matches listings with model matching the provided value
	 */
	model?: string | null;
};

/**
 * Query object for listing collection
 */
export type tListingQuery = {
	cursor?: tCursor;
	filter?: tListingFilter;
	where?: tListingWhere;
	sort?: Array<tListingSort>;
	meta?: tListingMeta;
};

/**
 * Request to collect listings from a feed
 */
export type tFeedCollectionRequest = {
	/**
	 * ID of the feed to collect listings for
	 */
	feedId: string;
	/**
	 * Pagination cursor
	 */
	cursor?: {
		/**
		 * Page number (0-indexed)
		 */
		page: number;
		/**
		 * Page size
		 */
		size: number;
	} | null;
};

/**
 * Collection of listings
 */
export type tListingCollection = {
	data: Array<tListingDto>;
	/**
	 * Whether there are more items to fetch
	 */
	more: boolean;
};

/**
 * Category data transfer object
 */
export type tCategoryDto = {
	/**
	 * ID of the category
	 */
	id: string;
	/**
	 * Group/name of the category
	 */
	group: string;
	/**
	 * Category name within the group
	 */
	category: string;
	/**
	 * Slug of the category
	 */
	slug: string;
	/**
	 * Sort order (position) of the category
	 */
	sort: number;
	/**
	 * Locale/language of the category
	 */
	locale: string;
};

/**
 * Location data transfer object
 */
export type tLocationDto = {
	id: string;
	/**
	 * The query that was used to get the location
	 */
	query: string;
	/**
	 * The language that was used to get the location
	 */
	lang: string;
	/**
	 * The country that the location is in
	 */
	country: string;
	/**
	 * Country code
	 */
	code: string;
	/**
	 * The county that the location is in
	 */
	county?: string | null;
	/**
	 * The municipality that the location is in
	 */
	municipality?: string | null;
	/**
	 * The state that the location is in
	 */
	state?: string | null;
	/**
	 * Full address preview of a location
	 */
	address: string;
	/**
	 * The city that the location is in
	 */
	city?: string | null;
	/**
	 * The street that the location is on
	 */
	street?: string | null;
	/**
	 * The postal/zip code of the location
	 */
	zip?: string | null;
	/**
	 * Confidence score of the location (based on query)
	 */
	confidence: number;
	/**
	 * Used to uniquely identify this location entry
	 */
	hash: string;
	/**
	 * Latitude of the location
	 */
	lat: number;
	/**
	 * Longitude of the location
	 */
	lon: number;
};

export type tListingDto = {
	/**
	 * ID of the listing
	 */
	id: string;
	/**
	 * Price of the listing
	 */
	price: number;
	currency: tCurrencyList;
	/**
	 * Condition of the item (0-based index)
	 */
	condition: number;
	/**
	 * Age of the item (0-based index)
	 */
	age: number;
	/**
	 * ID of the location
	 */
	locationId: string;
	/**
	 * ID of the category
	 */
	categoryId: string;
	/**
	 * Expiration timestamp
	 */
	expiresAt: string;
	/**
	 * Creation timestamp
	 */
	createdAt: string;
	/**
	 * Last update timestamp
	 */
	updatedAt: string;
	/**
	 * Vendor/manufacturer of the item
	 */
	vendor?: string | null;
	/**
	 * Model of the item
	 */
	model?: string | null;
	location: tLocationDto;
	category: tCategoryDto;
	/**
	 * Array of listing gallery images
	 */
	gallery: Array<tGalleryDto>;
};

/**
 * Data required to create a new listing
 */
export type tListingCreate = {
	/**
	 * Price of the listing
	 */
	price: number;
	/**
	 * Condition of the item (0-based index)
	 */
	condition: number;
	/**
	 * Age of the item (0-based index)
	 */
	age: number;
	/**
	 * ID of the location
	 */
	locationId: string;
	/**
	 * ID of the category
	 */
	categoryId: string;
	currency: tCurrencyList;
	expiresAt: tListingExpire;
	/**
	 * Vendor/manufacturer of the item
	 */
	vendor?: string | null;
	/**
	 * Model of the item
	 */
	model?: string | null;
	/**
	 * IDs of the uploads; order of uploads defines order in the gallery
	 */
	uploadIds: Array<string>;
};

/**
 * Expiration period for the listing
 */
export const tListingExpire = {
	"7-days": "7-days",
	"14-days": "14-days",
	"1-month": "1-month",
} as const;

/**
 * Expiration period for the listing
 */
export type tListingExpire =
	(typeof tListingExpire)[keyof typeof tListingExpire];

/**
 * Complex count of items based on provided query.
 */
export type tCount = {
	/**
	 * Count of items based on provided where query.
	 */
	where: number;
	/**
	 * Count of items based on provided filter query.
	 */
	filter: number;
	/**
	 * Total count of items (no filters applied).
	 */
	total: number;
};

/**
 * Collection of categories
 */
export type tCategoryCollection = {
	data: Array<tCategoryDto>;
	/**
	 * Whether there are more items to fetch
	 */
	more: boolean;
};

/**
 * Query object for category collection
 */
export type tCategoryQuery = {
	cursor?: tCursor;
	filter?: tCategoryFilter;
	where?: tCategoryWhere;
	sort?: Array<tCategorySort>;
};

/**
 * Sort object for category collection
 */
export type tCategorySort = {
	value: "group" | "category" | "sort";
	sort?: "asc" | "desc";
};

/**
 * App-based filters
 */
export type tCategoryWhere = {
	/**
	 * This filter matches the exact id
	 */
	id?: string | null;
	/**
	 * This filter matches the ids
	 */
	idIn?: Array<string> | null;
	/**
	 * Runs fulltext on the collection/query.
	 */
	fulltext?: string | null;
	/**
	 * This filter matches the exact group of the category
	 */
	group?: string | null;
	/**
	 * This filter matches the exact category name
	 */
	category?: string | null;
	/**
	 * This filter matches the exact locale of the category
	 */
	locale?: string | null;
	/**
	 * This filter matches categories with locales in the provided array
	 */
	localeIn?: Array<string> | null;
};

/**
 * User-land filters
 */
export type tCategoryFilter = {
	/**
	 * This filter matches the exact id
	 */
	id?: string | null;
	/**
	 * This filter matches the ids
	 */
	idIn?: Array<string> | null;
	/**
	 * Runs fulltext on the collection/query.
	 */
	fulltext?: string | null;
	/**
	 * This filter matches the exact group of the category
	 */
	group?: string | null;
	/**
	 * This filter matches the exact category name
	 */
	category?: string | null;
	/**
	 * This filter matches the exact locale of the category
	 */
	locale?: string | null;
	/**
	 * This filter matches categories with locales in the provided array
	 */
	localeIn?: Array<string> | null;
};

/**
 * Standard error response format
 */
export type tErrorDto = {
	/**
	 * Error message describing what went wrong
	 */
	message: string;
};

export type tApiCategoryFetchRequest = {
	/**
	 * Query object for category fetch
	 */
	body?: tCategoryQuery;
	path?: never;
	query?: never;
	url: "/api/session/category/fetch";
};

export type apiCategoryFetchErrors = {
	/**
	 * Category not found
	 */
	404: tErrorDto;
};

export type apiCategoryFetchError =
	apiCategoryFetchErrors[keyof apiCategoryFetchErrors];

export type tApiCategoryFetchResponse = {
	/**
	 * Return a category based on the provided query
	 */
	200: tCategoryDto;
};

export type apiCategoryFetchResponse =
	tApiCategoryFetchResponse[keyof tApiCategoryFetchResponse];

export type tApiCategoryCollectionRequest = {
	body?: tCategoryQuery;
	path?: never;
	query?: never;
	url: "/api/session/category/collection";
};

export type tApiCategoryCollectionResponse = {
	/**
	 * Access collection of categories based on provided query
	 */
	200: tCategoryCollection;
};

export type apiCategoryCollectionResponse =
	tApiCategoryCollectionResponse[keyof tApiCategoryCollectionResponse];

export type tApiCategoryCountRequest = {
	body?: tCategoryQuery;
	path?: never;
	query?: never;
	url: "/api/session/category/count";
};

export type tApiCategoryCountResponse = {
	/**
	 * Return counts based on provided query
	 */
	200: tCount;
};

export type apiCategoryCountResponse =
	tApiCategoryCountResponse[keyof tApiCategoryCountResponse];

export type tApiListingCreateRequest = {
	/**
	 * Data for creating a new listing
	 */
	body?: tListingCreate;
	path?: never;
	query?: never;
	url: "/api/session/listing/create";
};

export type tApiListingCreateResponse = {
	/**
	 * The created listing
	 */
	201: tListingDto;
};

export type apiListingCreateResponse =
	tApiListingCreateResponse[keyof tApiListingCreateResponse];

export type tApiListingFeedCollectionRequest = {
	body?: tFeedCollectionRequest;
	path?: never;
	query?: never;
	url: "/api/session/listing/feed/collection";
};

export type apiListingFeedCollectionErrors = {
	/**
	 * Feed not found
	 */
	404: tErrorDto;
	/**
	 * Internal server error
	 */
	500: tErrorDto;
};

export type apiListingFeedCollectionError =
	apiListingFeedCollectionErrors[keyof apiListingFeedCollectionErrors];

export type tApiListingFeedCollectionResponse = {
	/**
	 * Access collection of listings based on a feed definition
	 */
	200: tListingCollection;
};

export type apiListingFeedCollectionResponse =
	tApiListingFeedCollectionResponse[keyof tApiListingFeedCollectionResponse];

export type tApiListingFetchRequest = {
	/**
	 * Query object for listing fetch
	 */
	body?: tListingQuery;
	path?: never;
	query?: never;
	url: "/api/session/listing/fetch";
};

export type apiListingFetchErrors = {
	/**
	 * Listing not found
	 */
	404: tErrorDto;
};

export type apiListingFetchError =
	apiListingFetchErrors[keyof apiListingFetchErrors];

export type tApiListingFetchResponse = {
	/**
	 * Return a listing based on the provided query
	 */
	200: tListingDto;
};

export type apiListingFetchResponse =
	tApiListingFetchResponse[keyof tApiListingFetchResponse];

export type tApiListingCollectionRequest = {
	body?: tListingQuery;
	path?: never;
	query?: never;
	url: "/api/session/listing/collection";
};

export type tApiListingCollectionResponse = {
	/**
	 * Access collection of listings based on provided query
	 */
	200: tListingCollection;
};

export type apiListingCollectionResponse =
	tApiListingCollectionResponse[keyof tApiListingCollectionResponse];

export type tApiListingCountRequest = {
	body?: tListingCountQuery;
	path?: never;
	query?: never;
	url: "/api/session/listing/count";
};

export type tApiListingCountResponse = {
	/**
	 * Return counts based on provided query
	 */
	200: tCount;
};

export type apiListingCountResponse =
	tApiListingCountResponse[keyof tApiListingCountResponse];

export type tApiGalleryFetchRequest = {
	/**
	 * Query object for gallery fetch
	 */
	body?: tGalleryQuery;
	path?: never;
	query?: never;
	url: "/api/session/gallery/fetch";
};

export type apiGalleryFetchErrors = {
	/**
	 * Gallery item not found
	 */
	404: tErrorDto;
};

export type apiGalleryFetchError =
	apiGalleryFetchErrors[keyof apiGalleryFetchErrors];

export type tApiGalleryFetchResponse = {
	/**
	 * Return a gallery item based on the provided query
	 */
	200: tGalleryDto;
};

export type apiGalleryFetchResponse =
	tApiGalleryFetchResponse[keyof tApiGalleryFetchResponse];

export type tApiGalleryCollectionRequest = {
	body?: tGalleryQuery;
	path?: never;
	query?: never;
	url: "/api/session/gallery/collection";
};

export type tApiGalleryCollectionResponse = {
	/**
	 * Access collection of gallery items based on provided query
	 */
	200: tGalleryCollection;
};

export type apiGalleryCollectionResponse =
	tApiGalleryCollectionResponse[keyof tApiGalleryCollectionResponse];

export type tApiGalleryCountRequest = {
	body?: tGalleryQuery;
	path?: never;
	query?: never;
	url: "/api/session/gallery/count";
};

export type tApiGalleryCountResponse = {
	/**
	 * Return counts based on provided query
	 */
	200: tCount;
};

export type apiGalleryCountResponse =
	tApiGalleryCountResponse[keyof tApiGalleryCountResponse];

export type tApiUploadCreateRequest = {
	/**
	 * Data for creating a new upload
	 */
	body?: tUploadCreate;
	path?: never;
	query?: never;
	url: "/api/session/upload/create";
};

export type apiUploadCreateErrors = {
	/**
	 * Invalid URL
	 */
	400: tErrorDto;
};

export type apiUploadCreateError =
	apiUploadCreateErrors[keyof apiUploadCreateErrors];

export type tApiUploadCreateResponse = {
	/**
	 * The created upload
	 */
	201: tUploadDto;
};

export type apiUploadCreateResponse =
	tApiUploadCreateResponse[keyof tApiUploadCreateResponse];

export type tApiUploadFetchRequest = {
	/**
	 * Query object for upload fetch
	 */
	body?: tUploadQuery;
	path?: never;
	query?: never;
	url: "/api/session/upload/fetch";
};

export type apiUploadFetchErrors = {
	/**
	 * Upload not found
	 */
	404: tErrorDto;
};

export type apiUploadFetchError =
	apiUploadFetchErrors[keyof apiUploadFetchErrors];

export type tApiUploadFetchResponse = {
	/**
	 * Return an upload item based on the provided query
	 */
	200: tUploadDto;
};

export type apiUploadFetchResponse =
	tApiUploadFetchResponse[keyof tApiUploadFetchResponse];

export type tApiUploadCollectionRequest = {
	body?: tUploadQuery;
	path?: never;
	query?: never;
	url: "/api/session/upload/collection";
};

export type tApiUploadCollectionResponse = {
	/**
	 * Access collection of upload items based on provided query
	 */
	200: tUploadCollection;
};

export type apiUploadCollectionResponse =
	tApiUploadCollectionResponse[keyof tApiUploadCollectionResponse];

export type tApiUploadCountRequest = {
	body?: tUploadQuery;
	path?: never;
	query?: never;
	url: "/api/session/upload/count";
};

export type tApiUploadCountResponse = {
	/**
	 * Return counts based on provided query
	 */
	200: tCount;
};

export type apiUploadCountResponse =
	tApiUploadCountResponse[keyof tApiUploadCountResponse];

export type tApiLocationAutocompleteRequest = {
	/**
	 * Request body for location autocomplete
	 */
	body?: tLocationAutocomplete;
	path?: never;
	query?: never;
	url: "/api/session/location/autocomplete";
};

export type tApiLocationAutocompleteResponse = {
	/**
	 * Location(s) found (cache hit)
	 */
	200: Array<tLocationDto>;
	/**
	 * Location(s) created (cache miss)
	 */
	201: Array<tLocationDto>;
};

export type apiLocationAutocompleteResponse =
	tApiLocationAutocompleteResponse[keyof tApiLocationAutocompleteResponse];

export type tApiLocationFetchRequest = {
	/**
	 * Query object for location fetch
	 */
	body?: tLocationQuery;
	path?: never;
	query?: never;
	url: "/api/session/location/fetch";
};

export type apiLocationFetchErrors = {
	/**
	 * Location not found
	 */
	404: tErrorDto;
};

export type apiLocationFetchError =
	apiLocationFetchErrors[keyof apiLocationFetchErrors];

export type tApiLocationFetchResponse = {
	/**
	 * Return a location based on the provided query
	 */
	200: tLocationDto;
};

export type apiLocationFetchResponse =
	tApiLocationFetchResponse[keyof tApiLocationFetchResponse];

export type tApiS3PresignRequest = {
	body: tS3PreSignRequest;
	path?: never;
	query?: never;
	url: "/api/session/s3/pre-sign";
};

export type apiS3PresignErrors = {
	/**
	 * Unauthorized (path prefix must match user).
	 */
	403: tErrorDto;
	/**
	 * Failed to generate pre-signed URL.
	 */
	500: tErrorDto;
};

export type apiS3PresignError = apiS3PresignErrors[keyof apiS3PresignErrors];

export type tApiS3PresignResponse = {
	/**
	 * Pre-signed URL generated successfully.
	 */
	200: tS3PreSignResponse;
};

export type apiS3PresignResponse =
	tApiS3PresignResponse[keyof tApiS3PresignResponse];

export type tApiUserExPatchRequest = {
	/**
	 * User extended information to update
	 */
	body?: tUserPatch;
	path?: never;
	query?: never;
	url: "/api/session/user-ex";
};

export type apiUserExPatchErrors = {
	/**
	 * Internal server error
	 */
	500: tErrorDto;
};

export type apiUserExPatchError =
	apiUserExPatchErrors[keyof apiUserExPatchErrors];

export type tApiUserExPatchResponse = {
	/**
	 * User extended information updated successfully
	 */
	204: void;
};

export type apiUserExPatchResponse =
	tApiUserExPatchResponse[keyof tApiUserExPatchResponse];

export type tApiFeedCreateRequest = {
	/**
	 * Data for creating a new feed item
	 */
	body?: tFeedCreate;
	path?: never;
	query?: never;
	url: "/api/session/feed/create";
};

export type apiFeedCreateErrors = {
	/**
	 * Internal server error
	 */
	500: tErrorDto;
};

export type apiFeedCreateError = apiFeedCreateErrors[keyof apiFeedCreateErrors];

export type tApiFeedCreateResponse = {
	/**
	 * The created feed item
	 */
	201: tFeedDto;
};

export type apiFeedCreateResponse =
	tApiFeedCreateResponse[keyof tApiFeedCreateResponse];

export type tApiFeedPatchRequest = {
	/**
	 * Data for updating a feed item
	 */
	body?: tFeedPatch;
	path?: never;
	query?: never;
	url: "/api/session/feed/patch";
};

export type apiFeedPatchErrors = {
	/**
	 * Feed item not found
	 */
	404: tErrorDto;
	/**
	 * Internal server error
	 */
	500: tErrorDto;
};

export type apiFeedPatchError = apiFeedPatchErrors[keyof apiFeedPatchErrors];

export type tApiFeedPatchResponse = {
	/**
	 * The updated feed item
	 */
	200: tFeedDto;
};

export type apiFeedPatchResponse =
	tApiFeedPatchResponse[keyof tApiFeedPatchResponse];

export type tApiFeedFetchRequest = {
	/**
	 * Query object for feed fetch
	 */
	body?: tFeedQuery;
	path?: never;
	query?: never;
	url: "/api/session/feed/fetch";
};

export type apiFeedFetchErrors = {
	/**
	 * Feed item not found
	 */
	404: tErrorDto;
};

export type apiFeedFetchError = apiFeedFetchErrors[keyof apiFeedFetchErrors];

export type tApiFeedFetchResponse = {
	/**
	 * Return a feed item based on the provided query
	 */
	200: tFeedDto;
};

export type apiFeedFetchResponse =
	tApiFeedFetchResponse[keyof tApiFeedFetchResponse];

export type tApiFeedCollectionRequest = {
	body?: tFeedQuery;
	path?: never;
	query?: never;
	url: "/api/session/feed/collection";
};

export type tApiFeedCollectionResponse = {
	/**
	 * Access collection of feed items based on provided query
	 */
	200: tFeedCollection;
};

export type apiFeedCollectionResponse =
	tApiFeedCollectionResponse[keyof tApiFeedCollectionResponse];

export type tApiFeedCountRequest = {
	body?: tFeedQuery;
	path?: never;
	query?: never;
	url: "/api/session/feed/count";
};

export type tApiFeedCountResponse = {
	/**
	 * Return counts based on provided query
	 */
	200: tCount;
};

export type apiFeedCountResponse =
	tApiFeedCountResponse[keyof tApiFeedCountResponse];

export type tApiFeedDeleteRequest = {
	/**
	 * Query object for feed deletion
	 */
	body?: tFeedQuery;
	path?: never;
	query?: never;
	url: "/api/session/feed/delete";
};

export type apiFeedDeleteErrors = {
	/**
	 * Feed item not found
	 */
	404: tErrorDto;
	/**
	 * Internal server error
	 */
	500: tErrorDto;
};

export type apiFeedDeleteError = apiFeedDeleteErrors[keyof apiFeedDeleteErrors];

export type tApiFeedDeleteResponse = {
	/**
	 * The deleted feed item
	 */
	200: tFeedDto;
};

export type apiFeedDeleteResponse =
	tApiFeedDeleteResponse[keyof tApiFeedDeleteResponse];
