// This file is auto-generated by @hey-api/openapi-ts

export const sNoticeTypeEnum = {
    type: 'string',
    enum: [
        'info',
        'warning',
        'error'
    ]
} as const;

export const sNotice = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/NoticeTypeEnum'
        }
    },
    required: [
        'message',
        'type'
    ]
} as const;

export const sGitHubHistory = {
    type: 'object',
    properties: {
        date: {
            type: 'string',
            example: '2025-12-17'
        },
        count: {
            type: 'integer',
            minimum: 0,
            example: 3
        }
    },
    required: [
        'date',
        'count'
    ]
} as const;
