// This file is auto-generated by @hey-api/openapi-ts

export type clientOptions = {
    baseURL: 'http://obsidian-ii.local:3032' | (string & {});
};

/**
 * Type of notice
 */
export const tNoticeTypeEnum = {
    info: 'info',
    warning: 'warning',
    error: 'error'
} as const;

/**
 * Type of notice
 */
export type tNoticeTypeEnum = typeof tNoticeTypeEnum[keyof typeof tNoticeTypeEnum];

/**
 * Just a note sent from various reasons, usually when something is fucked up.
 */
export type tNotice = {
    /**
     * Message
     */
    message: string;
    type: tNoticeTypeEnum;
};

/**
 * GitHub commit history count
 */
export type tGitHubHistory = {
    /**
     * UTC day (YYYY-MM-DD)
     */
    date: string;
    /**
     * Number of commits on this day
     */
    count: number;
};

export type tApiCronHourlyRequest = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/cron/hourly';
};

export type tApiCronHourlyResponse = {
    /**
     * Hourly cron job executed
     */
    200: {
        status: tNotice;
        /**
         * Timestamp when the cron job was executed
         */
        timestamp: string;
    };
};

export type apiCronHourlyResponse = tApiCronHourlyResponse[keyof tApiCronHourlyResponse];

export type tApiCronMonthlyRequest = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/cron/monthly';
};

export type tApiCronMonthlyResponse = {
    /**
     * Monthly cron job executed
     */
    200: {
        status: tNotice;
        /**
         * Timestamp when the cron job was executed
         */
        timestamp: string;
    };
};

export type apiCronMonthlyResponse = tApiCronMonthlyResponse[keyof tApiCronMonthlyResponse];

export type tApiCronDay0Request = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/cron/day-0';
};

export type tApiCronDay0Response = {
    /**
     * Daily cron job executed (hour 0)
     */
    200: {
        status: tNotice;
        /**
         * Timestamp when the cron job was executed
         */
        timestamp: string;
    };
};

export type apiCronDay0Response = tApiCronDay0Response[keyof tApiCronDay0Response];

export type tApiCronDay4Request = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/cron/day-4';
};

export type tApiCronDay4Response = {
    /**
     * Daily cron job executed (hour 4)
     */
    200: {
        status: tNotice;
        /**
         * Timestamp when the cron job was executed
         */
        timestamp: string;
    };
};

export type apiCronDay4Response = tApiCronDay4Response[keyof tApiCronDay4Response];

export type tApiCronDay8Request = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/cron/day-8';
};

export type tApiCronDay8Response = {
    /**
     * Daily cron job executed (hour 8)
     */
    200: {
        status: tNotice;
        /**
         * Timestamp when the cron job was executed
         */
        timestamp: string;
    };
};

export type apiCronDay8Response = tApiCronDay8Response[keyof tApiCronDay8Response];

export type tApiCronDay12Request = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/cron/day-12';
};

export type tApiCronDay12Response = {
    /**
     * Daily cron job executed (hour 12)
     */
    200: {
        status: tNotice;
        /**
         * Timestamp when the cron job was executed
         */
        timestamp: string;
    };
};

export type apiCronDay12Response = tApiCronDay12Response[keyof tApiCronDay12Response];

export type tApiCronDay16Request = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/cron/day-16';
};

export type tApiCronDay16Response = {
    /**
     * Daily cron job executed (hour 16)
     */
    200: {
        status: tNotice;
        /**
         * Timestamp when the cron job was executed
         */
        timestamp: string;
    };
};

export type apiCronDay16Response = tApiCronDay16Response[keyof tApiCronDay16Response];

export type tApiCronDay20Request = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/cron/day-20';
};

export type tApiCronDay20Response = {
    /**
     * Daily cron job executed (hour 20)
     */
    200: {
        status: tNotice;
        /**
         * Timestamp when the cron job was executed
         */
        timestamp: string;
    };
};

export type apiCronDay20Response = tApiCronDay20Response[keyof tApiCronDay20Response];

export type tApiGithubHistoryRequest = {
    body?: never;
    path?: never;
    query: {
        /**
         * How many weeks back (including the current week) to return
         */
        weeks: number;
    };
    url: '/api/public/github/history';
};

export type apiGithubHistoryErrors = {
    /**
     * Failed to sync/fetch history from GitHub
     */
    500: tNotice;
};

export type apiGithubHistoryError = apiGithubHistoryErrors[keyof apiGithubHistoryErrors];

export type tApiGithubHistoryResponse = {
    /**
     * GitHub commit history (cached)
     */
    200: Array<tGitHubHistory>;
};

export type apiGithubHistoryResponse = tApiGithubHistoryResponse[keyof tApiGithubHistoryResponse];

export type tApiHealthRequest = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/health';
};

export type tApiHealthResponse = {
    /**
     * Just health check
     */
    200: {
        /**
         * Health status
         */
        status: boolean;
    };
};

export type apiHealthResponse = tApiHealthResponse[keyof tApiHealthResponse];

export type tApiJanitorCleanupRequest = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/janitor/cleanup';
};

export type apiJanitorCleanupErrors = {
    /**
     * Error during cleanup
     */
    500: tNotice;
};

export type apiJanitorCleanupError = apiJanitorCleanupErrors[keyof apiJanitorCleanupErrors];

export type tApiJanitorCleanupResponse = {
    /**
     * When cleanup is done
     */
    200: Array<{
        /**
         * Type of cleanup operation
         */
        type: string;
        /**
         * Total items scanned
         */
        total: number;
        /**
         * Number of items deleted
         */
        deleted: number;
    }>;
};

export type apiJanitorCleanupResponse = tApiJanitorCleanupResponse[keyof tApiJanitorCleanupResponse];

export type tApiMigrationRunRequest = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/migration/run';
};

export type tApiMigrationRunResponse = {
    /**
     * Executes app migrations
     */
    200: Array<{
        /**
         * Migration name run
         */
        migrationName: string;
        /**
         * Migration direction
         */
        direction: 'Up' | 'Down';
        /**
         * Migration status
         */
        status: 'Success' | 'Error' | 'NotExecuted';
    }>;
};

export type apiMigrationRunResponse = tApiMigrationRunResponse[keyof tApiMigrationRunResponse];

export type tApiSeedRequest = {
    /**
     * User data for seeding
     */
    body?: {
        /**
         * User data for seeding
         */
        email: string;
        transaction: {
            /**
             * Number of listings to create transactions for
             */
            count: number;
            /**
             * Number of months to create transactions for
             */
            months: number;
        };
    };
    path?: never;
    query?: never;
    url: '/api/public/seed';
};

export type apiSeedErrors = {
    /**
     * Invalid request
     */
    400: tNotice;
    /**
     * Access denied
     */
    403: tNotice;
    /**
     * User not found
     */
    404: tNotice;
    /**
     * Internal server error
     */
    500: tNotice;
};

export type apiSeedError = apiSeedErrors[keyof apiSeedErrors];

export type tApiSeedResponse = {
    /**
     * Seed operation completed
     */
    201: unknown;
};
