// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Current status of the listing transaction
 */
export const zTransactionStatusEnum = z.enum([
    'pending',
    'open',
    'resolved',
    'dispute',
    'sold',
    'rejected',
    'expired',
    'success',
    'closed'
]).register(z.globalRegistry, {
    description: 'Current status of the listing transaction'
});

export type zTransactionStatusEnum = z.infer<typeof zTransactionStatusEnum>;

/**
 * Upload file metadata
 */
export const zUpload = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'ID of the upload'
    }),
    url: z.url().register(z.globalRegistry, {
        description: 'Public URL to the uploaded file'
    })
}).register(z.globalRegistry, {
    description: 'Upload file metadata'
});

export type zUpload = z.infer<typeof zUpload>;

/**
 * Gallery item data
 */
export const zGalleryItem = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'ID of the gallery item'
    }),
    galleryId: z.string().register(z.globalRegistry, {
        description: 'ID of the gallery this item belongs to'
    }),
    uploadId: z.string().register(z.globalRegistry, {
        description: 'ID of the upload this image belongs to'
    }),
    sort: z.number().register(z.globalRegistry, {
        description: 'Sort order of the image in the gallery'
    }),
    upload: zUpload
}).register(z.globalRegistry, {
    description: 'Gallery item data'
});

export type zGalleryItem = z.infer<typeof zGalleryItem>;

/**
 * Gallery data with items
 */
export const zGallery = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'ID of the gallery'
    }),
    items: z.array(zGalleryItem).register(z.globalRegistry, {
        description: 'Gallery items sorted by sort order'
    })
}).register(z.globalRegistry, {
    description: 'Gallery data with items'
});

export type zGallery = z.infer<typeof zGallery>;

/**
 * Price type of the listing
 */
export const zListingPriceEnum = z.enum(['closed', 'open']).register(z.globalRegistry, {
    description: 'Price type of the listing'
});

export type zListingPriceEnum = z.infer<typeof zListingPriceEnum>;

/**
 * List of available currencies
 */
export const zCurrencyEnum = z.enum([
    'CZK',
    'EUR',
    'USD',
    'GBP',
    'PLN',
    'HUF',
    'CHF'
]).register(z.globalRegistry, {
    description: 'List of available currencies'
});

export type zCurrencyEnum = z.infer<typeof zCurrencyEnum>;

/**
 * Direction of the transaction entry from the current viewer perspective
 */
export const zTransactionEntryDirectionEnum = z.enum([
    'in',
    'out',
    'system'
]).register(z.globalRegistry, {
    description: 'Direction of the transaction entry from the current viewer perspective'
});

export type zTransactionEntryDirectionEnum = z.infer<typeof zTransactionEntryDirectionEnum>;

/**
 * Transaction text entry with user-authored message payload
 */
export const zTransactionEntryText = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'Transaction entry identifier'
    }),
    transactionId: z.string().register(z.globalRegistry, {
        description: 'Transaction identifier'
    }),
    userId: z.string().nullable(),
    createdAt: z.string().register(z.globalRegistry, {
        description: 'Creation timestamp'
    }),
    kind: z.enum(['text']),
    payload: z.object({
        text: z.string().register(z.globalRegistry, {
            description: 'Text entry body'
        })
    }),
    direction: zTransactionEntryDirectionEnum
}).register(z.globalRegistry, {
    description: 'Transaction text entry with user-authored message payload'
});

export type zTransactionEntryText = z.infer<typeof zTransactionEntryText>;

/**
 * Transaction gallery entry with linked gallery payload
 */
export const zTransactionEntryGallery = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'Transaction entry identifier'
    }),
    transactionId: z.string().register(z.globalRegistry, {
        description: 'Transaction identifier'
    }),
    userId: z.string().nullable(),
    createdAt: z.string().register(z.globalRegistry, {
        description: 'Creation timestamp'
    }),
    kind: z.enum(['gallery']),
    payload: z.object({
        galleryId: z.string().register(z.globalRegistry, {
            description: 'Gallery identifier linked to this entry'
        })
    }),
    direction: zTransactionEntryDirectionEnum
}).register(z.globalRegistry, {
    description: 'Transaction gallery entry with linked gallery payload'
});

export type zTransactionEntryGallery = z.infer<typeof zTransactionEntryGallery>;

/**
 * Transaction location entry with linked location payload
 */
export const zTransactionEntryLocation = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'Transaction entry identifier'
    }),
    transactionId: z.string().register(z.globalRegistry, {
        description: 'Transaction identifier'
    }),
    userId: z.string().nullable(),
    createdAt: z.string().register(z.globalRegistry, {
        description: 'Creation timestamp'
    }),
    kind: z.enum(['location']),
    payload: z.object({
        locationId: z.string().register(z.globalRegistry, {
            description: 'Location identifier linked to this entry'
        })
    }),
    direction: zTransactionEntryDirectionEnum
}).register(z.globalRegistry, {
    description: 'Transaction location entry with linked location payload'
});

export type zTransactionEntryLocation = z.infer<typeof zTransactionEntryLocation>;

/**
 * Transaction package entry with shipment tracking payload
 */
export const zTransactionEntryPackage = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'Transaction entry identifier'
    }),
    transactionId: z.string().register(z.globalRegistry, {
        description: 'Transaction identifier'
    }),
    userId: z.string().nullable(),
    createdAt: z.string().register(z.globalRegistry, {
        description: 'Creation timestamp'
    }),
    kind: z.enum(['package']),
    payload: z.object({
        link: z.url().register(z.globalRegistry, {
            description: 'Package tracking link'
        }),
        number: z.string().nullable()
    }),
    direction: zTransactionEntryDirectionEnum
}).register(z.globalRegistry, {
    description: 'Transaction package entry with shipment tracking payload'
});

export type zTransactionEntryPackage = z.infer<typeof zTransactionEntryPackage>;

/**
 * Transaction personal entry with contact and handoff payload
 */
export const zTransactionEntryPersonal = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'Transaction entry identifier'
    }),
    transactionId: z.string().register(z.globalRegistry, {
        description: 'Transaction identifier'
    }),
    userId: z.string().nullable(),
    createdAt: z.string().register(z.globalRegistry, {
        description: 'Creation timestamp'
    }),
    kind: z.enum(['personal']),
    payload: z.object({
        name: z.string().register(z.globalRegistry, {
            description: 'Contact name'
        }),
        phone: z.string().register(z.globalRegistry, {
            description: 'Contact phone'
        }),
        email: z.email().register(z.globalRegistry, {
            description: 'Contact email'
        }),
        locationId: z.string().register(z.globalRegistry, {
            description: 'Contact location identifier'
        })
    }),
    direction: zTransactionEntryDirectionEnum
}).register(z.globalRegistry, {
    description: 'Transaction personal entry with contact and handoff payload'
});

export type zTransactionEntryPersonal = z.infer<typeof zTransactionEntryPersonal>;

/**
 * Common (shared) entries sharing same shape
 */
export const zTransactionCommonKindEnum = z.enum([
    'status-pending',
    'status-open',
    'status-resolved',
    'status-dispute-buyer',
    'status-dispute-seller',
    'status-rejected-buyer',
    'status-rejected-seller',
    'status-sold',
    'status-expired',
    'status-success',
    'status-closed'
]).register(z.globalRegistry, {
    description: 'Common (shared) entries sharing same shape'
});

export type zTransactionCommonKindEnum = z.infer<typeof zTransactionCommonKindEnum>;

/**
 * Transaction system entry with shared status or informational payload
 */
export const zTransactionEntryCommon = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'Transaction entry identifier'
    }),
    transactionId: z.string().register(z.globalRegistry, {
        description: 'Transaction identifier'
    }),
    userId: z.string().nullable(),
    createdAt: z.string().register(z.globalRegistry, {
        description: 'Creation timestamp'
    }),
    kind: zTransactionCommonKindEnum,
    payload: z.object({
        text: z.string().register(z.globalRegistry, {
            description: 'Translation key for the system/status timeline entry'
        })
    }),
    direction: zTransactionEntryDirectionEnum
}).register(z.globalRegistry, {
    description: 'Transaction system entry with shared status or informational payload'
});

export type zTransactionEntryCommon = z.infer<typeof zTransactionEntryCommon>;

/**
 * Transaction timeline entry
 */
export const zTransactionEntry = z.union([
    z.object({
        kind: z.literal('text')
    }).and(zTransactionEntryText),
    z.object({
        kind: z.literal('gallery')
    }).and(zTransactionEntryGallery),
    z.object({
        kind: z.literal('location')
    }).and(zTransactionEntryLocation),
    z.object({
        kind: z.literal('package')
    }).and(zTransactionEntryPackage),
    z.object({
        kind: z.literal('personal')
    }).and(zTransactionEntryPersonal),
    z.object({
        kind: z.union([
            z.literal('status-pending'),
            z.literal('status-open'),
            z.literal('status-resolved'),
            z.literal('status-dispute-buyer'),
            z.literal('status-dispute-seller'),
            z.literal('status-rejected-buyer'),
            z.literal('status-rejected-seller'),
            z.literal('status-sold'),
            z.literal('status-expired'),
            z.literal('status-success'),
            z.literal('status-closed')
        ])
    }).and(zTransactionEntryCommon)
]);

export type zTransactionEntry = z.infer<typeof zTransactionEntry>;

/**
 * Location data
 */
export const zLocation = z.object({
    id: z.string(),
    query: z.string().register(z.globalRegistry, {
        description: 'The query that was used to get the location'
    }),
    lang: z.string().register(z.globalRegistry, {
        description: 'The language that was used to get the location'
    }),
    country: z.string().register(z.globalRegistry, {
        description: 'The country that the location is in'
    }),
    code: z.string().register(z.globalRegistry, {
        description: 'Country code'
    }),
    county: z.string().nullable(),
    municipality: z.string().nullable(),
    state: z.string().nullable(),
    address: z.string().register(z.globalRegistry, {
        description: 'Full address preview of a location'
    }),
    city: z.string().nullable(),
    street: z.string().nullable(),
    zip: z.string().nullable(),
    confidence: z.number().register(z.globalRegistry, {
        description: 'Confidence score of the location (based on query)'
    }),
    hash: z.string().register(z.globalRegistry, {
        description: 'Used to uniquely identify this location entry'
    }),
    lat: z.number().register(z.globalRegistry, {
        description: 'Latitude of the location'
    }),
    lon: z.number().register(z.globalRegistry, {
        description: 'Longitude of the location'
    })
}).register(z.globalRegistry, {
    description: 'Location data'
});

export type zLocation = z.infer<typeof zLocation>;

/**
 * Transaction data
 */
export const zTransaction = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'ID of the transaction'
    }),
    listingId: z.string().register(z.globalRegistry, {
        description: 'ID of the related listing'
    }),
    createdAt: z.string().register(z.globalRegistry, {
        description: 'Creation timestamp'
    }),
    updatedAt: z.string().register(z.globalRegistry, {
        description: 'Last update timestamp'
    }),
    status: zTransactionStatusEnum,
    statusUpdatedAt: z.string().register(z.globalRegistry, {
        description: 'Last status update timestamp'
    }),
    expiresAt: z.string().register(z.globalRegistry, {
        description: 'Expiration timestamp'
    }),
    title: z.string().register(z.globalRegistry, {
        description: 'Transaction title'
    }),
    gallery: zGallery,
    price: z.number().register(z.globalRegistry, {
        description: 'Price of the listing'
    }),
    priceType: zListingPriceEnum,
    currency: zCurrencyEnum,
    entry: zTransactionEntry,
    unreadCount: z.number().register(z.globalRegistry, {
        description: 'Unread inbox seller-message count for this transaction'
    }),
    location: zLocation
}).register(z.globalRegistry, {
    description: 'Transaction data'
});

export type zTransaction = z.infer<typeof zTransaction>;

/**
 * Type of notice
 */
export const zNoticeTypeEnum = z.enum([
    'info',
    'warning',
    'error'
]).register(z.globalRegistry, {
    description: 'Type of notice'
});

export type zNoticeTypeEnum = z.infer<typeof zNoticeTypeEnum>;

/**
 * Just a note sent from various reasons, usually when something is fucked up.
 */
export const zNotice = z.object({
    message: z.string().register(z.globalRegistry, {
        description: 'Message'
    }),
    type: zNoticeTypeEnum
}).register(z.globalRegistry, {
    description: 'Just a note sent from various reasons, usually when something is fucked up.'
});

export type zNotice = z.infer<typeof zNotice>;

/**
 * Cursor for pagination
 */
export const zCursor = z.object({
    page: z.number().gte(0).register(z.globalRegistry, {
        description: 'Page number (0-indexed)'
    }),
    size: z.number().gte(1).lte(1000).register(z.globalRegistry, {
        description: 'Page size'
    })
}).register(z.globalRegistry, {
    description: 'Cursor for pagination'
});

export type zCursor = z.infer<typeof zCursor>;

/**
 * Filter object for transaction collection
 */
export const zTransactionFilter = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'This filter matches the exact id'
    }).optional(),
    idIn: z.array(z.string()).register(z.globalRegistry, {
        description: 'This filter matches the ids'
    }).optional(),
    fulltext: z.string().register(z.globalRegistry, {
        description: 'Runs fulltext on the collection/query.'
    }).optional(),
    userId: z.string().register(z.globalRegistry, {
        description: 'This filter matches the exact userId'
    }).optional(),
    listingId: z.string().register(z.globalRegistry, {
        description: 'This filter matches the exact listingId'
    }).optional(),
    active: z.boolean().register(z.globalRegistry, {
        description: 'When true, match transactions with unread inbox activity for the current side; when false, match transactions without unread inbox activity for the current side'
    }).optional(),
    terminal: z.boolean().register(z.globalRegistry, {
        description: 'When true, match transactions already in a terminal status; when false, match transactions that still have a non-terminal status'
    }).optional(),
    status: zTransactionStatusEnum.and(z.unknown().register(z.globalRegistry, {
        description: 'This filter matches the current status of the transaction'
    })).optional(),
    statusIn: z.array(zTransactionStatusEnum).register(z.globalRegistry, {
        description: 'This filter matches any of the provided statuses for the current status of the transaction'
    }).optional()
}).register(z.globalRegistry, {
    description: 'Filter object for transaction collection'
});

export type zTransactionFilter = z.infer<typeof zTransactionFilter>;

/**
 * App-based filters
 */
export const zTransactionWhere = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'This filter matches the exact id'
    }).optional(),
    idIn: z.array(z.string()).register(z.globalRegistry, {
        description: 'This filter matches the ids'
    }).optional(),
    fulltext: z.string().register(z.globalRegistry, {
        description: 'Runs fulltext on the collection/query.'
    }).optional(),
    userId: z.string().register(z.globalRegistry, {
        description: 'This filter matches the exact userId'
    }).optional(),
    listingId: z.string().register(z.globalRegistry, {
        description: 'This filter matches the exact listingId'
    }).optional(),
    active: z.boolean().register(z.globalRegistry, {
        description: 'When true, match transactions with unread inbox activity for the current side; when false, match transactions without unread inbox activity for the current side'
    }).optional(),
    terminal: z.boolean().register(z.globalRegistry, {
        description: 'When true, match transactions already in a terminal status; when false, match transactions that still have a non-terminal status'
    }).optional(),
    status: zTransactionStatusEnum.and(z.unknown().register(z.globalRegistry, {
        description: 'This filter matches the current status of the transaction'
    })).optional(),
    statusIn: z.array(zTransactionStatusEnum).register(z.globalRegistry, {
        description: 'This filter matches any of the provided statuses for the current status of the transaction'
    }).optional()
}).register(z.globalRegistry, {
    description: 'App-based filters'
});

export type zTransactionWhere = z.infer<typeof zTransactionWhere>;

/**
 * Field of the transaction sort
 */
export const zTransactionSortField = z.enum([
    'createdAt',
    'updatedAt',
    'expiresAt',
    'lastAt',
    'status'
]).register(z.globalRegistry, {
    description: 'Field of the transaction sort'
});

export type zTransactionSortField = z.infer<typeof zTransactionSortField>;

/**
 * Order
 */
export const zOrderEnum = z.enum(['asc', 'desc']).register(z.globalRegistry, {
    description: 'Order'
});

export type zOrderEnum = z.infer<typeof zOrderEnum>;

/**
 * Sort object for transaction collection
 */
export const zTransactionSort = z.object({
    field: zTransactionSortField,
    order: zOrderEnum
}).register(z.globalRegistry, {
    description: 'Sort object for transaction collection'
});

export type zTransactionSort = z.infer<typeof zTransactionSort>;

/**
 * Query object for transaction collection
 */
export const zTransactionQuery = z.object({
    cursor: zCursor.optional(),
    filter: zTransactionFilter.optional(),
    where: zTransactionWhere.optional(),
    sort: z.array(zTransactionSort).optional()
}).register(z.globalRegistry, {
    description: 'Query object for transaction collection'
});

export type zTransactionQuery = z.infer<typeof zTransactionQuery>;

/**
 * Count data
 */
export const zCount = z.object({
    where: z.number().register(z.globalRegistry, {
        description: 'Count of items based on provided where query.'
    }),
    filter: z.number().register(z.globalRegistry, {
        description: 'Count of items based on provided filter query.'
    }),
    total: z.number().register(z.globalRegistry, {
        description: 'Total count of items (no filters applied).'
    }),
    isEmpty: z.boolean().register(z.globalRegistry, {
        description: 'True when total count is empty.'
    }),
    isFilterEmpty: z.boolean().register(z.globalRegistry, {
        description: 'True when filter count is empty while total count has data.'
    })
}).register(z.globalRegistry, {
    description: 'Count data'
});

export type zCount = z.infer<typeof zCount>;

/**
 * Query object for transaction count
 */
export const zTransactionCountQuery = z.object({
    filter: zTransactionFilter.optional(),
    where: zTransactionWhere.optional()
}).register(z.globalRegistry, {
    description: 'Query object for transaction count'
});

export type zTransactionCountQuery = z.infer<typeof zTransactionCountQuery>;

/**
 * Data for creating a new transaction
 */
export const zTransactionCreate = z.object({
    listingId: z.string().register(z.globalRegistry, {
        description: 'ID of the listing to start a transaction for'
    })
}).register(z.globalRegistry, {
    description: 'Data for creating a new transaction'
});

export type zTransactionCreate = z.infer<typeof zTransactionCreate>;

export const zApiTransactionCloseData = z.object({
    body: z.never().optional(),
    path: z.object({
        transactionId: z.string().register(z.globalRegistry, {
            description: 'Transaction identifier'
        })
    }),
    query: z.never().optional()
});

export type zapiTransactionCloseRequest = z.infer<typeof zApiTransactionCloseData>;

/**
 * Transaction was closed
 */
export const zApiTransactionCloseResponse = zTransaction;

export type zapiTransactionCloseResponse = z.infer<typeof zApiTransactionCloseResponse>;

export const zApiTransactionCollectionData = z.object({
    body: zTransactionQuery.optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export type zapiTransactionCollectionRequest = z.infer<typeof zApiTransactionCollectionData>;

/**
 * Access collection of transactions based on provided query
 */
export const zApiTransactionCollectionResponse = z.array(zTransaction).register(z.globalRegistry, {
    description: 'Access collection of transactions based on provided query'
});

export type zapiTransactionCollectionResponse = z.infer<typeof zApiTransactionCollectionResponse>;

export const zApiTransactionCountData = z.object({
    body: zTransactionCountQuery.optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export type zapiTransactionCountRequest = z.infer<typeof zApiTransactionCountData>;

/**
 * Return counts based on provided query
 */
export const zApiTransactionCountResponse = zCount;

export type zapiTransactionCountResponse = z.infer<typeof zApiTransactionCountResponse>;

export const zApiTransactionCreateData = z.object({
    body: zTransactionCreate.optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export type zapiTransactionCreateRequest = z.infer<typeof zApiTransactionCreateData>;

/**
 * The transaction was created
 */
export const zApiTransactionCreateResponse = zTransaction;

export type zapiTransactionCreateResponse = z.infer<typeof zApiTransactionCreateResponse>;

export const zApiTransactionDisputeData = z.object({
    body: z.never().optional(),
    path: z.object({
        transactionId: z.string().register(z.globalRegistry, {
            description: 'Transaction identifier'
        })
    }),
    query: z.never().optional()
});

export type zapiTransactionDisputeRequest = z.infer<typeof zApiTransactionDisputeData>;

/**
 * Transaction was disputed
 */
export const zApiTransactionDisputeResponse = zTransaction;

export type zapiTransactionDisputeResponse = z.infer<typeof zApiTransactionDisputeResponse>;

export const zApiTransactionFetchData = z.object({
    body: zTransactionQuery.optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export type zapiTransactionFetchRequest = z.infer<typeof zApiTransactionFetchData>;

/**
 * Transaction matching provided query
 */
export const zApiTransactionFetchResponse = zTransaction;

export type zapiTransactionFetchResponse = z.infer<typeof zApiTransactionFetchResponse>;

export const zApiTransactionRejectData = z.object({
    body: z.never().optional(),
    path: z.object({
        transactionId: z.string().register(z.globalRegistry, {
            description: 'Transaction identifier'
        })
    }),
    query: z.never().optional()
});

export type zapiTransactionRejectRequest = z.infer<typeof zApiTransactionRejectData>;

/**
 * Transaction was rejected
 */
export const zApiTransactionRejectResponse = zTransaction;

export type zapiTransactionRejectResponse = z.infer<typeof zApiTransactionRejectResponse>;

export const zApiTransactionSuccessData = z.object({
    body: z.never().optional(),
    path: z.object({
        transactionId: z.string().register(z.globalRegistry, {
            description: 'Transaction identifier'
        })
    }),
    query: z.never().optional()
});

export type zapiTransactionSuccessRequest = z.infer<typeof zApiTransactionSuccessData>;

/**
 * Transaction was marked as successful
 */
export const zApiTransactionSuccessResponse = zTransaction;

export type zapiTransactionSuccessResponse = z.infer<typeof zApiTransactionSuccessResponse>;
