name: Production Deploy

on:
    push:
        branches: ["main"]

concurrency:
    group: production-deploy
    cancel-in-progress: false

permissions:
    contents: read

env:
    # -------------------------------
    # Common env. variables
    # -------------------------------
    VITE_DOMAIN: ${{ vars.VITE_DOMAIN }}

    # -------------------------------
    # Web env. variables
    # -------------------------------
    # WEB_ORIGIN: ${{ vars.WEB_ORIGIN }}
    # APP_ORIGIN: ${{ vars.APP_ORIGIN }}
    # VITE_SERVER_API: ${{ vars.VITE_SERVER_API }}
    # VITE_WEB_ASSET_BASE: ${{ vars.VITE_WEB_ASSET_BASE }}
    # VITE_APP_ASSET_BASE: ${{ vars.VITE_APP_ASSET_BASE }}
    # SERVER_UPSTASH_REDIS_REST_URL: ${{ vars.SERVER_UPSTASH_REDIS_REST_URL }}

    # -------------------------------
    # Server env. variables
    # -------------------------------
    SERVER_S3_API: ${{ vars.SERVER_S3_API }}
    SERVER_S3_BUCKET: ${{ vars.SERVER_S3_BUCKET }}
    SERVER_S3_KEY: ${{ secrets.SERVER_S3_KEY }}
    SERVER_S3_SECRET: ${{ secrets.SERVER_S3_SECRET }}

    # --------------------------------
    # Private (sensitive) secrets
    # --------------------------------
    # SERVER_BETTER_AUTH_SECRET: ${{ secrets.SERVER_BETTER_AUTH_SECRET }}

    # SERVER_GEOAPIFY_TOKEN: ${{ secrets.SERVER_GEOAPIFY_TOKEN }}
    # SERVER_JWT_SECRET: ${{ secrets.SERVER_JWT_SECRET }}

    # VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    # SERVER_UPSTASH_REDIS_REST_TOKEN: ${{ secrets.SERVER_UPSTASH_REDIS_REST_TOKEN }}

    # -------------------------------
    # Local (GHA only)
    # -------------------------------
    BUNNY_HOST: ${{ vars.BUNNY_HOST }}
    BUNNY_USER: ${{ vars.BUNNY_USER }}
    BUNNY_TOKEN: ${{ secrets.BUNNY_TOKEN }}
    #
    NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
    NEON_PROJECT_ID: ${{ vars.NEON_PROJECT_ID }}
    #
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
    VERCEL_WEB_PROJECT_ID: ${{ vars.VERCEL_WEB_PROJECT_ID }}
    VERCEL_SERVER_PROJECT_ID: ${{ vars.VERCEL_SERVER_PROJECT_ID }}
    #
    MIGRATION_URL: ${VITE_SERVER_API}/api/public/migration/run

    # -------------------------------
    # Web environment variables list
    # -------------------------------
    WEB_ENV_VARS: "VITE_WEB_ASSETS VITE_SERVER_API"

    # -------------------------------
    # Server environment variables list
    # -------------------------------
    SERVER_ENV_VARS: "SERVER_WEB_ORIGIN SERVER_APP_ORIGIN SERVER_UPSTASH_REDIS_REST_TOKEN SERVER_UPSTASH_REDIS_REST_URL SERVER_GEOAPIFY_TOKEN SERVER_BETTER_AUTH_SECRET SERVER_JWT_SECRET VITE_SERVER_API SERVER_DATABASE_URL SERVER_S3_API SERVER_S3_KEY SERVER_S3_SECRET SERVER_S3_BUCKET"

jobs:
    validate-env:
        name: Validate env
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Check environment variables
              run: |
                  set -euo pipefail
                  : "${BUNNY_HOST:?BUNNY_HOST missing}"
                  : "${BUNNY_TOKEN:?BUNNY_TOKEN missing}"
                  : "${BUNNY_USER:?BUNNY_USER missing}"
                  : "${NEON_API_KEY:?NEON_API_KEY missing}"
                  : "${NEON_PROJECT_ID:?NEON_PROJECT_ID missing}"
                  : "${SERVER_S3_API:?SERVER_S3_API missing}"
                  : "${SERVER_S3_BUCKET:?SERVER_S3_BUCKET missing}"
                  : "${SERVER_S3_KEY:?SERVER_S3_KEY missing}"
                  : "${SERVER_S3_SECRET:?SERVER_S3_SECRET missing}"
                  : "${VERCEL_ORG_ID:?VERCEL_ORG_ID missing}"
                  : "${VERCEL_SERVER_PROJECT_ID:?VERCEL_SERVER_PROJECT_ID missing}"
                  : "${VERCEL_TOKEN:?VERCEL_TOKEN missing}"
                  : "${VERCEL_WEB_PROJECT_ID:?VERCEL_WEB_PROJECT_ID missing}"
                  : "${VITE_DOMAIN:?VITE_DOMAIN missing}"
                  echo "OK: required variables present."

    vercel-env-web:
        name: "Web: Sync env. variables"
        runs-on: ubuntu-latest
        environment: production
        needs: [validate-env]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            # Upsert web build-time envs (production)
            - name: Upsert web env
              env:
                  # Bind the web project for this step; Vercel CLI reads from env
                  VERCEL_PROJECT_ID: ${{ env.VERCEL_WEB_PROJECT_ID }}
              run: |
                  set -euo pipefail
                  for KEY in ${{ env.WEB_ENV_VARS }}; do
                    VAL="${!KEY}"
                    if [ -z "$VAL" ]; then
                      echo "Error: Environment variable '$KEY' is not set"
                      exit 1
                    fi
                    echo "Setting $KEY..."
                    bunx -y vercel@latest env rm "$KEY" production --yes --token "$VERCEL_TOKEN" >/dev/null 2>&1 || true
                    printf "%s" "$VAL" | bunx -y vercel@latest env add "$KEY" production --token "$VERCEL_TOKEN"
                  done

    vercel-env-server:
        name: "Server: Sync env. variables"
        runs-on: ubuntu-latest
        environment: production
        needs: [validate-env]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            # Resolve DATABASE_URL (production branch) from Neon
            - name: Resolve prod DB URL via Neon
              id: neon
              uses: neondatabase/create-branch-action@v6
              with:
                  project_id: ${{ env.NEON_PROJECT_ID }}
                  branch_name: production
                  database: neondb
                  role: neondb_owner
                  api_key: ${{ env.NEON_API_KEY }}

            # Upsert server runtime envs including DATABASE_URL
            - name: Upsert server env
              env:
                  VERCEL_PROJECT_ID: ${{ env.VERCEL_SERVER_PROJECT_ID }}
                  SERVER_DATABASE_URL: ${{ steps.neon.outputs.db_url_pooled }}
              run: |
                  set -euo pipefail
                  for KEY in ${{ env.SERVER_ENV_VARS }}; do
                    VAL="${!KEY}"
                    if [ -z "$VAL" ]; then
                      echo "Error: Environment variable '$KEY' is not set"
                      exit 1
                    fi
                    echo "Setting $KEY..."
                    bunx -y vercel@latest env rm "$KEY" production --yes --token "$VERCEL_TOKEN" >/dev/null 2>&1 || true
                    printf "%s" "$VAL" | bunx -y vercel@latest env add "$KEY" production --token "$VERCEL_TOKEN"
                  done

    web-build:
        name: Build web
        runs-on: ubuntu-latest
        environment: production
        needs: [vercel-env-web]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Cache node_modules (root)
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: root-nm-${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
                  restore-keys: |
                      root-nm-${{ runner.os }}-bun-

            - name: Cache node_modules (web, isolated)
              uses: actions/cache@v4
              with:
                  path: apps/web/node_modules
                  key: web-nm-${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
                  restore-keys: |
                      web-nm-${{ runner.os }}-bun-

            - name: Install dependencies (root)
              run: bun install

            - name: Build web
              working-directory: apps/web
              run: bun run build

            - name: Upload artifact (web prebuilt)
              uses: actions/upload-artifact@v4
              with:
                  name: web
                  path: apps/web/.vercel/output
                  include-hidden-files: true

    server-build:
        name: Build server
        runs-on: ubuntu-latest
        environment: production
        needs: [vercel-env-server]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Cache node_modules (root)
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: root-nm-${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
                  restore-keys: |
                      root-nm-${{ runner.os }}-bun-

            - name: Cache node_modules (server, isolated)
              uses: actions/cache@v4
              with:
                  path: apps/server/node_modules
                  key: server-nm-${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
                  restore-keys: |
                      server-nm-${{ runner.os }}-bun-

            - name: Install dependencies (root, workspace)
              run: bun install

            - name: Build server
              working-directory: apps/server
              run: bun run build

            - name: Upload artifact (server prebuilt)
              uses: actions/upload-artifact@v4
              with:
                  name: server
                  path: apps/server/.vercel/output
                  include-hidden-files: true

    vercel-web:
        name: Deploy web to Vercel
        runs-on: ubuntu-latest
        environment: production
        needs: [web-build]
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: web
                  path: apps/web/.vercel/output

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Strip assets
              working-directory: apps/web
              run: rm -rf .vercel/output/static/assets || true

            - name: Deploy to Vercel (web)
              working-directory: apps/web
              env:
                  VERCEL_PROJECT_ID: ${{ env.VERCEL_WEB_PROJECT_ID }}
              run: |
                  bunx -y vercel@latest deploy \
                    --prebuilt \
                    --prod --yes \
                    --token "$VERCEL_TOKEN"

    vercel-server:
        name: Deploy server to Vercel
        runs-on: ubuntu-latest
        environment: production
        needs: [server-build]
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: server
                  path: apps/server/.vercel/output

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Deploy to Vercel (server)
              working-directory: apps/server
              env:
                  VERCEL_PROJECT_ID: ${{ env.VERCEL_SERVER_PROJECT_ID }}
              run: |
                  bunx -y vercel@latest deploy \
                    --prebuilt \
                    --prod --yes \
                    --token "$VERCEL_TOKEN"

    bunny-cdn:
        name: Update CDN
        runs-on: ubuntu-latest
        environment: production
        needs: [web-build]
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: web
                  path: apps/web/.vercel/output

            - name: Prepare rclone config
              run: |
                  set -euo pipefail
                  CONF="${GITHUB_WORKSPACE}/rclone.conf"
                  OBF=$(docker run --rm rclone/rclone:1.66 obscure "${BUNNY_TOKEN}")
                  cat > "$CONF" <<EOF
                  [bunny]
                  type = sftp
                  host = ${BUNNY_HOST}
                  user = ${BUNNY_USER}
                  port = 22
                  pass = ${OBF}
                  EOF
                  echo "RCLONE_CONFIG=$CONF" >> "$GITHUB_ENV"

            - name: Sync CDN
              uses: docker://rclone/rclone:1.66
              with:
                  args: >
                      sync /github/workspace/apps/web/.vercel/output/static/assets bunny:/assets
                      --config /github/workspace/rclone.conf
                      --inplace
                      --sftp-set-modtime=false
                      --size-only
                      --transfers=8
                      --checkers=16
                      --fast-list
                      --timeout=2m
                      --retries=5
                      --low-level-retries=10
                      --verbose

            - name: Copy root favicon/manifest to CDN /
              uses: docker://rclone/rclone:1.66
              with:
                  args: >
                      copy /github/workspace/apps/web/.vercel/output/static bunny:/
                      --config /github/workspace/rclone.conf
                      --inplace
                      --include "/favicon*.ico"
                      --include "/favicon*.png"
                      --include "/favicon*.svg"
                      --include "/apple-touch-icon*.png"
                      --include "/site.webmanifest"
                      --exclude "*"
                      --sftp-set-modtime=false
                      --transfers=4
                      --checkers=8
                      --timeout=2m
                      --retries=5
                      --low-level-retries=10
                      --verbose

    run-migrations:
        name: Run migrations
        runs-on: ubuntu-latest
        environment: production
        needs: [vercel-server]
        steps:
            - name: Trigger migrations endpoint
              run: |
                  set -euo pipefail
                  code=$(curl -sS -o /dev/null -w "%{http_code}" "$MIGRATION_URL")
                  echo "HTTP $code from $MIGRATION_URL"
                  if [ "$code" != "200" ] && [ "$code" != "204" ]; then
                    echo "Migration trigger failed (expected 200/204)."
                    exit 1
                  fi
