# .github/workflows/deploy-prod-monorepo.yml
name: Prod Deploy (SERVER -> CDN assets -> FE)

on:
    push:
        branches: ["main"]

concurrency:
    group: deploy-prod
    cancel-in-progress: false

permissions:
    contents: read

jobs:
    validate-env:
        name: Validate environment variables & secrets
        runs-on: ubuntu-latest
        environment: production
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
            VERCEL_CLIENT_PROJECT_ID: ${{ vars.VERCEL_CLIENT_PROJECT_ID }}
            VITE_ASSET_BASE: ${{ vars.VITE_ASSET_BASE }}
            BUNNY_HOST: ${{ vars.BUNNY_HOST }}
            BUNNY_USER: ${{ vars.BUNNY_USER }}
            BUNNY_TOKEN: ${{ secrets.BUNNY_TOKEN }}
        steps:
            - name: Check required vars (fail fast)
              run: |
                  set -euo pipefail
                  : "${VERCEL_TOKEN:?VERCEL_TOKEN missing}"
                  : "${VERCEL_ORG_ID:?VERCEL_ORG_ID missing}"
                  : "${VERCEL_CLIENT_PROJECT_ID:?VERCEL_CLIENT_PROJECT_ID missing}"
                  : "${VITE_ASSET_BASE:?VITE_ASSET_BASE missing}"
                  : "${BUNNY_HOST:?BUNNY_HOST missing}"
                  : "${BUNNY_USER:?BUNNY_USER missing}"
                  : "${BUNNY_TOKEN:?BUNNY_TOKEN missing}"
                  echo "OK: required variables present."
                  echo "VITE_ASSET_BASE length: ${#VITE_ASSET_BASE}"
                  echo "BUNNY_HOST: ${BUNNY_HOST}"
                  echo "BUNNY_USER: ${BUNNY_USER}"
                  echo "BUNNY_TOKEN length: ${#BUNNY_TOKEN}"
                  echo "VERCEL_ORG_ID: ${VERCEL_ORG_ID}"
                  echo "VERCEL_CLIENT_PROJECT_ID: ${VERCEL_CLIENT_PROJECT_ID}"
                  echo "VERCEL_TOKEN length: ${#VERCEL_TOKEN}"

    upload-assets:
        name: Build FE & Upload assets to Bunny (rclone SFTP)
        runs-on: ubuntu-latest
        environment: production
        needs: [validate-env]
        env:
            VITE_ASSET_BASE: ${{ vars.VITE_ASSET_BASE }}
            BUNNY_HOST: ${{ vars.BUNNY_HOST }}
            BUNNY_USER: ${{ vars.BUNNY_USER }}
            BUNNY_TOKEN: ${{ secrets.BUNNY_TOKEN }}
        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install deps (FE)
              working-directory: apps/client
              run: bun install --linker=isolated

            - name: Build FE (Vite) with CDN base
              working-directory: apps/client
              env:
                  VITE_ASSET_BASE: ${{ env.VITE_ASSET_BASE }}
              run: bun run build

            # rclone via official Docker image (SFTP on port 22, in-place writes)
            - name: Write rclone config (SFTP -> Bunny)
              run: |
                  CONF="${GITHUB_WORKSPACE}/rclone.conf"
                  OBF=$(docker run --rm rclone/rclone:1.66 obscure "${BUNNY_TOKEN}")
                  cat > "$CONF" <<EOF
                  [bunny]
                  type = sftp
                  host = ${BUNNY_HOST}
                  user = ${BUNNY_USER}
                  port = 22
                  pass = ${OBF}
                  EOF
                  echo "RCLONE_CONFIG=$CONF" >> "$GITHUB_ENV"

            - name: Sync assets to Bunny via rclone (SFTP, skip unchanged, in-place)
              uses: docker://rclone/rclone:1.66
              with:
                  args: >
                      copy /github/workspace/apps/client/dist/assets bunny:/assets
                      --config /github/workspace/rclone.conf
                      --ignore-existing
                      --inplace
                      --sftp-set-modtime=false
                      --transfers=4
                      --checkers=8
                      --no-traverse
                      --timeout=2m
                      --retries=5
                      --low-level-retries=10
                      --verbose

            - name: Strip assets before FE deploy (optional)
              working-directory: apps/client
              run: rm -rf dist/assets

            - name: Save FE dist for next job
              uses: actions/upload-artifact@v4
              with:
                  name: fe-dist
                  path: apps/client/dist

    deploy-fe:
        name: Deploy FE (Vercel, production)
        runs-on: ubuntu-latest
        environment: production
        needs: [upload-assets]
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
            VERCEL_CLIENT_PROJECT_ID: ${{ vars.VERCEL_CLIENT_PROJECT_ID }}
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: fe-dist
                  path: dist

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Deploy FE (production) via bunx
              run: |
                  bun x -y vercel@latest pull --yes --environment=production --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID"
                  bun x -y vercel@latest deploy dist \
                    --prod --yes \
                    --token "$VERCEL_TOKEN" \
                    --scope "$VERCEL_ORG_ID" \
                    --project "$VERCEL_CLIENT_PROJECT_ID"
